#include "agentcad/authoring.hpp"
#include "agentcad/kernel.hpp"
#include "agentcad/model.hpp"
#include "agentcad/service.hpp"
#include "agentcad/jobs.hpp"
#include "agentcad/hash.hpp"
#include <STEPControl_Reader.hxx>
#include <BRepCheck_Analyzer.hxx>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <chrono>
#include <fstream>
#include <functional>
#include <future>
#include <iostream>
#include <numbers>
#include <thread>
using namespace agentcad;
namespace {
int checks=0;
void require(bool value,const std::string& message){++checks;if(!value)throw std::runtime_error(message);}
void near(double a,double b,double tolerance=2e-5){require(std::abs(a-b)<tolerance,"Expected "+std::to_string(b)+", got "+std::to_string(a));}
Error fails(const std::string& code,const std::function<void()>& action){try{action();}catch(const Error& e){require(e.code==code,"Expected "+code+", got "+e.code+": "+e.what());return e;}throw std::runtime_error("Expected "+code);}
struct Temp{fs::path path=temporary_file(fs::temp_directory_path());Temp(){fs::remove(path);directory(path);}~Temp(){std::error_code error;fs::remove_all(path,error);}};
void write(const fs::path& path,const std::string& bytes){std::ofstream stream(path,std::ios::binary);stream<<bytes;require(static_cast<bool>(stream),"Fixture writes");}
Json plane(Json origin={0,0,0},Json normal={0,0,1},Json x={1,0,0}){return {{"origin",origin},{"normal",normal},{"x_direction",x}};}
Json model(Json features,const std::string& output){return {{"schema_version",1},{"units","mm"},{"parameters",Json::object()},{"features",features},{"output",output}};}
Json imported(const std::string& format,const std::string& content){return {{"type",format},{"content",content},{"sha256",sha256(content)}};}
Json profile_model(Json profile,Json workplane=plane(),double depth=3){return model(Json::array({{{"id","profile"},{"type","sketch"},{"workplane",workplane},{"profile",profile}},{{"id","part"},{"type","extrude"},{"input","profile"},{"distance",depth}}}),"part");}
bool curved(const BuiltModel& built,const std::string& kind){const auto topology=built.topology("profile");for(const auto& edge:topology.at("edges"))if(edge.at("curve_kind")==kind)return true;return false;}
void readback(const BuiltModel& built,const fs::path& path){built.export_file(path,"step");STEPControl_Reader reader;require(reader.ReadFile(path_to_utf8(path).c_str())==IFSelect_RetDone,"Independent STEP reads");require(reader.TransferRoots()>0,"STEP roots transfer");const auto shape=reader.OneShape();require(BRepCheck_Analyzer(shape).IsValid(),"Exact STEP readback is valid");GProp_GProps p;BRepGProp::VolumeProperties(shape,p);near(p.Mass(),built.summary().at("volume_mm3"),1e-4);}
std::string dxf(const std::string& entities,int units=4){return "0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n"+std::to_string(units)+"\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n"+entities+"0\nENDSEC\n0\nEOF\n";}
std::string circle(double radius){return "0\nCIRCLE\n10\n0\n20\n0\n40\n"+std::to_string(radius)+"\n";}
Json wait(Service& service,const std::string& id){for(int attempt=0;attempt<500;++attempt){Json result;try{result=service.call("cad_job",{{"action","get"},{"job_id",id}});}catch(const Error& e){if(e.code!="workspace_busy")throw;std::this_thread::sleep_for(std::chrono::milliseconds(20));continue;}const auto state=result.at("state");if(state=="succeeded")return result.at("result");if(state=="failed"||state=="cancelled"||state=="interrupted")throw std::runtime_error(result.dump());std::this_thread::sleep_for(std::chrono::milliseconds(20));}throw std::runtime_error("Job did not complete");}
void svg(const fs::path& root){
  const std::string ring="<svg xmlns='http://www.w3.org/2000/svg'><path fill-rule='evenodd' d='M10 0 A10 10 0 1 1 -10 0 A10 10 0 1 1 10 0 Z M4 0 A4 4 0 1 1 -4 0 A4 4 0 1 1 4 0 Z'/></svg>";
  auto document=profile_model(imported("svg",ring));BuiltModel built(document);near(built.summary().at("volume_mm3"),252*std::numbers::pi);require(curved(built,"bezier"),"SVG arcs remain exact rational curves");readback(built,root/"svg-ring.step");near(BuiltModel(document,built.snapshot()).summary().at("volume_mm3"),252*std::numbers::pi);
  document["parameters"]["magnification"]=2;document["features"][0]["profile"]["scale"]={{"parameter","magnification"}};near(BuiltModel(document).summary().at("volume_mm3"),1008*std::numbers::pi);
  document["features"][0]["workplane"]=plane({1,2,3},{0,1,0},{1,0,0});const auto turned=BuiltModel(document).summary();near(turned.at("bounds_mm")["min"][1],2);near(turned.at("bounds_mm")["max"][1],5);
  const std::string nested="<svg><path d='M0 0 L10 0 L10 10 L0 10 Z M2 2 L4 2 L4 4 L2 4 Z'/></svg>";near(BuiltModel(profile_model(imported("svg",nested))).summary().at("volume_mm3"),300);
  auto reversed=nested;reversed.replace(reversed.find("M2 2 L4 2 L4 4 L2 4 Z"),21,"M2 2 L2 4 L4 4 L4 2 Z");near(BuiltModel(profile_model(imported("svg",reversed))).summary().at("volume_mm3"),288);
  const std::string independent="<svg><rect width='10' height='10'/><rect x='2' y='2' width='2' height='2'/></svg>";near(BuiltModel(profile_model(imported("svg",independent))).summary().at("volume_mm3"),300);
  const std::string viewport="<svg width='20mm' height='10mm' viewBox='0 0 2 1'><g transform='translate(0.25 0) scale(0.5)'><rect width='2' height='1'/></g></svg>";const auto view=BuiltModel(profile_model(imported("svg",viewport))).summary();near(view.at("volume_mm3"),150);near(view.at("bounds_mm")["min"][0],2.5);near(view.at("bounds_mm")["max"][0],12.5);
  const std::string cubic="<svg><path d='M0 0 C0 10 20 10 20 0 Z'/></svg>";near(BuiltModel(profile_model(imported("svg",cubic))).summary().at("volume_mm3"),360);
  const std::string ellipse="<svg><g transform='matrix(1 0.2 0.3 1 0 0)'><ellipse rx='10' ry='5'/></g></svg>";near(BuiltModel(profile_model(imported("svg",ellipse))).summary().at("volume_mm3"),141*std::numbers::pi,2e-4);
  const std::string adjacent_flags="<svg><path d='M10 0 A10 10 0 11-10 0 A10 10 0 1110 0 Z'/></svg>";near(BuiltModel(profile_model(imported("svg",adjacent_flags))).summary().at("volume_mm3"),300*std::numbers::pi);
  const std::string smooth="<svg><path d='M0 0 q5 10 10 0 t10 0 l0 -10 h-20 z'/></svg>";require(BuiltModel(profile_model(imported("svg",smooth))).summary().at("volume_mm3").get<double>()>0,"Relative smooth quadratic path closes exactly");
  const std::string rounded="<svg><rect width='20' height='10' rx='2' ry='2'/></svg>";near(BuiltModel(profile_model(imported("svg",rounded))).summary().at("volume_mm3"),3*(200-16+4*std::numbers::pi));
  for(const std::string source:{"<svg><script>bad</script></svg>","<svg><use href='#part'/></svg>","<svg><text>Label</text></svg>","<svg><rect width='1' height='1' stroke='black'/></svg>","<!DOCTYPE svg><svg><circle r='1'/></svg>"})fails("unsupported_format",[&]{BuiltModel rejected(profile_model(imported("svg",source)));});
  for(const std::string paint:{" none ","\tNoNe\n"," URL(#paint) ","uRl(#paint) red","vAr(--paint)","context-fill","CONTEXT-STROKE",R"(\6e one)",R"(\75rl(#paint))"}){
    for(const std::string source:{"<svg><rect width='2' height='3' fill='"+paint+"'/></svg>","<svg><g fill='"+paint+"'><rect width='2' height='3'/></g></svg>"})
      fails("unsupported_format",[&]{BuiltModel rejected(profile_model(imported("svg",source)));});
  }
  const std::string normalized_stroke="<svg><rect width='2' height='3' fill=' ReD ' stroke=' NoNe '/></svg>";
  near(BuiltModel(profile_model(imported("svg",normalized_stroke))).summary().at("volume_mm3"),18);
  Service paint_service(root/"paint_workspace");const auto paint_path=root/"paint.svg";write(paint_path,normalized_stroke);
  const auto paint_capture=paint_service.call("cad_capture_sketch",{{"format","svg"},{"path",path_to_utf8(paint_path)},{"feature_id","paint"},{"workplane",plane()}});
  require(paint_capture.at("feature").at("profile").at("content")==normalized_stroke&&paint_capture.at("source_sha256")==sha256(normalized_stroke),"Paint interpretation never normalizes captured bytes or identity");
  const std::string declared="<?xml version='1.0' encoding='uTf-8' standalone='yes'?><svg xmlns='http://www.w3.org/2000/svg'><!--<!DOCTYPE inside a comment>--><title>Plain text</title><desc><![CDATA[plain description]]></desc><rect width='2' height='3'/></svg>";
  near(BuiltModel(profile_model(imported("svg",declared))).summary().at("volume_mm3"),18);
  for(const std::string source:{"<?xml-stylesheet type='text/css' href='https://example.invalid/hidden.css'?><svg><rect width='2' height='3'/></svg>","<?custom action='hide'?><svg><rect width='2' height='3'/></svg>","<!FOO><svg><rect width='2' height='3'/></svg>","<svg xmlns='https://example.invalid/other'><rect width='2' height='3'/></svg>","<svg xmlns=''><rect width='2' height='3'/></svg>","<?xml version='1.0' encoding='UTF-16'?><svg><rect width='2' height='3'/></svg>","<?xml version='1.0' custom='ignored'?><svg><rect width='2' height='3'/></svg>","<?xml version='1.0'?><?xml version='1.0'?><svg><rect width='2' height='3'/></svg>","<svg>unexpected text<rect width='2' height='3'/></svg>"})
    fails("unsupported_format",[&]{BuiltModel rejected(profile_model(imported("svg",source)));});
  write(paint_path,declared);const auto declared_capture=paint_service.call("cad_capture_sketch",{{"format","svg"},{"path",path_to_utf8(paint_path)},{"feature_id","declaration"},{"workplane",plane()}});
  require(declared_capture.at("feature").at("profile").at("content")==declared&&declared_capture.at("source_sha256")==sha256(declared),"Standard XML declaration and namespace retain immutable raw bytes");
  fails("invalid_shape",[&]{BuiltModel rejected(profile_model(imported("svg","<svg><path d='M0 0 L10 0 L0 10'/></svg>")));});
  fails("invalid_shape",[&]{BuiltModel rejected(profile_model(imported("svg","<svg><path d='M0 0 L10 10 L0 10 L10 0 Z'/></svg>")));});
}
void dxf_profiles(const fs::path& root){auto document=profile_model(imported("dxf",dxf(circle(10)+circle(4))));BuiltModel ring(document);near(ring.summary().at("volume_mm3"),252*std::numbers::pi);readback(ring,root/"dxf-ring.step");
  const std::string bulge="0\nLWPOLYLINE\n90\n2\n70\n1\n10\n-5\n20\n0\n42\n1\n10\n5\n20\n0\n42\n1\n";near(BuiltModel(profile_model(imported("dxf",dxf(bulge)))).summary().at("volume_mm3"),75*std::numbers::pi);
  const std::string old="0\nPOLYLINE\n66\n1\n70\n1\n0\nVERTEX\n10\n0\n20\n0\n0\nVERTEX\n10\n5\n20\n0\n0\nVERTEX\n10\n0\n20\n5\n0\nSEQEND\n";near(BuiltModel(profile_model(imported("dxf",dxf(old)))).summary().at("volume_mm3"),37.5);
  const std::string elliptical="0\nELLIPSE\n10\n0\n20\n0\n11\n10\n21\n0\n40\n0.5\n41\n0\n42\n6.283185307179586\n";near(BuiltModel(profile_model(imported("dxf",dxf(elliptical)))).summary().at("volume_mm3"),150*std::numbers::pi);
  const std::string spline="0\nSPLINE\n70\n8\n71\n3\n72\n8\n73\n4\n74\n0\n40\n0\n40\n0\n40\n0\n40\n0\n40\n1\n40\n1\n40\n1\n40\n1\n10\n0\n20\n0\n10\n0\n20\n10\n10\n20\n20\n10\n10\n20\n20\n0\n0\nLINE\n10\n20\n20\n0\n11\n0\n21\n0\n";BuiltModel curve(profile_model(imported("dxf",dxf(spline))));near(curve.summary().at("volume_mm3"),360);require(curved(curve,"bspline"),"DXF control-point spline remains exact");readback(curve,root/"dxf-spline.step");
  const std::string semi="0\nARC\n10\n0\n20\n0\n40\n5\n50\n0\n51\n180\n0\nLINE\n10\n-5\n20\n0\n11\n5\n21\n0\n";near(BuiltModel(profile_model(imported("dxf",dxf(semi)))).summary().at("volume_mm3"),37.5*std::numbers::pi);
  fails("invalid_argument",[&]{BuiltModel rejected(profile_model(imported("dxf",dxf(circle(-5)))));});
  fails("invalid_argument",[&]{BuiltModel rejected(profile_model(imported("dxf",dxf("0\nARC\n40\n5\n50\n0\n51\n0\n"))));});
  near(BuiltModel(profile_model(imported("dxf",dxf(circle(1),1)))).summary().at("volume_mm3"),3*std::numbers::pi*25.4*25.4,2e-4);
  fails("unsupported_format",[&]{BuiltModel rejected(profile_model(imported("dxf",dxf("0\nINSERT\n2\nblock\n"))));});
  fails("unsupported_format",[&]{BuiltModel rejected(profile_model(imported("dxf",dxf("0\nCIRCLE\n10\n0\n20\n0\n30\n1\n40\n5\n"))));});
  fails("invalid_shape",[&]{BuiltModel rejected(profile_model(imported("dxf",dxf("0\nLINE\n10\n0\n20\n0\n11\n1\n21\n0\n"))));});
}
void text(const fs::path& root){const auto bytes=read_text(fs::path(CAD_SOURCE_DIR)/"tests"/"fixtures"/"authoring-test.ttf",authoring_font_bytes);const Json font={{"content_base64",encode_font_bytes(bytes)},{"sha256",sha256(bytes)}};auto doc=profile_model({{"type","text"},{"text","B"},{"height",20},{"font",font}});BuiltModel b(doc);near(b.summary().at("volume_mm3"),312);near(b.summary("profile").at("area_mm2"),104);require(b.summary("profile").at("face_count")==1,"B retains one face with two interior contours");readback(b,root/"text-B.step");
  doc["features"][0]["profile"]["text"]="BO";BuiltModel label(doc);require(label.summary().at("solid_count")==2,"Separate glyph solids are retained");require(curved(label,"bezier"),"TrueType quadratic outlines remain exact Bezier curves");near(BuiltModel(doc,label.snapshot()).summary().at("volume_mm3"),label.summary().at("volume_mm3"));
  doc["parameters"]["letter_height"]=10;doc["features"][0]["profile"]["height"]={{"parameter","letter_height"}};near(BuiltModel(doc).summary().at("volume_mm3"),label.summary().at("volume_mm3").get<double>()/4);
  doc["features"][0]["profile"]["text"]="\xC3\xA9";near(BuiltModel(doc).summary().at("volume_mm3"),78);
  doc["features"].insert(doc["features"].begin(),Json{{"id","stock"},{"type","box"},{"origin",{-1,-1,0}},{"size",{10,10,3}}});doc["features"].push_back({{"id","engraved"},{"type","cut"},{"left","stock"},{"right","part"}});doc["output"]="engraved";near(BuiltModel(doc).summary().at("volume_mm3"),222);
  auto bad=doc;bad["features"][1]["profile"]["text"]="missing";fails("unsupported_format",[&]{BuiltModel rejected(bad);});bad=doc;bad["features"][1]["profile"]["font"]["sha256"]=std::string(64,'0');fails("artifact_mismatch",[&]{BuiltModel rejected(bad);});bad=doc;bad["features"][1]["profile"]["text"]=" ";fails("invalid_shape",[&]{BuiltModel rejected(bad);});
  doc=profile_model({{"type","text"},{"text","O"},{"height",20},{"font",font}});const auto o=BuiltModel(doc).summary("profile");require(o.at("face_count")==1,"Curved O has one filled region with its interior retained");near(o.at("area_mm2"),220.0/3);
  require(decode_font_bytes(encode_font_bytes(bytes))==bytes,"Font capture is byte-exact");fails("invalid_argument",[&]{decode_font_bytes("Zh==");});
}
void persistence(const fs::path& root){Service service(root/"workspace");const auto path=root/"source.svg";const std::string source="<svg><path fill-rule='evenodd' d='M0 0 H10 V10 H0 Z M2 2 H4 V4 H2 Z'/></svg>";write(path,source);const Json args={{"format","svg"},{"path",path_to_utf8(path)},{"feature_id","profile"},{"workplane",plane()},{"expected_sha256",sha256(source)}};const auto captured=service.call("cad_capture_sketch",args);require(captured.at("contour_count")==2,"Capture validates and counts source contours");require(captured.at("feature")["profile"]["content"]==source,"Capture preserves raw SVG bytes");auto doc=profile_model(captured.at("feature")["profile"]);auto created=service.call("cad_create",{{"document_id","svg"},{"model",doc}});near(created.at("summary")["volume_mm3"],288);fs::remove(path);fs::remove_all(root/"workspace"/".cache");Service reopened(root/"workspace");near(reopened.call("cad_query",{{"document_id","svg"},{"revision",1}}).at("summary")["volume_mm3"],288);
  auto feature=captured.at("feature");feature["profile"]["scale"]=2;auto edited=reopened.call("cad_apply",{{"document_id","svg"},{"expected_revision",1},{"operations",Json::array({{{"op","replace_feature"},{"id","profile"},{"feature",feature}}})}});near(edited.at("summary")["volume_mm3"],1152);feature["profile"]["sha256"]=std::string(64,'0');fails("artifact_mismatch",[&]{reopened.call("cad_apply",{{"document_id","svg"},{"expected_revision",2},{"operations",Json::array({{{"op","replace_feature"},{"id","profile"},{"feature",feature}}})}});});require(reopened.call("cad_read",{{"document_id","svg"}}).at("revision")==2,"Integrity failure preserves HEAD");
  write(path,source);service.call("cad_job",{{"action","submit"},{"request_id","capture_svg"},{"tool","cad_capture_sketch"},{"arguments",args}});const auto asynchronous=wait(service,"capture_svg");require(asynchronous==captured,"Durable capture job returns same exact feature");fs::remove(path);require(wait(service,"capture_svg")==captured,"Capture job replay survives source deletion");
  // A captured source larger than the metadata budget stays portable through
  // persistence, worker inputs and component materialization, with raw bytes intact.
  const auto padded=std::string("<svg><!--")+std::string(1100000,'x')+"--><rect width='2' height='3'/></svg>";auto large=profile_model(imported("svg",padded));validate_payload_size(large);require(parse_payload_json(large.dump())==large,"Source bytes are charged separately from metadata");service.call("cad_create",{{"document_id","large"},{"model",large}});auto consumer=model(Json::array({{{"id","base"},{"type","box"},{"size",{1,1,1}}}}),"base");service.call("cad_create",{{"document_id","consumer"},{"model",consumer}});auto component=service.call("cad_apply",{{"document_id","consumer"},{"expected_revision",1},{"operations",Json::array({{{"op","set_component"},{"id","captured"},{"source_document_id","large"},{"source_revision",1},{"source_feature_id","part"}},{{"op","set_output"},{"feature_id","captured"}}})}});near(component.at("summary")["volume_mm3"],18);fs::remove_all(root/"workspace"/"documents"/"large");fs::remove_all(root/"workspace"/".cache");near(Service(root/"workspace").call("cad_query",{{"document_id","consumer"},{"revision",2}}).at("summary")["volume_mm3"],18);
  const auto font_path=root/"font.ttf";write(font_path,read_text(fs::path(CAD_SOURCE_DIR)/"tests"/"fixtures"/"authoring-test.ttf",authoring_font_bytes));const auto font_capture=service.call("cad_capture_sketch",{{"format","text"},{"path",path_to_utf8(font_path)},{"feature_id","profile"},{"workplane",plane()},{"text","B"},{"height",20}});fs::remove(font_path);auto text_doc=profile_model(font_capture.at("feature")["profile"]);service.call("cad_create",{{"document_id","text"},{"model",text_doc}});fs::remove_all(root/"workspace"/".cache");near(Service(root/"workspace").call("cad_query",{{"document_id","text"},{"revision",1}}).at("summary")["volume_mm3"],312);auto new_text=font_capture.at("feature");new_text["profile"]["text"]="BB";near(service.call("cad_apply",{{"document_id","text"},{"expected_revision",1},{"operations",Json::array({{{"op","replace_feature"},{"id","profile"},{"feature",new_text}}})}}).at("summary")["volume_mm3"],624);
  const auto oversized=std::string(authoring_source_bytes+1,'x');auto oversized_model=profile_model(imported("svg",oversized));fails("limit_exceeded",[&]{validate_model(oversized_model);});auto oversized_font=std::string(authoring_font_bytes+1,'x');fails("limit_exceeded",[&]{encode_font_bytes(oversized_font);});auto invalid_source=profile_model(imported("svg",std::string("<svg>")+std::string(1,'\0')+"</svg>"));fails("invalid_model",[&]{validate_model(invalid_source);});
  // Large captures are appended by path, never sent back in an MCP request.
  auto stock=model(Json::array({{{"id","stock"},{"type","box"},{"size",{20,20,10}}}}),"stock");stock["parameters"]["letter_height"]=20;service.call("cad_create",{{"document_id","direct"},{"model",stock}});write(path,padded);
  Json import_args={{"document_id","direct"},{"expected_revision",1},{"format","svg"},{"path",path_to_utf8(path)},{"feature_id","artwork"},{"workplane",plane()},{"expected_sha256",sha256(padded)},{"request_id","import_artwork"}};const auto direct=service.call("cad_import_sketch",import_args);require(!direct.contains("model")&&direct.dump().size()<2048,"Atomic sketch import returns compact identity without source bytes");require(direct.at("revision")==2&&direct.at("source_sha256")==sha256(padded),"Imported sketch reports committed raw source identity");fs::remove(path);require(service.call("cad_import_sketch",import_args)==direct,"Committed capture retries do not read deleted source paths");
  auto invalid=import_args;invalid.erase("request_id");invalid["expected_revision"]=2;invalid["feature_id"]="invalid";invalid["unexpected"]=true;fails("invalid_argument",[&]{service.call("cad_import_sketch",invalid);});invalid.erase("unexpected");fails("not_found",[&]{service.call("cad_import_sketch",invalid);});write(path,padded);invalid["expected_sha256"]=std::string(64,'0');fails("artifact_mismatch",[&]{service.call("cad_import_sketch",invalid);});invalid["expected_sha256"]=sha256(padded);invalid["expected_revision"]=1;fails("revision_conflict",[&]{service.call("cad_import_sketch",invalid);});invalid["expected_revision"]=2;invalid["workplane"]["normal"]={0,0,0};fails("invalid_model",[&]{service.call("cad_import_sketch",invalid);});invalid["workplane"]=plane();const auto open="<svg><path d='M0 0 L1 0 L0 1'/></svg>";write(path,open);invalid["expected_sha256"]=sha256(open);fails("invalid_shape",[&]{service.call("cad_import_sketch",invalid);});require(service.call("cad_read",{{"document_id","direct"}}).at("revision")==2,"Unknown/source/geometry/revision failures publish no import");
  write(path,"<svg><rect width='2' height='3'/></svg>");invalid.erase("expected_sha256");const auto race=[&](const char* name){auto input=invalid;input["feature_id"]=name;try{return service.call("cad_import_sketch",input).at("revision")==3?std::string("success"):std::string("unexpected");}catch(const Error& e){return e.code;}};auto a=std::async(std::launch::async,race,"race_a"),b=std::async(std::launch::async,race,"race_b");const auto first=a.get(),second=b.get();require((first=="success"&&second=="revision_conflict")||(second=="success"&&first=="revision_conflict"),"Concurrent imports against the same revision publish exactly one candidate");require(service.call("cad_read",{{"document_id","direct"}}).at("revision")==3,"Concurrent import publication preserves one revision transition");
  write(font_path,read_text(fs::path(CAD_SOURCE_DIR)/"tests"/"fixtures"/"authoring-test.ttf",authoring_font_bytes));Json text_args={{"document_id","direct"},{"expected_revision",3},{"format","text"},{"path",path_to_utf8(font_path)},{"feature_id","letters"},{"workplane",plane()},{"text","B"},{"height",{{"parameter","letter_height"}}}};service.call("cad_job",{{"action","submit"},{"request_id","import_text_job"},{"tool","cad_import_sketch"},{"arguments",text_args}});const auto text_import=wait(service,"import_text_job");require(!text_import.contains("model")&&text_import.at("feature_id")=="letters","Native import job returns compact committed source identity");fs::remove(font_path);Service job_reopened(root/"workspace");require(wait(job_reopened,"import_text_job")==text_import,"Durable imported text job replays without original font");
  service.call("cad_apply",{{"document_id","direct"},{"expected_revision",4},{"operations",Json::array({{{"op","add_feature"},{"feature",{{"id","letter_solid"},{"type","extrude"},{"input","letters"},{"distance",3}}}},{{"op","set_output"},{"feature_id","letter_solid"}}})}});fs::remove_all(root/"workspace"/".cache");near(Service(root/"workspace").call("cad_query",{{"document_id","direct"},{"revision",5}}).at("summary")["volume_mm3"],312);

}
}
int main(){try{set_worker_executable(CAD_SERVICE_EXE);Temp temp;svg(temp.path);dxf_profiles(temp.path);text(temp.path);persistence(temp.path);std::cout<<"Authoring: "<<checks<<" checks passed\n";return 0;}catch(const Error& e){std::cerr<<e.json().dump()<<'\n';return 1;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
