cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED BUILD_DIR OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "BUILD_DIR and TEST_DIR are required")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
get_filename_component(TEST_DIR "${TEST_DIR}" ABSOLUTE)
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config Release --prefix staging
  WORKING_DIRECTORY "${TEST_DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE installed ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Bundle install failed: ${installed}\n${diagnostics}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUNDLE_DIR=${TEST_DIR}/staging"
  "-DINSTALL_DIR=${TEST_DIR}/relocated bundles" "-DRESULT_FILE=${TEST_DIR}/install-result.json"
  -P "${CMAKE_CURRENT_LIST_DIR}/../packaging/install-local.cmake"
  RESULT_VARIABLE status OUTPUT_VARIABLE installed ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Verified local installation failed: ${installed}\n${diagnostics}")
endif()
file(READ "${TEST_DIR}/install-result.json" installation)
string(JSON bundle GET "${installation}" install_dir)
if(WIN32)
  set(suffix .exe)
endif()
set(CAD_EXE "${bundle}/bin/agent-3d-cad${suffix}")
set(SOURCE_DIR "${bundle}/share/agent-3d-cad")
if(NOT EXISTS "${SOURCE_DIR}/skills/native-cad/SKILL.md")
  message(FATAL_ERROR "Bundle is missing its native CAD workflow skill")
endif()
file(READ "${SOURCE_DIR}/provenance.json" provenance)
string(JSON hlr_patch GET "${provenance}" occt_modifications 0)
if(NOT hlr_patch STREQUAL "agentcad-hlr-midpoint-v2")
  message(FATAL_ERROR "Bundle must identify its reproducible OCCT midpoint optimization")
endif()
file(READ "${SOURCE_DIR}/notices/occt/agentcad-hlr-midpoint-v2.json" hlr_metadata)
string(JSON hlr_metadata_patch GET "${hlr_metadata}" modification)
string(JSON hlr_metadata_version GET "${hlr_metadata}" occt_version)
string(JSON hlr_metadata_format GET "${hlr_metadata}" format_version)
string(JSON hlr_sdk_hash GET "${provenance}" occt_hlr_sdk_sha256)
string(JSON hlr_binary_count LENGTH "${hlr_metadata}" binaries)
if(NOT hlr_metadata_patch STREQUAL hlr_patch OR NOT hlr_metadata_version STREQUAL "8.0.1"
    OR NOT hlr_metadata_format EQUAL 1 OR hlr_binary_count LESS 1)
  message(FATAL_ERROR "Bundle OCCT modification metadata is inconsistent")
endif()
set(hlr_sdk_recorded FALSE)
math(EXPR hlr_binary_last "${hlr_binary_count}-1")
foreach(index RANGE 0 ${hlr_binary_last})
  string(JSON recorded_hash GET "${hlr_metadata}" binaries ${index} sha256)
  if(recorded_hash STREQUAL hlr_sdk_hash)
    set(hlr_sdk_recorded TRUE)
  endif()
endforeach()
if(NOT hlr_sdk_recorded)
  message(FATAL_ERROR "Bundle provenance does not identify a binary from its patched SDK manifest")
endif()
foreach(source HLRBRep_Intersector.cxx HLRBRep_Intersector.hxx HLRBRep_Data.cxx HLRBRep_Data.hxx HLRBRep_Hider.cxx)
  if(NOT EXISTS "${SOURCE_DIR}/notices/occt/modified/${source}")
    message(FATAL_ERROR "Bundle is missing modified OCCT source: ${source}")
  endif()
endforeach()
if(NOT EXISTS "${SOURCE_DIR}/ARTIFACT_REVIEW.md")
  message(FATAL_ERROR "Bundle omitted external-artifact review guidance")
endif()
file(READ "${SOURCE_DIR}/notices/tinyxml2/PROVENANCE.json" artifact_dependencies)
string(JSON tinyxml2_version GET "${provenance}" tinyxml2_version)
string(JSON tinyxml2_archive GET "${provenance}" tinyxml2_archive_sha256)
string(JSON tinyxml2_linkage GET "${provenance}" tinyxml2_linkage)
if(NOT tinyxml2_version STREQUAL "11.0.0" OR NOT tinyxml2_archive STREQUAL "5556deb5081fb246ee92afae73efd943c889cef0cafea92b0b82422d6a18f289"
    OR NOT tinyxml2_linkage STREQUAL "statically compiled into cad_core")
  message(FATAL_ERROR "Bundle omitted pinned TinyXML2 provenance")
endif()
foreach(source tinyxml2.cpp tinyxml2.h LICENSE.txt readme.md)
  string(JSON expected_hash GET "${artifact_dependencies}" tinyxml2 files "${source}")
  string(JSON recorded_hash GET "${provenance}" tinyxml2_sources_sha256 "${source}")
  file(SHA256 "${SOURCE_DIR}/notices/tinyxml2/${source}" actual_hash)
  if(NOT actual_hash STREQUAL expected_hash OR NOT actual_hash STREQUAL recorded_hash)
    message(FATAL_ERROR "Bundled TinyXML2 source/notice differs from pin: ${source}")
  endif()
endforeach()
set(TEST_DIR "${TEST_DIR}/workflow")
# Absolute service paths and direct worker spawn must work without SDK tooling
# on PATH or loader environment overrides. Windows retains SystemRoot for APIs.
set(ENV{PATH} "")
foreach(variable LD_LIBRARY_PATH DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH CASROOT CSF_SHMessage CSF_XSMessage CSF_STEPDefaults CSF_IGESDefaults CSF_StandardDefaults CSF_PluginDefaults CSF_XCAFDefaults)
  unset(ENV{${variable}})
endforeach()
execute_process(COMMAND "${CAD_EXE}" --version RESULT_VARIABLE status OUTPUT_VARIABLE version ERROR_VARIABLE logs)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Relocated bundle cannot start: ${logs}")
endif()
string(JSON kernel GET "${version}" kernel_version)
if(NOT kernel STREQUAL "8.0.1")
  message(FATAL_ERROR "Unexpected bundled kernel: ${kernel}")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/cli_smoke.cmake")
call_tool(cad_drawing "${SOURCE_DIR}/examples/plate.drawing.json")
string(JSON drawing_manifest GET "${reply}" path)
string(JSON drawing_count LENGTH "${reply}" artifacts)
if(NOT EXISTS "${drawing_manifest}" OR NOT drawing_count EQUAL 6)
  message(FATAL_ERROR "Relocated native drawing did not publish PDF, SVG and four DXFs")
endif()
foreach(index RANGE 0 5)
  string(JSON drawing_file GET "${reply}" artifacts ${index} path)
  if(NOT EXISTS "${drawing_file}")
    message(FATAL_ERROR "Relocated drawing artifact missing: ${drawing_file}")
  endif()
endforeach()
call_tool(cad_drawing "${SOURCE_DIR}/examples/plate-section.drawing.json")
string(JSON section_layout GET "${reply}" layout)
string(JSON section_count LENGTH "${reply}" artifacts)
if(NOT section_layout STREQUAL "third_angle" OR NOT section_count EQUAL 6)
  message(FATAL_ERROR "Relocated section drawing did not preserve its standard layout and artifacts")
endif()
set(found_hatching FALSE)
foreach(index RANGE 0 5)
  string(JSON section_format GET "${reply}" artifacts ${index} format)
  if(section_format STREQUAL "svg")
    string(JSON section_file GET "${reply}" artifacts ${index} path)
    file(READ "${section_file}" section_svg)
    if(section_svg MATCHES "data-layer=\"HATCH\"")
      set(found_hatching TRUE)
    endif()
  endif()
endforeach()
if(NOT found_hatching)
  message(FATAL_ERROR "Relocated section drawing omitted requested material hatching")
endif()
call_tool(cad_create "${SOURCE_DIR}/examples/angular-plate.create.json")
call_tool(cad_drawing "${SOURCE_DIR}/examples/angular-plate.drawing.json")
string(JSON angle GET "${reply}" dimensions 0 value_deg)
string(JSON angle_lower GET "${reply}" dimensions 0 lower_limit_deg)
string(JSON angle_label GET "${reply}" dimensions 0 label)
string(JSON bore_lower GET "${reply}" dimensions 1 lower_limit_mm)
if(NOT angle EQUAL 45 OR NOT angle_lower EQUAL 44.75 OR
   NOT angle_label STREQUAL "45 +/-0.25 deg" OR NOT bore_lower EQUAL 7.98)
  message(FATAL_ERROR "Relocated drawing did not preserve angular dimensions and explicit tolerances")
endif()
file(GLOB cache_entries "${TEST_DIR}/workspace/.cache/*.json")
list(LENGTH cache_entries cache_count)
if(cache_count LESS 5)
  message(FATAL_ERROR "Relocated service did not cache exact geometry and projections")
endif()
set(cold_drawing "${reply}")
call_tool(cad_drawing "${SOURCE_DIR}/examples/angular-plate.drawing.json")
string(JSON artifact_count LENGTH "${reply}" artifacts)
math(EXPR last_artifact "${artifact_count}-1")
foreach(index RANGE 0 ${last_artifact})
  string(JSON cold_file GET "${cold_drawing}" artifacts ${index} path)
  string(JSON warm_file GET "${reply}" artifacts ${index} path)
  file(SHA256 "${cold_file}" cold_hash)
  file(SHA256 "${warm_file}" warm_hash)
  if(NOT cold_hash STREQUAL warm_hash)
    message(FATAL_ERROR "Cached relocated drawing changed artifact contents")
  endif()
endforeach()
call_tool(cad_create "${SOURCE_DIR}/examples/assembly.create.json")
string(JSON assembly_parts LENGTH "${reply}" summary assembly parts)
if(assembly_parts LESS 2)
  message(FATAL_ERROR "Relocated assembly omitted its editable part inventory")
endif()
string(JSON presented_document GET "${reply}" document_id)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" original_head_hash)
file(WRITE "${TEST_DIR}/presentation-open.json" "{\"document_id\":\"${presented_document}\",\"view_id\":\"bundle_presentation\"}")
call_tool(cad_open "${TEST_DIR}/presentation-open.json")
file(WRITE "${TEST_DIR}/presentation-sync.json" [=[{"action":"sync","view_id":"bundle_presentation"}]=])
foreach(attempt RANGE 0 199)
  call_tool(cad_viewer "${TEST_DIR}/presentation-sync.json")
  string(JSON presented_state GET "${reply}" state)
  if(presented_state STREQUAL "ready")
    break()
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
endforeach()
if(NOT presented_state STREQUAL "ready")
  message(FATAL_ERROR "Relocated live presentation did not become ready")
endif()
string(JSON presented_evaluation GET "${reply}" evaluation_id)
set(presentation_settings [=[{"clip":{"normal":[0,0,1],"offset_mm":3,"keep":"negative"},"explode":{"distance_mm":20,"directions":[]}}]=])
file(WRITE "${TEST_DIR}/presentation-save.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"selection\":null,\"presentation\":${presentation_settings}}")
call_tool(cad_viewer "${TEST_DIR}/presentation-save.json")
string(JSON expected_presentation GET "${reply}" presentation)
file(WRITE "${TEST_DIR}/presentation-read.json" [=[{"view_id":"bundle_presentation"}]=])
call_tool(cad_context "${TEST_DIR}/presentation-read.json")
string(JSON saved_presentation GET "${reply}" presentation)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" presented_head_hash)
if(NOT saved_presentation STREQUAL expected_presentation OR NOT original_head_hash STREQUAL presented_head_hash)
  message(FATAL_ERROR "Relocated presentation changed source HEAD or failed persistence across native processes")
endif()
# Annotations are persisted native review metadata, usable with an empty PATH.
file(WRITE "${TEST_DIR}/annotation-add.json" "{\"action\":\"annotation\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"operation\":\"add\",\"anchor\":{\"kind\":\"part\",\"part_id\":\"spacer_a\"},\"text\":\"Inspect source leaf clearance\"}")
call_tool(cad_viewer "${TEST_DIR}/annotation-add.json")
string(JSON annotation_id GET "${reply}" annotations 0 id)
string(JSON annotation_owner GET "${reply}" annotations 0 anchor part_id)
string(JSON annotation_status GET "${reply}" annotations 0 status)
string(JSON annotation_lifetime GET "${reply}" annotations 0 anchor_lifetime)
call_tool(cad_context "${TEST_DIR}/presentation-read.json")
string(JSON persisted_annotation GET "${reply}" annotations 0 id)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" annotation_head_hash)
if(NOT annotation_id STREQUAL persisted_annotation OR NOT annotation_owner STREQUAL "spacer_a" OR NOT annotation_status STREQUAL "current" OR NOT annotation_lifetime STREQUAL "evaluation" OR NOT original_head_hash STREQUAL annotation_head_hash)
  message(FATAL_ERROR "Relocated review note lost native source lifetime/ownership/persistence or changed HEAD")
endif()
file(WRITE "${TEST_DIR}/measurement.json" "{\"document_id\":\"${presented_document}\",\"revision\":1,\"evaluation_id\":\"${presented_evaluation}\",\"feature_id\":\"assembly\",\"query\":{\"action\":\"pair\",\"targets\":[{\"kind\":\"part\",\"part_id\":\"spacer_a\"},{\"kind\":\"part\",\"part_id\":\"spacer_b\"}],\"minimum_clearance_mm\":1}}")
call_tool(cad_measure "${TEST_DIR}/measurement.json")
string(JSON measured_distance GET "${reply}" report minimum_distance_mm)
string(JSON measured_status GET "${reply}" report status)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" measured_head_hash)
if(measured_distance LESS 31.231 OR measured_distance GREATER 31.232 OR NOT measured_status STREQUAL "pass" OR NOT original_head_hash STREQUAL measured_head_hash)
  message(FATAL_ERROR "Relocated exact measurement differs from analytic cylinder gap or changed source HEAD")
endif()
if(NOT EXISTS "${SOURCE_DIR}/SECTIONS.md")
  message(FATAL_ERROR "Relocated bundle omitted exact native section guidance")
endif()
file(WRITE "${TEST_DIR}/section.json" "{\"document_id\":\"${presented_document}\",\"revision\":1,\"evaluation_id\":\"${presented_evaluation}\",\"feature_id\":\"assembly\",\"query\":{\"action\":\"section\",\"plane\":{\"normal\":[0,0,1],\"offset_mm\":8}}}")
call_tool(cad_measure "${TEST_DIR}/section.json")
string(JSON section_area GET "${reply}" report area_mm2)
string(JSON section_regions LENGTH "${reply}" report regions)
string(JSON section_wires_a GET "${reply}" report regions 0 wire_count)
string(JSON section_wires_b GET "${reply}" report regions 1 wire_count)
string(JSON section_triangles LENGTH "${reply}" report mesh triangles)
string(JSON section_plane_z GET "${reply}" report mesh positions 0 2)
if(section_area LESS 117.8097 OR section_area GREATER 117.8098 OR NOT section_regions EQUAL 2 OR NOT section_wires_a EQUAL 2 OR NOT section_wires_b EQUAL 2 OR section_triangles LESS 1 OR NOT section_plane_z EQUAL 8)
  message(FATAL_ERROR "Relocated native section lost analytic annular areas, actual holes or cap-plane coordinates")
endif()
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" section_head_hash)
if(NOT original_head_hash STREQUAL section_head_hash)
  message(FATAL_ERROR "Relocated native section modified raw saved source")
endif()
# Exercise the independent live slot through fresh native processes. Core CAD
# and section jobs must work with no developer runtimes or tools on PATH.
set(section_presentation [=[{"clip":{"normal":[0,0,1],"offset_mm":8,"keep":"negative"},"explode":{"distance_mm":0,"directions":[]}}]=])
file(WRITE "${TEST_DIR}/section-context.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"selection\":null,\"presentation\":${section_presentation}}")
call_tool(cad_viewer "${TEST_DIR}/section-context.json")
file(WRITE "${TEST_DIR}/section-start.json" "{\"action\":\"section\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"query\":{\"action\":\"section\",\"plane\":{\"normal\":[0,0,1],\"offset_mm\":8}}}")
  call_tool(cad_viewer "${TEST_DIR}/section-start.json")
  string(JSON live_section_job GET "${reply}" job_id)
  file(WRITE "${TEST_DIR}/section-poll.json" "{\"action\":\"section\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\"}")
  # Publication briefly owns the workspace. Retry only this read-only poll,
  # only for its explicit busy result; never repeat a section admission.
  function(poll_section)
    foreach(read_attempt RANGE 0 199)
      execute_process(COMMAND "${CAD_EXE}" call cad_viewer --workspace "${TEST_DIR}/workspace" --input "${TEST_DIR}/section-poll.json"
        RESULT_VARIABLE read_status OUTPUT_VARIABLE read_output ERROR_VARIABLE read_logs TIMEOUT 30)
      if(read_status EQUAL 0)
        set(reply "${read_output}" PARENT_SCOPE)
        return()
      endif()
      string(JSON read_error ERROR_VARIABLE invalid_error GET "${read_logs}" error code)
      if(invalid_error OR NOT read_error STREQUAL "workspace_busy")
        message(FATAL_ERROR "Relocated section poll failed: ${read_logs}")
      endif()
      execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
    endforeach()
    message(FATAL_ERROR "Relocated section poll remained busy: ${read_logs}")
  endfunction()
  foreach(attempt RANGE 0 199)
    poll_section()
  string(JSON live_section_state GET "${reply}" state)
  if(NOT live_section_state STREQUAL "queued" AND NOT live_section_state STREQUAL "running" AND NOT live_section_state STREQUAL "cancelling")
    break()
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
endforeach()
if(NOT live_section_state STREQUAL "succeeded")
  message(FATAL_ERROR "Relocated live native section did not succeed: ${reply}")
endif()
string(JSON live_section_area GET "${reply}" result report area_mm2)
string(JSON live_section_result_job GET "${reply}" job_id)
if(NOT live_section_result_job STREQUAL live_section_job OR live_section_area LESS 117.8097 OR live_section_area GREATER 117.8098)
  message(FATAL_ERROR "Relocated live section lost its saved native job or analytic result")
endif()
call_tool(cad_context "${TEST_DIR}/presentation-read.json")
string(JSON restored_section_job GET "${reply}" section job_id)
if(NOT restored_section_job STREQUAL live_section_job)
  message(FATAL_ERROR "Relocated section did not survive reopening across native processes")
endif()
string(REPLACE "negative" "positive" reversed_section_presentation "${section_presentation}")
file(WRITE "${TEST_DIR}/section-reverse.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"selection\":null,\"presentation\":${reversed_section_presentation}}")
call_tool(cad_viewer "${TEST_DIR}/section-reverse.json")
string(JSON reversed_section_job GET "${reply}" section job_id)
if(NOT reversed_section_job STREQUAL live_section_job)
  message(FATAL_ERROR "Kept-side reversal retired the unchanged native section")
endif()
string(REPLACE "\"offset_mm\":8" "\"offset_mm\":9" moved_section_presentation "${section_presentation}")
file(WRITE "${TEST_DIR}/section-move.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"selection\":null,\"presentation\":${moved_section_presentation}}")
call_tool(cad_viewer "${TEST_DIR}/section-move.json")
poll_section()
string(JSON retired_section_state GET "${reply}" state)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" live_section_head_hash)
if(NOT retired_section_state STREQUAL "empty" OR NOT original_head_hash STREQUAL live_section_head_hash)
  message(FATAL_ERROR "Moving the section failed to retire derived geometry or changed source HEAD")
endif()
if(NOT EXISTS "${SOURCE_DIR}/APPEARANCE.md")
  message(FATAL_ERROR "Relocated bundle omitted appearance and saved-view guidance")
endif()
set(bundle_colors [=[{"default_color":[0.2,0.5,0.7],"parts":[{"part_id":"spacer_a","color":[0.9,0.2,0.1]}]}]=])
file(WRITE "${TEST_DIR}/colors.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"selection\":null,\"appearance\":${bundle_colors}}")
call_tool(cad_viewer "${TEST_DIR}/colors.json")
file(WRITE "${TEST_DIR}/preset-save.json" "{\"action\":\"preset\",\"operation\":\"save\",\"name\":\"Colored section\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\"}")
call_tool(cad_viewer "${TEST_DIR}/preset-save.json")
string(JSON preset_count LENGTH "${reply}" presets)
if(NOT preset_count EQUAL 1)
  message(FATAL_ERROR "Relocated native preset did not persist exactly one view")
endif()
file(WRITE "${TEST_DIR}/colors-reset.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\",\"selection\":null,\"appearance\":{\"default_color\":[0.66,0.75,0.8],\"parts\":[]}}")
call_tool(cad_viewer "${TEST_DIR}/colors-reset.json")
file(WRITE "${TEST_DIR}/preset-apply.json" "{\"action\":\"preset\",\"operation\":\"apply\",\"name\":\"Colored section\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${presented_evaluation}\"}")
call_tool(cad_viewer "${TEST_DIR}/preset-apply.json")
string(JSON restored_color_owner GET "${reply}" appearance parts 0 part_id)
string(JSON restored_color_red GET "${reply}" appearance parts 0 color 0)
string(JSON restored_default_blue GET "${reply}" appearance default_color 2)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" colors_head_hash)
if(NOT restored_color_owner STREQUAL "spacer_a" OR NOT restored_color_red EQUAL 0.9 OR NOT restored_default_blue EQUAL 0.7 OR NOT original_head_hash STREQUAL colors_head_hash)
  message(FATAL_ERROR "Relocated native preset failed color restoration or changed source HEAD")
endif()
call_tool(cad_drawing "${SOURCE_DIR}/examples/assembly.drawing.json")
string(JSON assembly_artifacts LENGTH "${reply}" artifacts)
math(EXPR last_assembly_artifact "${assembly_artifacts}-1")
set(exploded_label FALSE)
foreach(index RANGE 0 ${last_assembly_artifact})
  string(JSON artifact_format GET "${reply}" artifacts ${index} format)
  if(artifact_format STREQUAL "svg")
    string(JSON artifact_file GET "${reply}" artifacts ${index} path)
    file(READ "${artifact_file}" assembly_svg)
    if(assembly_svg MATCHES "EXPLODED")
      set(exploded_label TRUE)
    endif()
  endif()
endforeach()
if(NOT exploded_label)
  message(FATAL_ERROR "Relocated exploded assembly drawing omitted its label")
endif()
# BOMs are generated from saved editable intent by the relocated service, with
# JSON/CSV usable independently of the application or developer tooling.
file(WRITE "${TEST_DIR}/bom.json" [=[{"document_id":"spacer_assembly","revision":1}]=])
call_tool(cad_bom "${TEST_DIR}/bom.json")
set(original_bom "${reply}")
string(JSON bom_quantity GET "${reply}" bom total_quantity)
string(JSON bom_items LENGTH "${reply}" bom items)
string(JSON plate_quantity GET "${reply}" bom items 0 quantity)
string(JSON spacer_quantity GET "${reply}" bom items 1 quantity)
string(JSON bom_files LENGTH "${reply}" artifacts)
if(NOT bom_quantity EQUAL 4 OR NOT bom_items EQUAL 2 OR NOT plate_quantity EQUAL 2 OR
   NOT spacer_quantity EQUAL 2 OR NOT bom_files EQUAL 2)
  message(FATAL_ERROR "Relocated BOM did not group repeated plate/spacer instances")
endif()
foreach(index RANGE 0 1)
  string(JSON artifact_file GET "${reply}" artifacts ${index} path)
  string(JSON artifact_bytes GET "${reply}" artifacts ${index} bytes)
  file(SIZE "${artifact_file}" actual_bytes)
  if(NOT actual_bytes EQUAL artifact_bytes OR actual_bytes LESS 1)
    message(FATAL_ERROR "Relocated BOM artifact does not match declared size")
  endif()
endforeach()
call_tool(cad_drawing "${SOURCE_DIR}/examples/assembly-bom.drawing.json")
string(JSON balloons LENGTH "${reply}" balloons)
string(JSON base_item GET "${reply}" balloons 0 item_number)
string(JSON spacer_item GET "${reply}" balloons 1 item_number)
string(JSON bom_artifacts LENGTH "${reply}" artifacts)
if(NOT balloons EQUAL 4 OR NOT base_item EQUAL 1 OR NOT spacer_item EQUAL 2 OR NOT bom_artifacts EQUAL 6)
  message(FATAL_ERROR "Relocated BOM drawing omitted source-matched balloons or sidecars")
endif()
set(found_bom_json FALSE)
set(found_bom_csv FALSE)
set(found_bom_table FALSE)
set(found_bom_balloons FALSE)
foreach(index RANGE 0 5)
  string(JSON artifact_format GET "${reply}" artifacts ${index} format)
  string(JSON artifact_file GET "${reply}" artifacts ${index} path)
  file(READ "${artifact_file}" artifact_content)
  if(artifact_format STREQUAL "json")
    string(JSON sidecar_quantity GET "${artifact_content}" bom total_quantity)
    string(JSON sidecar_revision GET "${artifact_content}" revision)
    if(NOT sidecar_quantity EQUAL 4 OR NOT sidecar_revision EQUAL 1)
      message(FATAL_ERROR "Relocated drawing BOM JSON lost its inventory or revision")
    endif()
    set(found_bom_json TRUE)
  elseif(artifact_format STREQUAL "csv")
    if(NOT artifact_content MATCHES "item_number" OR NOT artifact_content MATCHES "base;cover")
      message(FATAL_ERROR "Relocated drawing BOM CSV lost its grouped part identities")
    endif()
    set(found_bom_csv TRUE)
  elseif(artifact_format STREQUAL "svg")
    if(artifact_content MATCHES "BILL OF MATERIALS")
      set(found_bom_table TRUE)
    endif()
    if(artifact_content MATCHES "data-layer=\"BALLOONS\"")
      set(found_bom_balloons TRUE)
    endif()
  endif()
endforeach()
if(NOT found_bom_json OR NOT found_bom_csv OR NOT found_bom_table OR NOT found_bom_balloons)
  message(FATAL_ERROR "Relocated drawing omitted BOM sidecars, rendered table or numbered balloons")
endif()
file(WRITE "${TEST_DIR}/bom-edit.json" [=[{"document_id":"spacer_assembly","expected_revision":1,"operations":[{"op":"set_bom_item","assembly_id":"assembly","item":{"input":"plate","item_number":9,"description":"Plate, \"checked\""}}]}]=])
call_tool(cad_apply "${TEST_DIR}/bom-edit.json")
file(WRITE "${TEST_DIR}/bom-current.json" [=[{"document_id":"spacer_assembly","revision":2}]=])
call_tool(cad_bom "${TEST_DIR}/bom-current.json")
string(JSON edited_item GET "${reply}" bom items 1 item_number)
string(JSON edited_description GET "${reply}" bom items 1 description)
if(NOT edited_item EQUAL 9 OR NOT edited_description STREQUAL "Plate, \"checked\"")
  message(FATAL_ERROR "Relocated semantic BOM edit did not retain explicit metadata")
endif()
foreach(index RANGE 0 1)
  string(JSON artifact_format GET "${reply}" artifacts ${index} format)
  if(artifact_format STREQUAL "csv")
    string(JSON artifact_file GET "${reply}" artifacts ${index} path)
    file(READ "${artifact_file}" edited_csv)
    string(FIND "${edited_csv}" "\"Plate, \"\"checked\"\"\"" quoted_description)
    if(quoted_description EQUAL -1)
      message(FATAL_ERROR "Relocated CSV did not quote commas and embedded quotes")
    endif()
  endif()
endforeach()
call_tool(cad_bom "${TEST_DIR}/bom.json")
string(JSON original_inventory GET "${original_bom}" bom)
string(JSON historical_inventory GET "${reply}" bom)
if(NOT original_inventory STREQUAL historical_inventory)
  message(FATAL_ERROR "Metadata edit changed historical BOM output")
endif()
file(WRITE "${TEST_DIR}/bom-remove.json" [=[{"document_id":"spacer_assembly","expected_revision":2,"operations":[{"op":"remove_bom_item","assembly_id":"assembly","input":"plate"}]}]=])
call_tool(cad_apply "${TEST_DIR}/bom-remove.json")
file(WRITE "${TEST_DIR}/bom-restored.json" [=[{"document_id":"spacer_assembly","revision":3}]=])
call_tool(cad_bom "${TEST_DIR}/bom-restored.json")
string(JSON restored_inventory GET "${reply}" bom)
if(NOT original_inventory STREQUAL restored_inventory)
  message(FATAL_ERROR "Removing metadata did not restore automatic BOM groups")
endif()
foreach(example curved-plate curved-pipe)
  call_tool(cad_create "${SOURCE_DIR}/examples/${example}.create.json")
  string(JSON curve_document GET "${reply}" document_id)
  file(WRITE "${TEST_DIR}/curve-export.json" "{\"document_id\":\"${curve_document}\",\"revision\":1,\"format\":\"step\"}")
  call_tool(cad_export "${TEST_DIR}/curve-export.json")
  string(JSON curve_path GET "${reply}" path)
  if(NOT EXISTS "${curve_path}")
    message(FATAL_ERROR "Relocated curved-model export is missing")
  endif()
endforeach()
call_tool(cad_create "${SOURCE_DIR}/examples/articulated-arm.create.json")
call_tool(cad_robot_export "${SOURCE_DIR}/examples/articulated-arm.robot.json")
string(JSON robot_directory GET "${reply}" directory)
foreach(artifact model.urdf model.srdf robot.json manifest.json meshes/mesh_0.stl)
  if(NOT EXISTS "${robot_directory}/${artifact}")
    message(FATAL_ERROR "Relocated native robot export omitted ${artifact}")
  endif()
endforeach()
file(READ "${robot_directory}/model.urdf" robot_xml)
if(NOT robot_xml MATCHES "mate_spindle_joint_angle" OR NOT robot_xml MATCHES "mate_spindle_joint_travel" OR NOT robot_xml MATCHES "mimic")
  message(FATAL_ERROR "Relocated robot export lost cylindrical motion or coupling")
endif()
file(READ "${SOURCE_DIR}/examples/articulated-arm.robot.json" robot_input)
string(JSON robot_input SET "${robot_input}" robot format "\"sdf\"")
set(robot_inertials "[]")
set(inertial_index 0)
foreach(link part_ground part_lever part_slide part_spindle carrier_spindle_joint)
  # Explicit synthetic test data, not physical properties inferred from CAD.
  string(JSON robot_inertials SET "${robot_inertials}" ${inertial_index}
    "{\"link\":\"${link}\",\"mass_kg\":0.1,\"center_of_mass_m\":[0,0,0],\"inertia_kg_m2\":[0.00002,0.00003,0.00004,0,0,0]}")
  math(EXPR inertial_index "${inertial_index}+1")
endforeach()
string(JSON robot_input SET "${robot_input}" robot inertials "${robot_inertials}")
file(WRITE "${TEST_DIR}/robot-sdf.json" "${robot_input}")
call_tool(cad_robot_export "${TEST_DIR}/robot-sdf.json")
string(JSON robot_sdf GET "${reply}" path)
file(READ "${robot_sdf}" robot_sdf_xml)
if(NOT robot_sdf_xml MATCHES "<sdf version=\"1.12\">" OR NOT robot_sdf_xml MATCHES "<inertial>")
  message(FATAL_ERROR "Relocated SDF export lost its version or physical data")
endif()
file(SHA256 "${TEST_DIR}/workspace/documents/articulated_arm/HEAD.json" playback_head_before)
file(WRITE "${TEST_DIR}/playback-open.json" [=[{"document_id":"articulated_arm","view_id":"bundle_playback"}]=])
call_tool(cad_open "${TEST_DIR}/playback-open.json")
file(WRITE "${TEST_DIR}/playback-sync.json" [=[{"action":"sync","view_id":"bundle_playback"}]=])
foreach(attempt RANGE 0 499)
  call_tool(cad_viewer "${TEST_DIR}/playback-sync.json")
  string(JSON playback_state GET "${reply}" state)
  if(playback_state STREQUAL "ready")
    break()
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
endforeach()
if(NOT playback_state STREQUAL "ready" OR NOT EXISTS "${SOURCE_DIR}/PLAYBACK.md")
  message(FATAL_ERROR "Relocated native playback source or bundled guidance is unavailable")
endif()
string(JSON playback_evaluation GET "${reply}" evaluation_id)
file(READ "${SOURCE_DIR}/examples/articulated-arm.sequence.json" playback_definition)
file(WRITE "${TEST_DIR}/playback-save.json" "{\"action\":\"sequence\",\"operation\":\"save\",\"view_id\":\"bundle_playback\",\"evaluation_id\":\"${playback_evaluation}\",\"sequence\":${playback_definition}}")
call_tool(cad_viewer "${TEST_DIR}/playback-save.json")
string(JSON playback_source_evaluation GET "${reply}" sequences 0 source evaluation_id)
if(NOT playback_source_evaluation STREQUAL playback_evaluation)
  message(FATAL_ERROR "Relocated sequence lost its original source evaluation")
endif()
file(WRITE "${TEST_DIR}/playback-seek.json" "{\"action\":\"sequence\",\"operation\":\"seek\",\"view_id\":\"bundle_playback\",\"evaluation_id\":\"${playback_evaluation}\",\"name\":\"Coordinated arm review\",\"time_s\":1}")
call_tool(cad_viewer "${TEST_DIR}/playback-seek.json")
foreach(attempt RANGE 0 499)
  call_tool(cad_viewer "${TEST_DIR}/playback-sync.json")
  string(JSON playback_state GET "${reply}" state)
  if(playback_state STREQUAL "ready")
    break()
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
endforeach()
string(JSON playback_angle GET "${reply}" summary assembly motion dofs 0 value)
string(JSON playback_feed GET "${reply}" summary assembly motion dofs 1 value)
string(JSON playback_time GET "${reply}" playback time_s)
string(JSON playback_display_state GET "${reply}" playback state)
string(JSON playback_explode GET "${reply}" presentation explode distance_mm)
file(SHA256 "${TEST_DIR}/workspace/documents/articulated_arm/HEAD.json" playback_head_after)
if(NOT playback_state STREQUAL "ready" OR NOT playback_angle EQUAL 45 OR NOT playback_feed EQUAL 4.5 OR NOT playback_time EQUAL 1 OR NOT playback_explode EQUAL 5 OR NOT playback_display_state STREQUAL "displayed" OR NOT playback_head_before STREQUAL playback_head_after)
  message(FATAL_ERROR "Relocated playback lost interpolated native geometry, displayed time or immutable source")
endif()
file(WRITE "${TEST_DIR}/motion-preview.json" [=[{"document_id":"articulated_arm","expected_revision":1,"kind":"mesh","operations":[{"op":"apply_pose","assembly_id":"mechanism","pose_id":"extended"}]}]=])
call_tool(cad_preview "${TEST_DIR}/motion-preview.json")
string(JSON is_draft GET "${reply}" draft)
string(JSON angle GET "${reply}" summary assembly motion dofs 0 value)
string(JSON feed GET "${reply}" summary assembly motion dofs 1 value)
if(NOT is_draft OR NOT angle EQUAL 90 OR NOT feed EQUAL 9)
  message(FATAL_ERROR "Relocated motion preview lost its joint or coupling state")
endif()
file(WRITE "${TEST_DIR}/motion-save.json" [=[{"document_id":"articulated_arm","expected_revision":1,"operations":[{"op":"apply_pose","assembly_id":"mechanism","pose_id":"extended"}]}]=])
call_tool(cad_apply "${TEST_DIR}/motion-save.json")
string(JSON motion_revision GET "${reply}" revision)
if(NOT motion_revision EQUAL 2)
  message(FATAL_ERROR "Relocated pose edit did not commit a revision")
endif()
file(WRITE "${TEST_DIR}/motion-history.json" [=[{"document_id":"articulated_arm","revision":1}]=])
call_tool(cad_read "${TEST_DIR}/motion-history.json")
string(JSON historic_angle GET "${reply}" model parameters arm_angle)
if(NOT historic_angle EQUAL 30)
  message(FATAL_ERROR "Relocated pose save changed its historical source")
endif()
file(WRITE "${TEST_DIR}/motion-export.json" [=[{"document_id":"articulated_arm","revision":2,"format":"stl"}]=])
call_tool(cad_export "${TEST_DIR}/motion-export.json")
call_tool(cad_create "${SOURCE_DIR}/examples/nested-assembly.create.json")
string(JSON nested_parts LENGTH "${reply}" summary assembly parts)
string(JSON nested_occurrences GET "${reply}" summary assembly mechanisms 0 occurrences)
string(JSON nested_scope GET "${reply}" summary assembly mechanisms 0 assembly_id)
if(NOT nested_parts EQUAL 5 OR NOT nested_scope STREQUAL "module" OR
    NOT nested_occurrences MATCHES "left" OR NOT nested_occurrences MATCHES "right")
  message(FATAL_ERROR "Relocated nested assembly omitted child mechanism occurrences")
endif()
file(WRITE "${TEST_DIR}/nested-motion.json" [=[{"document_id":"nested_assembly_demo","expected_revision":1,"operations":[{"op":"set_joint_value","assembly_id":"module","mate_id":"pivot","coordinate":"angle_deg","value":30},{"op":"set_pose","assembly_id":"module","pose":{"id":"review","values":[{"mate_id":"pivot","coordinate":"angle_deg","value":30}]}}]}]=])
call_tool(cad_apply "${TEST_DIR}/nested-motion.json")
string(JSON nested_angle GET "${reply}" summary assembly mechanisms 0 motion dofs 0 value)
if(NOT nested_angle EQUAL 30)
  message(FATAL_ERROR "Relocated child pose edit did not update the composed assembly")
endif()
# Explicit illustrative properties; no physical properties are inferred.
file(WRITE "${TEST_DIR}/nested-robot.json" [=[{"document_id":"nested_assembly_demo","revision":2,"robot":{"format":"urdf","joint_properties":[{"mate_id":"left/pivot","coordinate":"angle_deg","effort":1,"velocity":0.2},{"mate_id":"right/pivot","coordinate":"angle_deg","effort":1,"velocity":0.2}]}}]=])
call_tool(cad_robot_export "${TEST_DIR}/nested-robot.json")
string(JSON nested_directory GET "${reply}" directory)
file(READ "${nested_directory}/robot.json" nested_ledger)
string(JSON nested_coordinates LENGTH "${nested_ledger}" coordinates)
string(JSON nested_pose GET "${nested_ledger}" frames pose_sources 0 name)
file(READ "${nested_directory}/model.urdf" nested_urdf)
file(READ "${nested_directory}/model.srdf" nested_srdf)
if(NOT nested_coordinates EQUAL 2 OR NOT nested_ledger MATCHES "shared_definition" OR
    NOT nested_urdf MATCHES "nested_part_4_left_4_link" OR NOT nested_srdf MATCHES "${nested_pose}")
  message(FATAL_ERROR "Relocated robot export lost nested links, shared coordinates or the child preset")
endif()
file(WRITE "${TEST_DIR}/nested-history.json" [=[{"document_id":"nested_assembly_demo","revision":1}]=])
call_tool(cad_read "${TEST_DIR}/nested-history.json")
string(JSON nested_original GET "${reply}" model features 2 mates 0 angle_deg parameter)
if(NOT nested_original STREQUAL "angle")
  message(FATAL_ERROR "Relocated nested motion edit changed historical parameter intent")
endif()
if(NOT EXISTS "${SOURCE_DIR}/COMPONENTS.md")
  message(FATAL_ERROR "Relocated bundle omitted pinned-component guidance")
endif()
call_tool(cad_create "${SOURCE_DIR}/examples/component-assembly.create.json")
call_tool(cad_apply "${SOURCE_DIR}/examples/component-assembly.edit.json")
string(JSON component_revision GET "${reply}" model components 0 source revision)
string(JSON component_volume GET "${reply}" summary volume_mm3)
string(JSON component_parts LENGTH "${reply}" summary assembly parts)
string(JSON component_modified GET "${reply}" summary components 0 modified)
string(JSON component_model GET "${reply}" model)
if(NOT component_revision EQUAL 1 OR NOT component_parts EQUAL 5 OR
    component_volume LESS 6207.9999 OR component_volume GREATER 6208.0001 OR component_modified)
  message(FATAL_ERROR "Relocated component capture lost its pinned revision or exact repeated geometry")
endif()
if(NOT EXISTS "${SOURCE_DIR}/DEPENDENCY_CACHE.md")
  message(FATAL_ERROR "Relocated bundle omitted native dependency-cache guidance")
endif()
# A bound joint edit changes the two assembly definitions, while retaining both
# imported solid entries. Inspect private cache evidence without a public API.
function(component_cache_entries prefix)
  file(GLOB paths "${TEST_DIR}/workspace/.cache/*.json")
  set(solids "")
  set(assemblies "")
  foreach(path IN LISTS paths)
    file(READ "${path}" envelope)
    string(JSON payload GET "${envelope}" payload)
    string(JSON feature ERROR_VARIABLE absent GET "${payload}" feature_id)
    if(NOT absent)
      if(feature MATCHES "^cf_12_hinge_module_")
        list(APPEND solids "${path}")
      elseif(feature STREQUAL "hinge_module" OR feature STREQUAL "fixture")
        list(APPEND assemblies "${path}")
      endif()
    endif()
  endforeach()
  list(SORT solids)
  list(LENGTH assemblies count)
  set(${prefix}_solids "${solids}" PARENT_SCOPE)
  set(${prefix}_assemblies "${count}" PARENT_SCOPE)
endfunction()
component_cache_entries(component_before)
list(LENGTH component_before_solids component_solid_count)
if(NOT component_solid_count EQUAL 2 OR NOT component_before_assemblies EQUAL 2)
  message(FATAL_ERROR "Relocated capture did not stage its exact feature dependencies")
endif()
foreach(path IN LISTS component_before_solids)
  file(SHA256 "${path}" digest)
  set("component_hash_${path}" "${digest}")
endforeach()
file(WRITE "${TEST_DIR}/component-pose.json" [=[{"document_id":"component_assembly_demo","expected_revision":2,"operations":[{"op":"set_parameter","name":"module_angle","value":65}]}]=])
call_tool(cad_apply "${TEST_DIR}/component-pose.json")
string(JSON component_angle GET "${reply}" summary assembly mechanisms 0 motion dofs 0 value)
string(JSON component_modified GET "${reply}" summary components 0 modified)
if(NOT component_angle EQUAL 65 OR component_modified)
  message(FATAL_ERROR "Relocated component parameter binding lost its intent")
endif()
component_cache_entries(component_after)
if(NOT component_before_solids STREQUAL component_after_solids OR
    NOT component_after_assemblies EQUAL 4)
  message(FATAL_ERROR "Relocated pose edit rebuilt unchanged component solids or lost an assembly dependency")
endif()
foreach(path IN LISTS component_before_solids)
  file(SHA256 "${path}" digest)
  if(NOT digest STREQUAL "${component_hash_${path}}")
    message(FATAL_ERROR "Relocated pose edit changed an unchanged component cache entry")
  endif()
endforeach()
# Rebuild the saved snapshot in a separate workspace containing no source library.
file(WRITE "${TEST_DIR}/component-portable.json" "{\"document_id\":\"portable\",\"model\":${component_model}}")
execute_process(COMMAND "${CAD_EXE}" call cad_create --workspace "${TEST_DIR}/portable-workspace"
  --input "${TEST_DIR}/component-portable.json" RESULT_VARIABLE status OUTPUT_VARIABLE portable
  ERROR_VARIABLE logs TIMEOUT 30)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Relocated component required an absent source library: ${logs}")
endif()
string(JSON portable_volume GET "${portable}" summary volume_mm3)
if(portable_volume LESS 6207.9999 OR portable_volume GREATER 6208.0001)
  message(FATAL_ERROR "Self-contained portable component changed its geometry")
endif()
if(NOT EXISTS "${SOURCE_DIR}/MANUFACTURING.md")
  message(FATAL_ERROR "Relocated bundle omitted manufacturing-package guidance")
endif()
file(WRITE "${TEST_DIR}/component-manufacture.json" [=[{"document_id":"component_assembly_demo","revision":3,"options":{"part_drawing":{"views":[{"id":"front","orientation":"front"}],"dimensions":[{"view":"front","kind":"width"}]}}}]=])
call_tool(cad_manufacture "${TEST_DIR}/component-manufacture.json")
string(JSON package_directory GET "${reply}" directory)
string(JSON package_manifest GET "${reply}" path)
string(JSON package_part_count GET "${reply}" part_count)
file(READ "${package_manifest}" portable_manifest)
string(JSON package_occurrences LENGTH "${portable_manifest}" occurrences)
string(JSON review_status GET "${portable_manifest}" process_review status)
if(NOT package_part_count EQUAL 3 OR NOT package_occurrences EQUAL 5 OR NOT review_status STREQUAL "not_evaluated")
  message(FATAL_ERROR "Relocated manufacturing lost unique sources, occurrences or truthful process status")
endif()
string(JSON artifact_count LENGTH "${portable_manifest}" artifacts)
math(EXPR last_artifact "${artifact_count}-1")
foreach(index RANGE 0 ${last_artifact})
  string(JSON relative GET "${portable_manifest}" artifacts ${index} path)
  string(JSON expected_hash GET "${portable_manifest}" artifacts ${index} sha256)
  string(JSON expected_bytes GET "${portable_manifest}" artifacts ${index} bytes)
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "\\.\\.")
    message(FATAL_ERROR "Manufacturing manifest artifact reference is not portable")
  endif()
  file(SHA256 "${package_directory}/${relative}" actual_hash)
  file(SIZE "${package_directory}/${relative}" actual_bytes)
  if(NOT actual_hash STREQUAL expected_hash OR NOT actual_bytes EQUAL expected_bytes)
    message(FATAL_ERROR "Relocated manufacturing artifact failed independent hash/size verification")
  endif()
endforeach()
file(READ "${package_directory}/source.json" package_source)
string(JSON package_pin GET "${package_source}" model components 0 source revision)
string(JSON package_angle GET "${package_source}" model parameters module_angle)
if(NOT package_pin EQUAL 1 OR NOT package_angle EQUAL 65)
  message(FATAL_ERROR "Relocated manufacturing source lost its pin or current bound pose")
endif()
if(NOT EXISTS "${SOURCE_DIR}/FABRICATION_REVIEW.md")
  message(FATAL_ERROR "Relocated bundle omitted measured fabrication guidance")
endif()
file(WRITE "${TEST_DIR}/component-review.json" [=[{"document_id":"component_assembly_demo","revision":3,"options":{"profile":{"process":"fdm","orientation":{"build_direction":[0,0,1],"x_direction":[1,0,0]},"minimum_wall_mm":1000,"overhang_angle_deg":45}}}]=])
call_tool(cad_fabrication_review "${TEST_DIR}/component-review.json")
string(JSON review_path GET "${reply}" path)
string(JSON review_hash GET "${reply}" sha256)
file(SHA256 "${review_path}" actual_review_hash)
file(READ "${review_path}" measured_review)
string(JSON reviewed_revision GET "${measured_review}" source revision)
string(JSON reviewed_status GET "${measured_review}" report status)
string(JSON reviewed_sources LENGTH "${measured_review}" report parts)
if(NOT actual_review_hash STREQUAL review_hash OR NOT reviewed_revision EQUAL 3 OR NOT reviewed_sources EQUAL 3 OR NOT reviewed_status STREQUAL "fail")
  message(FATAL_ERROR "Relocated measured review lost artifact identity, source roll-up or measured findings")
endif()
if(NOT EXISTS "${SOURCE_DIR}/GCODE_REVIEW.md")
  message(FATAL_ERROR "Relocated bundle omitted native G-code guidance")
endif()
file(WRITE "${TEST_DIR}/review fixture.gcode" "G21\nG90\nM83\nM104S210\nM140S60\nG1X10Y5Z.2E1\nG91\nG1X15E1\n")
file(SHA256 "${TEST_DIR}/review fixture.gcode" gcode_hash)
file(TO_CMAKE_PATH "${TEST_DIR}/review fixture.gcode" gcode_path_json)
set(gcode_args [=[{"document_id":"component_assembly_demo","revision":3,"options":{"firmware":"marlin","machine":{"name":"Relocated fixture","motion_bounds_mm":[[-20,20],[-20,20],[0,100]]},"material":{"name":"Fixture ranges","nozzle_temperature_c":[190,230],"bed_temperature_c":[50,70]},"initial":{"units":"mm","xyz_mode":"absolute","extrusion_mode":"absolute","position_mm":[0,0,0],"extruder_mm":0}}}]=])
string(JSON gcode_args SET "${gcode_args}" path "\"${gcode_path_json}\"")
string(JSON gcode_args SET "${gcode_args}" expected_sha256 "\"${gcode_hash}\"")
file(WRITE "${TEST_DIR}/gcode-review.json" "${gcode_args}")
call_tool(cad_gcode_review "${TEST_DIR}/gcode-review.json")
string(JSON gcode_original GET "${reply}" artifact_path)
string(JSON gcode_review_path GET "${reply}" path)
string(JSON gcode_review_hash GET "${reply}" report_sha256)
string(JSON gcode_status GET "${reply}" report status)
string(JSON gcode_x_max GET "${reply}" report statistics commanded_bounds_mm 0 1)
file(SHA256 "${gcode_original}" actual_gcode_hash)
file(SHA256 "${gcode_review_path}" actual_gcode_review_hash)
if(NOT actual_gcode_hash STREQUAL gcode_hash OR NOT actual_gcode_review_hash STREQUAL gcode_review_hash OR NOT gcode_status STREQUAL "fail" OR NOT gcode_x_max EQUAL 25)
  message(FATAL_ERROR "Relocated native G-code review lost original identity or relative-motion failure")
endif()
if(NOT EXISTS "${SOURCE_DIR}/SLICING.md")
  message(FATAL_ERROR "Relocated bundle omitted native slicing guidance")
endif()
# These native fixtures exercise process plumbing with empty PATH. They are
# supplied explicitly as an installed-tool stand-in, never shipped as a slicer.
file(MAKE_DIRECTORY "${TEST_DIR}/native profiles")
set(slice_profiles "{}")
foreach(role machine process filament)
  if(role STREQUAL "machine")
    set(profile [=[{"type":"machine","name":"Normal","gcode_flavor":"marlin","printer_technology":"FFF"}]=])
  else()
    set(profile "{\"type\":\"${role}\",\"name\":\"Fixture ${role}\",\"compatible_printers\":[\"Normal\"],\"post_process\":[\"\"]}")
  endif()
  set(profile_path "${TEST_DIR}/native profiles/${role}.json")
  file(WRITE "${profile_path}" "${profile}")
  file(SHA256 "${profile_path}" profile_hash)
  file(TO_CMAKE_PATH "${profile_path}" profile_json_path)
  string(JSON slice_profiles SET "${slice_profiles}" ${role} "{\"path\":\"${profile_json_path}\",\"expected_sha256\":\"${profile_hash}\"}")
endforeach()
string(JSON slice_review GET "${gcode_args}" options)
if(NOT EXISTS "${SOURCE_DIR}/PRINTER_HANDOFF.md")
  message(FATAL_ERROR "Relocated bundle omitted native printer handoff guidance")
endif()
file(SHA256 "${TEST_DIR}/workspace/documents/component_assembly_demo/HEAD.json" printer_head_before)
set(printer_options "{\"printer\":{\"backend\":\"manual\",\"id\":\"relocated_fixture\",\"model\":\"Explicit relocated fixture\",\"nozzle_diameter_mm\":0.4,\"bed_type\":\"Assessed fixture plate\",\"handoff\":\"plain_gcode\"},\"profiles\":${slice_profiles},\"review\":${slice_review}}")
set(printer_args "{\"document_id\":\"component_assembly_demo\",\"revision\":3,\"action\":\"plan\",\"path\":\"${gcode_path_json}\",\"expected_sha256\":\"${gcode_hash}\",\"options\":${printer_options}}")
file(WRITE "${TEST_DIR}/printer-plan.json" "${printer_args}")
call_tool(cad_printer_handoff "${TEST_DIR}/printer-plan.json")
string(JSON printer_plan GET "${reply}" path)
string(JSON printer_directory GET "${reply}" directory)
string(JSON printer_plan_hash GET "${reply}" sha256)
string(JSON printer_status GET "${reply}" readiness status)
string(JSON printer_report_status GET "${reply}" report status)
string(JSON printer_association GET "${reply}" source_association)
string(JSON printer_contact GET "${reply}" hardware_contact)
string(JSON printer_started GET "${reply}" physical_print_started)
string(JSON printer_upload_supported GET "${reply}" readiness native_upload_supported)
string(JSON printer_start_supported GET "${reply}" readiness native_start_supported)
file(SHA256 "${printer_plan}" actual_printer_plan_hash)
file(SHA256 "${printer_directory}/original.gcode" actual_printer_gcode_hash)
if(NOT actual_printer_plan_hash STREQUAL printer_plan_hash OR NOT actual_printer_gcode_hash STREQUAL gcode_hash
    OR NOT printer_status STREQUAL "fail" OR NOT printer_report_status STREQUAL "fail"
    OR NOT printer_association STREQUAL "caller_declared_not_geometry_verified"
    OR printer_contact OR printer_started OR printer_upload_supported OR printer_start_supported)
  message(FATAL_ERROR "Relocated native printer plan lost byte/source qualification, failed findings or offline limitations")
endif()
# Verification resolves only the contained package. Relocating it must not
# depend on the original package location or the installed bundle path.
set(printer_portable "${TEST_DIR}/portable printer package")
file(COPY "${printer_directory}/" DESTINATION "${printer_portable}")
file(REMOVE_RECURSE "${printer_directory}")
file(TO_CMAKE_PATH "${printer_portable}/plan.json" printer_portable_json)
file(WRITE "${TEST_DIR}/printer-verify.json" "{\"document_id\":\"component_assembly_demo\",\"revision\":3,\"action\":\"verify\",\"plan_path\":\"${printer_portable_json}\",\"expected_sha256\":\"${printer_plan_hash}\"}")
call_tool(cad_printer_handoff "${TEST_DIR}/printer-verify.json")
string(JSON printer_verified_hash GET "${reply}" gcode_sha256)
string(JSON printer_verified_status GET "${reply}" readiness status)
string(JSON printer_verified_contact GET "${reply}" hardware_contact)
file(SHA256 "${TEST_DIR}/workspace/documents/component_assembly_demo/HEAD.json" printer_head_after)
if(NOT printer_verified_hash STREQUAL gcode_hash OR NOT printer_verified_status STREQUAL "fail"
    OR printer_verified_contact OR NOT printer_head_before STREQUAL printer_head_after)
  message(FATAL_ERROR "Relocated printer verification lost failed findings, original bytes or preserved source HEAD")
endif()
set(slice_options "{\"backend\":\"orcaslicer\",\"version\":\"2.4.2\",\"bed_type\":\"High Temp Plate\",\"profiles\":${slice_profiles},\"review\":${slice_review}}")
file(TO_CMAKE_PATH "${TEST_DIR}/missing-slicer${suffix}" missing_slicer)
string(JSON slice_options SET "${slice_options}" executable "{\"path\":\"${missing_slicer}\",\"expected_sha256\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"}")
set(slice_args "{\"document_id\":\"plate\",\"revision\":2,\"action\":\"plan\",\"options\":${slice_options}}")
file(WRITE "${TEST_DIR}/missing-slicer.json" "${slice_args}")
execute_process(COMMAND "${CAD_EXE}" call cad_slice --workspace "${TEST_DIR}/workspace" --input "${TEST_DIR}/missing-slicer.json"
  RESULT_VARIABLE missing_status OUTPUT_VARIABLE missing_output ERROR_VARIABLE missing_logs TIMEOUT 30)
string(JSON missing_error GET "${missing_logs}" error code)
if(missing_status EQUAL 0 OR NOT missing_output STREQUAL "" OR NOT missing_error STREQUAL "invalid_argument")
  message(FATAL_ERROR "Relocated bundle did not explicitly reject a missing installed slicer")
endif()
if(DEFINED SLICER_FIXTURE AND NOT SLICER_FIXTURE STREQUAL "")
  file(SHA256 "${SLICER_FIXTURE}" fixture_hash)
  file(TO_CMAKE_PATH "${SLICER_FIXTURE}" fixture_path)
  string(JSON slice_options SET "${slice_options}" executable "{\"path\":\"${fixture_path}\",\"expected_sha256\":\"${fixture_hash}\"}")
  string(JSON slice_args SET "${slice_args}" options "${slice_options}")
  file(WRITE "${TEST_DIR}/slice-plan.json" "${slice_args}")
  call_tool(cad_slice "${TEST_DIR}/slice-plan.json")
  string(JSON slice_plan_path GET "${reply}" path)
  string(JSON slice_plan_hash GET "${reply}" sha256)
  file(SHA256 "${slice_plan_path}" actual_plan_hash)
  if(NOT actual_plan_hash STREQUAL slice_plan_hash)
    message(FATAL_ERROR "Relocated dry-run plan hash differs from raw bytes")
  endif()
  file(TO_CMAKE_PATH "${slice_plan_path}" slice_plan_json_path)
  file(WRITE "${TEST_DIR}/slice-run.json" "{\"document_id\":\"plate\",\"revision\":2,\"action\":\"run\",\"plan_path\":\"${slice_plan_json_path}\",\"expected_sha256\":\"${slice_plan_hash}\"}")
  call_tool(cad_slice "${TEST_DIR}/slice-run.json")
  string(JSON sliced_gcode GET "${reply}" gcode_path)
  string(JSON sliced_hash GET "${reply}" gcode_sha256)
  string(JSON sliced_manifest GET "${reply}" path)
  string(JSON sliced_directory GET "${reply}" directory)
  string(JSON physical_started GET "${reply}" physical_print_started)
  file(SHA256 "${sliced_gcode}" actual_slice_hash)
  if(NOT actual_slice_hash STREQUAL sliced_hash OR physical_started)
    message(FATAL_ERROR "Relocated slicing lost raw G-code identity or claimed a physical print")
  endif()
  file(READ "${sliced_manifest}" sliced_manifest_json)
  string(JSON sliced_count LENGTH "${sliced_manifest_json}" artifacts)
  math(EXPR last_sliced "${sliced_count}-1")
  foreach(index RANGE 0 ${last_sliced})
    string(JSON relative GET "${sliced_manifest_json}" artifacts ${index} path)
    string(JSON expected_hash GET "${sliced_manifest_json}" artifacts ${index} sha256)
    string(JSON expected_size GET "${sliced_manifest_json}" artifacts ${index} bytes)
    file(SHA256 "${sliced_directory}/${relative}" actual_hash)
    file(SIZE "${sliced_directory}/${relative}" actual_size)
    if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)" OR NOT actual_hash STREQUAL expected_hash OR NOT actual_size EQUAL expected_size)
      message(FATAL_ERROR "Relocated slicing manifest artifact failed size/hash/path checks")
    endif()
  endforeach()
endif()
if(NOT EXISTS "${SOURCE_DIR}/PURCHASED_PARTS.md")
  message(FATAL_ERROR "Relocated bundle omitted sourced-part guidance")
endif()
file(WRITE "${TEST_DIR}/supplier-export.json" [=[{"document_id":"component_assembly_demo","revision":3,"format":"step"}]=])
call_tool(cad_export "${TEST_DIR}/supplier-export.json")
string(JSON supplier_step GET "${reply}" path)
file(SHA256 "${supplier_step}" supplier_hash)
# Use actual native example output, never a network-dependent CTest fixture.
set(supplier_args "{}")
file(TO_CMAKE_PATH "${supplier_step}" supplier_step_json)
string(JSON supplier_args SET "${supplier_args}" document_id "\"bundled_purchase\"")
string(JSON supplier_args SET "${supplier_args}" path "\"${supplier_step_json}\"")
string(JSON supplier_args SET "${supplier_args}" expected_sha256 "\"${supplier_hash}\"")
string(JSON supplier_args SET "${supplier_args}" purchase [=[{"supplier":"Bundle fixture supplier","part_number":"BUNDLE-PART","source_url":"https://example.invalid/BUNDLE-PART"}]=])
file(WRITE "${TEST_DIR}/supplier-import.json" "${supplier_args}")
call_tool(cad_import "${TEST_DIR}/supplier-import.json")
string(JSON imported_purchase_hash GET "${reply}" model features 0 purchase artifact_sha256)
if(NOT imported_purchase_hash STREQUAL supplier_hash)
  message(FATAL_ERROR "Relocated import did not bind supplier identity to actual STEP bytes")
endif()
file(WRITE "${TEST_DIR}/supplier-package.json" [=[{"document_id":"bundled_purchase","revision":1,"options":{"drawings":false}}]=])
call_tool(cad_manufacture "${TEST_DIR}/supplier-package.json")
string(JSON supplier_package GET "${reply}" directory)
file(READ "${supplier_package}/manifest.json" supplier_manifest)
string(JSON supplier_original GET "${supplier_manifest}" parts 0 source_artifact path)
file(SHA256 "${supplier_package}/${supplier_original}" original_hash)
string(JSON packaged_purchase_hash GET "${supplier_manifest}" parts 0 purchase artifact_sha256)
if(NOT original_hash STREQUAL supplier_hash OR NOT packaged_purchase_hash STREQUAL supplier_hash)
  message(FATAL_ERROR "Relocated package lost original supplier STEP identity")
endif()
# Exercise the relocated parser and read-only viewer with actual original
# bytes, while PATH and loader overrides remain empty. Fixtures are prebuilt
# developer inputs copied into this disposable workflow; no script runtime runs.
function(artifact_read_tool tool input)
  foreach(read_attempt RANGE 0 199)
    execute_process(COMMAND "${CAD_EXE}" call "${tool}" --workspace "${TEST_DIR}/workspace" --input "${input}"
      RESULT_VARIABLE read_status OUTPUT_VARIABLE read_output ERROR_VARIABLE read_logs TIMEOUT 30)
    if(read_status EQUAL 0)
      string(JSON read_kind TYPE "${read_output}")
      if(NOT read_kind STREQUAL "OBJECT")
        message(FATAL_ERROR "Relocated artifact read returned non-JSON stdout: ${read_output}")
      endif()
      set(reply "${read_output}" PARENT_SCOPE)
      return()
    endif()
    string(JSON read_error ERROR_VARIABLE invalid_error GET "${read_logs}" error code)
    if(invalid_error OR NOT read_error STREQUAL "workspace_busy")
      message(FATAL_ERROR "Relocated artifact ${tool} read failed: ${read_logs}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
  endforeach()
  message(FATAL_ERROR "Relocated artifact ${tool} read remained busy: ${read_logs}")
endfunction()
file(WRITE "${TEST_DIR}/artifact-native-read.json" "{\"document_id\":\"${presented_document}\"}")
artifact_read_tool(cad_read "${TEST_DIR}/artifact-native-read.json")
set(artifact_native_before "${reply}")
string(JSON artifact_native_revision GET "${reply}" revision)
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" artifact_head_before)
file(MAKE_DIRECTORY "${TEST_DIR}/artifact-inputs")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/artifact_fixtures/nested-deflate.3mf" DESTINATION "${TEST_DIR}/artifact-inputs")
file(REAL_PATH "${TEST_DIR}/artifact-inputs/nested-deflate.3mf" artifact_original)
file(READ "${artifact_original}" artifact_zip_method OFFSET 8 LIMIT 2 HEX)
if(NOT artifact_zip_method STREQUAL "0800")
  message(FATAL_ERROR "External bundle fixture must actually use ZIP deflate")
endif()
file(SHA256 "${artifact_original}" artifact_original_hash)
file(TO_CMAKE_PATH "${artifact_original}" artifact_original_json)
file(WRITE "${TEST_DIR}/artifact-review.json" "{\"action\":\"review\",\"path\":\"${artifact_original_json}\",\"format\":\"3mf\",\"units\":\"file\",\"expected_sha256\":\"${artifact_original_hash}\"}")
call_tool(cad_artifact "${TEST_DIR}/artifact-review.json")
string(JSON artifact_directory GET "${reply}" directory)
string(JSON artifact_review_path GET "${reply}" path)
string(JSON artifact_review_hash GET "${reply}" sha256)
string(JSON artifact_source_hash GET "${reply}" source sha256)
string(JSON artifact_read_only GET "${reply}" read_only)
string(JSON artifact_history GET "${reply}" editable_history_recovered)
string(JSON artifact_native_selectors GET "${reply}" native_selection_references)
string(JSON artifact_units GET "${reply}" summary units)
string(JSON artifact_representation GET "${reply}" summary representation)
string(JSON artifact_triangles GET "${reply}" summary triangles)
string(JSON artifact_min_x GET "${reply}" summary bounds min 0)
string(JSON artifact_max_x GET "${reply}" summary bounds max 0)
file(SHA256 "${artifact_review_path}" artifact_actual_review_hash)
if(NOT artifact_source_hash STREQUAL artifact_original_hash OR NOT artifact_actual_review_hash STREQUAL artifact_review_hash
    OR NOT artifact_read_only OR artifact_history OR artifact_native_selectors
    OR NOT artifact_units STREQUAL "mm" OR NOT artifact_representation STREQUAL "triangle_mesh"
    OR NOT artifact_triangles EQUAL 1 OR NOT artifact_min_x EQUAL 120 OR NOT artifact_max_x EQUAL 130)
  message(FATAL_ERROR "Relocated deflated 3MF parser lost source hash, centimeter/component transforms or read-only qualification")
endif()
# Verification must depend only on the captured portable bytes, including after
# both the original file and its first managed package location are removed.
set(artifact_portable "${TEST_DIR}/portable external review")
file(COPY "${artifact_directory}/" DESTINATION "${artifact_portable}")
file(REMOVE "${artifact_original}")
file(REMOVE_RECURSE "${artifact_directory}")
file(REAL_PATH "${artifact_portable}/review.json" artifact_portable_review)
file(TO_CMAKE_PATH "${artifact_portable_review}" artifact_portable_json)
file(WRITE "${TEST_DIR}/artifact-verify.json" "{\"action\":\"verify\",\"review_path\":\"${artifact_portable_json}\",\"expected_sha256\":\"${artifact_review_hash}\"}")
call_tool(cad_artifact "${TEST_DIR}/artifact-verify.json")
string(JSON artifact_verified_hash GET "${reply}" sha256)
string(JSON artifact_verified_source GET "${reply}" source sha256)
string(JSON artifact_captured_source GET "${reply}" source path)
file(SHA256 "${artifact_portable}/${artifact_captured_source}" artifact_captured_hash)
if(EXISTS "${artifact_original}" OR EXISTS "${artifact_directory}" OR NOT artifact_verified_hash STREQUAL artifact_review_hash
    OR NOT artifact_verified_source STREQUAL artifact_original_hash OR NOT artifact_captured_hash STREQUAL artifact_original_hash)
  message(FATAL_ERROR "Relocated artifact verify did not reparse independently captured original bytes")
endif()
file(WRITE "${TEST_DIR}/artifact-show.json" "{\"view_id\":\"bundle_presentation\",\"review_path\":\"${artifact_portable_json}\",\"expected_sha256\":\"${artifact_review_hash}\"}")
call_tool(cad_artifact_show "${TEST_DIR}/artifact-show.json")
string(JSON artifact_show_document TYPE "${reply}" document_id)
string(JSON artifact_show_read_only GET "${reply}" read_only)
if(NOT artifact_show_document STREQUAL "NULL" OR NOT artifact_show_read_only)
  message(FATAL_ERROR "Relocated artifact show retained a native document association")
endif()
artifact_read_tool(cad_viewer "${TEST_DIR}/presentation-sync.json")
string(JSON artifact_state GET "${reply}" state)
string(JSON artifact_evaluation GET "${reply}" evaluation_id)
string(JSON artifact_sync_hash GET "${reply}" artifact review_sha256)
string(JSON artifact_sync_document TYPE "${reply}" document_id)
string(JSON artifact_sync_revision TYPE "${reply}" revision)
string(JSON artifact_sync_feature TYPE "${reply}" feature_id)
if(NOT artifact_state STREQUAL "ready" OR NOT artifact_sync_hash STREQUAL artifact_review_hash
    OR NOT artifact_sync_document STREQUAL "NULL" OR NOT artifact_sync_revision STREQUAL "NULL" OR NOT artifact_sync_feature STREQUAL "NULL")
  message(FATAL_ERROR "Relocated read-only sync lost review identity or emitted synthetic native identity")
endif()
set(artifact_payload "")
set(artifact_offset 0)
set(artifact_mesh_complete FALSE)
foreach(chunk RANGE 0 9)
  file(WRITE "${TEST_DIR}/artifact-mesh.json" "{\"action\":\"mesh\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${artifact_evaluation}\",\"offset\":${artifact_offset}}")
  artifact_read_tool(cad_viewer "${TEST_DIR}/artifact-mesh.json")
  string(JSON artifact_data GET "${reply}" data)
  string(APPEND artifact_payload "${artifact_data}")
  string(JSON artifact_next_type TYPE "${reply}" next_offset)
  if(artifact_next_type STREQUAL "NULL")
    set(artifact_mesh_complete TRUE)
    break()
  endif()
  string(JSON artifact_offset GET "${reply}" next_offset)
endforeach()
string(JSON artifact_payload_kind GET "${artifact_payload}" kind)
string(JSON artifact_payload_groups LENGTH "${artifact_payload}" artifact_geometry groups)
string(JSON artifact_payload_triangles LENGTH "${artifact_payload}" artifact_geometry triangles)
string(JSON artifact_payload_group GET "${artifact_payload}" artifact_geometry groups 0 id)
string(JSON artifact_topology ERROR_VARIABLE artifact_topology_error TYPE "${artifact_payload}" topology)
if(NOT artifact_mesh_complete OR NOT artifact_payload_kind STREQUAL "artifact" OR NOT artifact_payload_groups EQUAL 1
    OR NOT artifact_payload_triangles EQUAL 1 OR NOT artifact_payload_group STREQUAL "artifact-1" OR NOT artifact_topology_error)
  message(FATAL_ERROR "Relocated artifact mesh transfer fabricated native topology or lost parsed geometry")
endif()
file(WRITE "${TEST_DIR}/artifact-pick.json" "{\"action\":\"context\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${artifact_evaluation}\",\"selection\":{\"review_sha256\":\"${artifact_review_hash}\",\"kind\":\"mesh_group\",\"entity_id\":\"artifact-1\"}}")
call_tool(cad_viewer "${TEST_DIR}/artifact-pick.json")
artifact_read_tool(cad_context "${TEST_DIR}/presentation-read.json")
string(JSON artifact_context_document TYPE "${reply}" document_id)
string(JSON artifact_context_hash GET "${reply}" selection review_sha256)
string(JSON artifact_context_kind GET "${reply}" selection kind)
string(JSON artifact_context_entity GET "${reply}" resolved_selection reference entity_id)
string(JSON artifact_context_editable GET "${reply}" resolved_selection geometry editable)
string(JSON artifact_context_notes LENGTH "${reply}" annotations)
string(JSON artifact_context_sequences LENGTH "${reply}" sequences)
string(JSON artifact_context_presets LENGTH "${reply}" presets)
string(JSON artifact_context_playback TYPE "${reply}" playback)
if(NOT artifact_context_document STREQUAL "NULL" OR NOT artifact_context_hash STREQUAL artifact_review_hash
    OR NOT artifact_context_kind STREQUAL "mesh_group" OR NOT artifact_context_entity STREQUAL "artifact-1" OR artifact_context_editable
    OR NOT artifact_context_notes EQUAL 0 OR NOT artifact_context_sequences EQUAL 0 OR NOT artifact_context_presets EQUAL 0
    OR NOT artifact_context_playback STREQUAL "NULL")
  message(FATAL_ERROR "Relocated artifact context lost review-local selection or inherited native review state")
endif()
foreach(action measure section preset annotation sequence motion_reset)
  set(artifact_native_action "{\"action\":\"${action}\",\"view_id\":\"bundle_presentation\",\"evaluation_id\":\"${artifact_evaluation}\"}")
  if(action STREQUAL "preset" OR action STREQUAL "annotation" OR action STREQUAL "sequence")
    string(JSON artifact_native_action SET "${artifact_native_action}" operation "\"list\"")
  endif()
  file(WRITE "${TEST_DIR}/artifact-denied-${action}.json" "${artifact_native_action}")
  execute_process(COMMAND "${CAD_EXE}" call cad_viewer --workspace "${TEST_DIR}/workspace" --input "${TEST_DIR}/artifact-denied-${action}.json"
    RESULT_VARIABLE artifact_denied_status OUTPUT_VARIABLE artifact_denied_output ERROR_VARIABLE artifact_denied_logs TIMEOUT 30)
  string(JSON artifact_denied_code GET "${artifact_denied_logs}" error code)
  if(artifact_denied_status EQUAL 0 OR NOT artifact_denied_output STREQUAL "" OR NOT artifact_denied_code STREQUAL "read_only_artifact")
    message(FATAL_ERROR "Relocated artifact view admitted native ${action}: ${artifact_denied_logs}")
  endif()
endforeach()
file(WRITE "${TEST_DIR}/artifact-native-show.json" "{\"view_id\":\"bundle_presentation\",\"document_id\":\"${presented_document}\"}")
call_tool(cad_show "${TEST_DIR}/artifact-native-show.json")
foreach(attempt RANGE 0 199)
  artifact_read_tool(cad_viewer "${TEST_DIR}/presentation-sync.json")
  string(JSON artifact_restored_state GET "${reply}" state)
  if(artifact_restored_state STREQUAL "ready")
    break()
  endif()
  if(NOT artifact_restored_state STREQUAL "loading")
    message(FATAL_ERROR "Relocated native restoration failed: ${reply}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.01)
endforeach()
string(JSON artifact_restored_document GET "${reply}" document_id)
string(JSON artifact_restored_revision GET "${reply}" revision)
string(JSON artifact_restored_model TYPE "${reply}" model)
if(NOT artifact_restored_state STREQUAL "ready" OR NOT artifact_restored_document STREQUAL presented_document
    OR NOT artifact_restored_revision EQUAL artifact_native_revision OR NOT artifact_restored_model STREQUAL "OBJECT")
  message(FATAL_ERROR "Relocated cad_show did not restore the actual editable native source")
endif()
artifact_read_tool(cad_context "${TEST_DIR}/presentation-read.json")
string(JSON artifact_restored_selection TYPE "${reply}" selection)
if(NOT artifact_restored_selection STREQUAL "NULL")
  message(FATAL_ERROR "Relocated native restoration retained an external artifact pick")
endif()
artifact_read_tool(cad_read "${TEST_DIR}/artifact-native-read.json")
file(SHA256 "${TEST_DIR}/workspace/documents/${presented_document}/HEAD.json" artifact_head_after)
if(NOT artifact_head_before STREQUAL artifact_head_after OR NOT artifact_native_before STREQUAL reply)
  message(FATAL_ERROR "External artifact review changed the existing native HEAD or source record")
endif()
message(STATUS "Relocated external review passed deflated 3MF/portable reparse/read-only mesh+context/native denial/source restoration with empty PATH")

set(app_requests "${TEST_DIR}/app-resource.jsonl")
file(WRITE "${app_requests}" [=[{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{"extensions":{"io.modelcontextprotocol/ui":{"mimeTypes":["text/html;profile=mcp-app"]}}},"clientInfo":{"name":"bundle-app-smoke","version":"1"}}}
{"jsonrpc":"2.0","method":"notifications/initialized"}
{"jsonrpc":"2.0","id":2,"method":"resources/read","params":{"uri":"ui://agent-3d-cad/viewer.html"}}
]=])
execute_process(COMMAND "${CAD_EXE}" serve --workspace "${TEST_DIR}/workspace"
  INPUT_FILE "${app_requests}" OUTPUT_VARIABLE app_responses ERROR_VARIABLE app_logs RESULT_VARIABLE app_status)
if(NOT app_status EQUAL 0)
  message(FATAL_ERROR "Relocated app resource request failed: ${app_logs}")
endif()
string(FIND "${app_responses}" "\n" app_first_newline)
math(EXPR app_offset "${app_first_newline}+1")
string(SUBSTRING "${app_responses}" ${app_offset} -1 app_reply)
string(JSON app_mime GET "${app_reply}" result contents 0 mimeType)
string(JSON app_html GET "${app_reply}" result contents 0 text)
if(NOT app_mime STREQUAL "text/html;profile=mcp-app" OR NOT app_html MATCHES "CadBridge" OR NOT app_html MATCHES "<canvas")
  message(FATAL_ERROR "Relocated bundle did not serve its embedded MCP App")
endif()
if(NOT app_html MATCHES "isolatePart" OR NOT app_html MATCHES "hidden_part_ids" OR NOT app_html MATCHES "Show all")
  message(FATAL_ERROR "Relocated MCP App omitted assembly visibility controls")
endif()
if(NOT EXISTS "${SOURCE_DIR}/PRESENTATION.md" OR NOT app_html MATCHES "clip-enabled" OR NOT app_html MATCHES "explode-distance" OR NOT app_html MATCHES "setPresentation")
  message(FATAL_ERROR "Relocated bundle omitted live clipping/explosion guidance or controls")
endif()
if(NOT EXISTS "${SOURCE_DIR}/MEASUREMENTS.md" OR NOT app_html MATCHES "measurement-pair" OR NOT app_html MATCHES "Check assembly clearance")
  message(FATAL_ERROR "Relocated bundle omitted exact measurement guidance or controls")
endif()
if(NOT EXISTS "${SOURCE_DIR}/SECTIONS.md" OR NOT app_html MATCHES "section-calculate" OR NOT app_html MATCHES "section-clear" OR NOT app_html MATCHES "section-result" OR NOT app_html MATCHES "setSection")
  message(FATAL_ERROR "Relocated bundle omitted native section guidance, controls or cap rendering")
endif()
if(NOT EXISTS "${SOURCE_DIR}/ANNOTATIONS.md" OR NOT app_html MATCHES "annotation-overlay" OR NOT app_html MATCHES "annotation-add" OR NOT app_html MATCHES "setAnnotations")
  message(FATAL_ERROR "Relocated bundle omitted review note contract, controls or image pin composition")
endif()
if(NOT app_html MATCHES "appearance-default" OR NOT app_html MATCHES "preset-save" OR NOT app_html MATCHES "save-image" OR NOT app_html MATCHES "setAppearance")
  message(FATAL_ERROR "Relocated embedded app omitted colors, saved views or PNG capture")
endif()
if(NOT app_html MATCHES "artifact-review-panel" OR NOT app_html MATCHES "validateArtifact" OR NOT app_html MATCHES "requireNative")
  message(FATAL_ERROR "Relocated MCP App omitted read-only artifact review or native-action guards")
endif()
if(NOT app_html MATCHES "motion_preview" OR NOT app_html MATCHES "motion_save" OR NOT app_html MATCHES "Save pose")
  message(FATAL_ERROR "Relocated MCP App omitted motion preview/save controls")
endif()
if(NOT app_html MATCHES "sequence-play" OR NOT app_html MATCHES "sequence-pause" OR NOT app_html MATCHES "sequence-seek" OR NOT app_html MATCHES "sequence-speed" OR NOT app_html MATCHES "sequence-loop" OR NOT app_html MATCHES "playSequence")
  message(FATAL_ERROR "Relocated MCP App omitted declarative playback controls")
endif()
if(NOT app_html MATCHES "motion-mechanism" OR NOT app_html MATCHES "Reused definitions share this pose")
  message(FATAL_ERROR "Relocated MCP App omitted composed mechanism controls")
endif()
if(NOT app_html MATCHES "Pinned from")
  message(FATAL_ERROR "Relocated MCP App omitted pinned-component provenance")
endif()
file(READ "${bundle}/share/agent-3d-cad/provenance.json" provenance)
string(SHA256 actual_app_hash "${app_html}")
string(JSON expected_app_hash GET "${provenance}" viewer_app_sha256)
if(NOT actual_app_hash STREQUAL expected_app_hash)
  message(FATAL_ERROR "Embedded MCP App differs from bundle provenance")
endif()
string(JSON count LENGTH "${provenance}" files)
if(count LESS 5)
  message(FATAL_ERROR "Incomplete bundle provenance")
endif()
message(STATUS "Relocated bundle passed create/edit/reopen/query/STEP/STL/drawings/BOM/balloons/MCP and embedded app-resource smoke with empty PATH")
