if(NOT DEFINED BUILD_DIR OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "BUILD_DIR and TEST_DIR are required")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
get_filename_component(TEST_DIR "${TEST_DIR}" ABSOLUTE)
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config Release --prefix staging
  WORKING_DIRECTORY "${TEST_DIR}"
  RESULT_VARIABLE status OUTPUT_VARIABLE installed ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Bundle install failed: ${installed}\n${diagnostics}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUNDLE_DIR=${TEST_DIR}/staging"
  "-DINSTALL_DIR=${TEST_DIR}/relocated bundles" "-DRESULT_FILE=${TEST_DIR}/install-result.json"
  -P "${CMAKE_CURRENT_LIST_DIR}/../packaging/install-local.cmake"
  RESULT_VARIABLE status OUTPUT_VARIABLE installed ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Verified local installation failed: ${installed}\n${diagnostics}")
endif()
file(READ "${TEST_DIR}/install-result.json" installation)
string(JSON bundle GET "${installation}" install_dir)
if(WIN32)
  set(suffix .exe)
endif()
set(CAD_EXE "${bundle}/bin/agent-3d-cad${suffix}")
set(SOURCE_DIR "${bundle}/share/agent-3d-cad")
if(NOT EXISTS "${SOURCE_DIR}/skills/native-cad/SKILL.md")
  message(FATAL_ERROR "Bundle is missing its native CAD workflow skill")
endif()
file(READ "${SOURCE_DIR}/provenance.json" provenance)
string(JSON hlr_patch GET "${provenance}" occt_modifications 0)
if(NOT hlr_patch STREQUAL "agentcad-hlr-midpoint-v2")
  message(FATAL_ERROR "Bundle must identify its reproducible OCCT midpoint optimization")
endif()
file(READ "${SOURCE_DIR}/notices/occt/agentcad-hlr-midpoint-v2.json" hlr_metadata)
string(JSON hlr_metadata_patch GET "${hlr_metadata}" modification)
string(JSON hlr_metadata_version GET "${hlr_metadata}" occt_version)
string(JSON hlr_metadata_format GET "${hlr_metadata}" format_version)
string(JSON hlr_sdk_hash GET "${provenance}" occt_hlr_sdk_sha256)
string(JSON hlr_binary_count LENGTH "${hlr_metadata}" binaries)
if(NOT hlr_metadata_patch STREQUAL hlr_patch OR NOT hlr_metadata_version STREQUAL "8.0.1"
    OR NOT hlr_metadata_format EQUAL 1 OR hlr_binary_count LESS 1)
  message(FATAL_ERROR "Bundle OCCT modification metadata is inconsistent")
endif()
set(hlr_sdk_recorded FALSE)
math(EXPR hlr_binary_last "${hlr_binary_count}-1")
foreach(index RANGE 0 ${hlr_binary_last})
  string(JSON recorded_hash GET "${hlr_metadata}" binaries ${index} sha256)
  if(recorded_hash STREQUAL hlr_sdk_hash)
    set(hlr_sdk_recorded TRUE)
  endif()
endforeach()
if(NOT hlr_sdk_recorded)
  message(FATAL_ERROR "Bundle provenance does not identify a binary from its patched SDK manifest")
endif()
foreach(source HLRBRep_Intersector.cxx HLRBRep_Intersector.hxx HLRBRep_Data.cxx HLRBRep_Data.hxx HLRBRep_Hider.cxx)
  if(NOT EXISTS "${SOURCE_DIR}/notices/occt/modified/${source}")
    message(FATAL_ERROR "Bundle is missing modified OCCT source: ${source}")
  endif()
endforeach()
set(TEST_DIR "${TEST_DIR}/workflow")
# Absolute service paths and direct worker spawn must work without SDK tooling
# on PATH or loader environment overrides. Windows retains SystemRoot for APIs.
set(ENV{PATH} "")
foreach(variable LD_LIBRARY_PATH DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH CASROOT CSF_SHMessage CSF_XSMessage CSF_STEPDefaults CSF_IGESDefaults CSF_StandardDefaults CSF_PluginDefaults CSF_XCAFDefaults)
  unset(ENV{${variable}})
endforeach()
execute_process(COMMAND "${CAD_EXE}" --version RESULT_VARIABLE status OUTPUT_VARIABLE version ERROR_VARIABLE logs)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Relocated bundle cannot start: ${logs}")
endif()
string(JSON kernel GET "${version}" kernel_version)
if(NOT kernel STREQUAL "8.0.1")
  message(FATAL_ERROR "Unexpected bundled kernel: ${kernel}")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/cli_smoke.cmake")
call_tool(cad_drawing "${SOURCE_DIR}/examples/plate.drawing.json")
string(JSON drawing_manifest GET "${reply}" path)
string(JSON drawing_count LENGTH "${reply}" artifacts)
if(NOT EXISTS "${drawing_manifest}" OR NOT drawing_count EQUAL 6)
  message(FATAL_ERROR "Relocated native drawing did not publish PDF, SVG and four DXFs")
endif()
foreach(index RANGE 0 5)
  string(JSON drawing_file GET "${reply}" artifacts ${index} path)
  if(NOT EXISTS "${drawing_file}")
    message(FATAL_ERROR "Relocated drawing artifact missing: ${drawing_file}")
  endif()
endforeach()
call_tool(cad_drawing "${SOURCE_DIR}/examples/plate-section.drawing.json")
string(JSON section_layout GET "${reply}" layout)
string(JSON section_count LENGTH "${reply}" artifacts)
if(NOT section_layout STREQUAL "third_angle" OR NOT section_count EQUAL 6)
  message(FATAL_ERROR "Relocated section drawing did not preserve its standard layout and artifacts")
endif()
set(found_hatching FALSE)
foreach(index RANGE 0 5)
  string(JSON section_format GET "${reply}" artifacts ${index} format)
  if(section_format STREQUAL "svg")
    string(JSON section_file GET "${reply}" artifacts ${index} path)
    file(READ "${section_file}" section_svg)
    if(section_svg MATCHES "data-layer=\"HATCH\"")
      set(found_hatching TRUE)
    endif()
  endif()
endforeach()
if(NOT found_hatching)
  message(FATAL_ERROR "Relocated section drawing omitted requested material hatching")
endif()
call_tool(cad_create "${SOURCE_DIR}/examples/angular-plate.create.json")
call_tool(cad_drawing "${SOURCE_DIR}/examples/angular-plate.drawing.json")
string(JSON angle GET "${reply}" dimensions 0 value_deg)
string(JSON angle_lower GET "${reply}" dimensions 0 lower_limit_deg)
string(JSON angle_label GET "${reply}" dimensions 0 label)
string(JSON bore_lower GET "${reply}" dimensions 1 lower_limit_mm)
if(NOT angle EQUAL 45 OR NOT angle_lower EQUAL 44.75 OR
   NOT angle_label STREQUAL "45 +/-0.25 deg" OR NOT bore_lower EQUAL 7.98)
  message(FATAL_ERROR "Relocated drawing did not preserve angular dimensions and explicit tolerances")
endif()
file(GLOB cache_entries "${TEST_DIR}/workspace/.cache/*.json")
list(LENGTH cache_entries cache_count)
if(cache_count LESS 5)
  message(FATAL_ERROR "Relocated service did not cache exact geometry and projections")
endif()
set(cold_drawing "${reply}")
call_tool(cad_drawing "${SOURCE_DIR}/examples/angular-plate.drawing.json")
string(JSON artifact_count LENGTH "${reply}" artifacts)
math(EXPR last_artifact "${artifact_count}-1")
foreach(index RANGE 0 ${last_artifact})
  string(JSON cold_file GET "${cold_drawing}" artifacts ${index} path)
  string(JSON warm_file GET "${reply}" artifacts ${index} path)
  file(SHA256 "${cold_file}" cold_hash)
  file(SHA256 "${warm_file}" warm_hash)
  if(NOT cold_hash STREQUAL warm_hash)
    message(FATAL_ERROR "Cached relocated drawing changed artifact contents")
  endif()
endforeach()
call_tool(cad_create "${SOURCE_DIR}/examples/assembly.create.json")
string(JSON assembly_parts LENGTH "${reply}" summary assembly parts)
if(assembly_parts LESS 2)
  message(FATAL_ERROR "Relocated assembly omitted its editable part inventory")
endif()
call_tool(cad_drawing "${SOURCE_DIR}/examples/assembly.drawing.json")
string(JSON assembly_artifacts LENGTH "${reply}" artifacts)
math(EXPR last_assembly_artifact "${assembly_artifacts}-1")
set(exploded_label FALSE)
foreach(index RANGE 0 ${last_assembly_artifact})
  string(JSON artifact_format GET "${reply}" artifacts ${index} format)
  if(artifact_format STREQUAL "svg")
    string(JSON artifact_file GET "${reply}" artifacts ${index} path)
    file(READ "${artifact_file}" assembly_svg)
    if(assembly_svg MATCHES "EXPLODED")
      set(exploded_label TRUE)
    endif()
  endif()
endforeach()
if(NOT exploded_label)
  message(FATAL_ERROR "Relocated exploded assembly drawing omitted its label")
endif()
# BOMs are generated from saved editable intent by the relocated service, with
# JSON/CSV usable independently of the application or developer tooling.
file(WRITE "${TEST_DIR}/bom.json" [=[{"document_id":"spacer_assembly","revision":1}]=])
call_tool(cad_bom "${TEST_DIR}/bom.json")
set(original_bom "${reply}")
string(JSON bom_quantity GET "${reply}" bom total_quantity)
string(JSON bom_items LENGTH "${reply}" bom items)
string(JSON plate_quantity GET "${reply}" bom items 0 quantity)
string(JSON spacer_quantity GET "${reply}" bom items 1 quantity)
string(JSON bom_files LENGTH "${reply}" artifacts)
if(NOT bom_quantity EQUAL 4 OR NOT bom_items EQUAL 2 OR NOT plate_quantity EQUAL 2 OR
   NOT spacer_quantity EQUAL 2 OR NOT bom_files EQUAL 2)
  message(FATAL_ERROR "Relocated BOM did not group repeated plate/spacer instances")
endif()
foreach(index RANGE 0 1)
  string(JSON artifact_file GET "${reply}" artifacts ${index} path)
  string(JSON artifact_bytes GET "${reply}" artifacts ${index} bytes)
  file(SIZE "${artifact_file}" actual_bytes)
  if(NOT actual_bytes EQUAL artifact_bytes OR actual_bytes LESS 1)
    message(FATAL_ERROR "Relocated BOM artifact does not match declared size")
  endif()
endforeach()
call_tool(cad_drawing "${SOURCE_DIR}/examples/assembly-bom.drawing.json")
string(JSON balloons LENGTH "${reply}" balloons)
string(JSON base_item GET "${reply}" balloons 0 item_number)
string(JSON spacer_item GET "${reply}" balloons 1 item_number)
string(JSON bom_artifacts LENGTH "${reply}" artifacts)
if(NOT balloons EQUAL 4 OR NOT base_item EQUAL 1 OR NOT spacer_item EQUAL 2 OR NOT bom_artifacts EQUAL 6)
  message(FATAL_ERROR "Relocated BOM drawing omitted source-matched balloons or sidecars")
endif()
set(found_bom_json FALSE)
set(found_bom_csv FALSE)
set(found_bom_table FALSE)
set(found_bom_balloons FALSE)
foreach(index RANGE 0 5)
  string(JSON artifact_format GET "${reply}" artifacts ${index} format)
  string(JSON artifact_file GET "${reply}" artifacts ${index} path)
  file(READ "${artifact_file}" artifact_content)
  if(artifact_format STREQUAL "json")
    string(JSON sidecar_quantity GET "${artifact_content}" bom total_quantity)
    string(JSON sidecar_revision GET "${artifact_content}" revision)
    if(NOT sidecar_quantity EQUAL 4 OR NOT sidecar_revision EQUAL 1)
      message(FATAL_ERROR "Relocated drawing BOM JSON lost its inventory or revision")
    endif()
    set(found_bom_json TRUE)
  elseif(artifact_format STREQUAL "csv")
    if(NOT artifact_content MATCHES "item_number" OR NOT artifact_content MATCHES "base;cover")
      message(FATAL_ERROR "Relocated drawing BOM CSV lost its grouped part identities")
    endif()
    set(found_bom_csv TRUE)
  elseif(artifact_format STREQUAL "svg")
    if(artifact_content MATCHES "BILL OF MATERIALS")
      set(found_bom_table TRUE)
    endif()
    if(artifact_content MATCHES "data-layer=\"BALLOONS\"")
      set(found_bom_balloons TRUE)
    endif()
  endif()
endforeach()
if(NOT found_bom_json OR NOT found_bom_csv OR NOT found_bom_table OR NOT found_bom_balloons)
  message(FATAL_ERROR "Relocated drawing omitted BOM sidecars, rendered table or numbered balloons")
endif()
file(WRITE "${TEST_DIR}/bom-edit.json" [=[{"document_id":"spacer_assembly","expected_revision":1,"operations":[{"op":"set_bom_item","assembly_id":"assembly","item":{"input":"plate","item_number":9,"description":"Plate, \"checked\""}}]}]=])
call_tool(cad_apply "${TEST_DIR}/bom-edit.json")
file(WRITE "${TEST_DIR}/bom-current.json" [=[{"document_id":"spacer_assembly","revision":2}]=])
call_tool(cad_bom "${TEST_DIR}/bom-current.json")
string(JSON edited_item GET "${reply}" bom items 1 item_number)
string(JSON edited_description GET "${reply}" bom items 1 description)
if(NOT edited_item EQUAL 9 OR NOT edited_description STREQUAL "Plate, \"checked\"")
  message(FATAL_ERROR "Relocated semantic BOM edit did not retain explicit metadata")
endif()
foreach(index RANGE 0 1)
  string(JSON artifact_format GET "${reply}" artifacts ${index} format)
  if(artifact_format STREQUAL "csv")
    string(JSON artifact_file GET "${reply}" artifacts ${index} path)
    file(READ "${artifact_file}" edited_csv)
    string(FIND "${edited_csv}" "\"Plate, \"\"checked\"\"\"" quoted_description)
    if(quoted_description EQUAL -1)
      message(FATAL_ERROR "Relocated CSV did not quote commas and embedded quotes")
    endif()
  endif()
endforeach()
call_tool(cad_bom "${TEST_DIR}/bom.json")
string(JSON original_inventory GET "${original_bom}" bom)
string(JSON historical_inventory GET "${reply}" bom)
if(NOT original_inventory STREQUAL historical_inventory)
  message(FATAL_ERROR "Metadata edit changed historical BOM output")
endif()
file(WRITE "${TEST_DIR}/bom-remove.json" [=[{"document_id":"spacer_assembly","expected_revision":2,"operations":[{"op":"remove_bom_item","assembly_id":"assembly","input":"plate"}]}]=])
call_tool(cad_apply "${TEST_DIR}/bom-remove.json")
file(WRITE "${TEST_DIR}/bom-restored.json" [=[{"document_id":"spacer_assembly","revision":3}]=])
call_tool(cad_bom "${TEST_DIR}/bom-restored.json")
string(JSON restored_inventory GET "${reply}" bom)
if(NOT original_inventory STREQUAL restored_inventory)
  message(FATAL_ERROR "Removing metadata did not restore automatic BOM groups")
endif()
foreach(example curved-plate curved-pipe)
  call_tool(cad_create "${SOURCE_DIR}/examples/${example}.create.json")
  string(JSON curve_document GET "${reply}" document_id)
  file(WRITE "${TEST_DIR}/curve-export.json" "{\"document_id\":\"${curve_document}\",\"revision\":1,\"format\":\"step\"}")
  call_tool(cad_export "${TEST_DIR}/curve-export.json")
  string(JSON curve_path GET "${reply}" path)
  if(NOT EXISTS "${curve_path}")
    message(FATAL_ERROR "Relocated curved-model export is missing")
  endif()
endforeach()
call_tool(cad_create "${SOURCE_DIR}/examples/articulated-arm.create.json")
call_tool(cad_robot_export "${SOURCE_DIR}/examples/articulated-arm.robot.json")
string(JSON robot_directory GET "${reply}" directory)
foreach(artifact model.urdf model.srdf robot.json manifest.json meshes/mesh_0.stl)
  if(NOT EXISTS "${robot_directory}/${artifact}")
    message(FATAL_ERROR "Relocated native robot export omitted ${artifact}")
  endif()
endforeach()
file(READ "${robot_directory}/model.urdf" robot_xml)
if(NOT robot_xml MATCHES "mate_spindle_joint_angle" OR NOT robot_xml MATCHES "mate_spindle_joint_travel" OR NOT robot_xml MATCHES "mimic")
  message(FATAL_ERROR "Relocated robot export lost cylindrical motion or coupling")
endif()
file(READ "${SOURCE_DIR}/examples/articulated-arm.robot.json" robot_input)
string(JSON robot_input SET "${robot_input}" robot format "\"sdf\"")
set(robot_inertials "[]")
set(inertial_index 0)
foreach(link part_ground part_lever part_slide part_spindle carrier_spindle_joint)
  # Explicit synthetic test data, not physical properties inferred from CAD.
  string(JSON robot_inertials SET "${robot_inertials}" ${inertial_index}
    "{\"link\":\"${link}\",\"mass_kg\":0.1,\"center_of_mass_m\":[0,0,0],\"inertia_kg_m2\":[0.00002,0.00003,0.00004,0,0,0]}")
  math(EXPR inertial_index "${inertial_index}+1")
endforeach()
string(JSON robot_input SET "${robot_input}" robot inertials "${robot_inertials}")
file(WRITE "${TEST_DIR}/robot-sdf.json" "${robot_input}")
call_tool(cad_robot_export "${TEST_DIR}/robot-sdf.json")
string(JSON robot_sdf GET "${reply}" path)
file(READ "${robot_sdf}" robot_sdf_xml)
if(NOT robot_sdf_xml MATCHES "<sdf version=\"1.12\">" OR NOT robot_sdf_xml MATCHES "<inertial>")
  message(FATAL_ERROR "Relocated SDF export lost its version or physical data")
endif()
file(WRITE "${TEST_DIR}/motion-preview.json" [=[{"document_id":"articulated_arm","expected_revision":1,"kind":"mesh","operations":[{"op":"apply_pose","assembly_id":"mechanism","pose_id":"extended"}]}]=])
call_tool(cad_preview "${TEST_DIR}/motion-preview.json")
string(JSON is_draft GET "${reply}" draft)
string(JSON angle GET "${reply}" summary assembly motion dofs 0 value)
string(JSON feed GET "${reply}" summary assembly motion dofs 1 value)
if(NOT is_draft OR NOT angle EQUAL 90 OR NOT feed EQUAL 9)
  message(FATAL_ERROR "Relocated motion preview lost its joint or coupling state")
endif()
file(WRITE "${TEST_DIR}/motion-save.json" [=[{"document_id":"articulated_arm","expected_revision":1,"operations":[{"op":"apply_pose","assembly_id":"mechanism","pose_id":"extended"}]}]=])
call_tool(cad_apply "${TEST_DIR}/motion-save.json")
string(JSON motion_revision GET "${reply}" revision)
if(NOT motion_revision EQUAL 2)
  message(FATAL_ERROR "Relocated pose edit did not commit a revision")
endif()
file(WRITE "${TEST_DIR}/motion-history.json" [=[{"document_id":"articulated_arm","revision":1}]=])
call_tool(cad_read "${TEST_DIR}/motion-history.json")
string(JSON historic_angle GET "${reply}" model parameters arm_angle)
if(NOT historic_angle EQUAL 30)
  message(FATAL_ERROR "Relocated pose save changed its historical source")
endif()
file(WRITE "${TEST_DIR}/motion-export.json" [=[{"document_id":"articulated_arm","revision":2,"format":"stl"}]=])
call_tool(cad_export "${TEST_DIR}/motion-export.json")
set(app_requests "${TEST_DIR}/app-resource.jsonl")
file(WRITE "${app_requests}" [=[{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{"extensions":{"io.modelcontextprotocol/ui":{"mimeTypes":["text/html;profile=mcp-app"]}}},"clientInfo":{"name":"bundle-app-smoke","version":"1"}}}
{"jsonrpc":"2.0","method":"notifications/initialized"}
{"jsonrpc":"2.0","id":2,"method":"resources/read","params":{"uri":"ui://agent-3d-cad/viewer.html"}}
]=])
execute_process(COMMAND "${CAD_EXE}" serve --workspace "${TEST_DIR}/workspace"
  INPUT_FILE "${app_requests}" OUTPUT_VARIABLE app_responses ERROR_VARIABLE app_logs RESULT_VARIABLE app_status)
if(NOT app_status EQUAL 0)
  message(FATAL_ERROR "Relocated app resource request failed: ${app_logs}")
endif()
string(FIND "${app_responses}" "\n" app_first_newline)
math(EXPR app_offset "${app_first_newline}+1")
string(SUBSTRING "${app_responses}" ${app_offset} -1 app_reply)
string(JSON app_mime GET "${app_reply}" result contents 0 mimeType)
string(JSON app_html GET "${app_reply}" result contents 0 text)
if(NOT app_mime STREQUAL "text/html;profile=mcp-app" OR NOT app_html MATCHES "CadBridge" OR NOT app_html MATCHES "<canvas")
  message(FATAL_ERROR "Relocated bundle did not serve its embedded MCP App")
endif()
if(NOT app_html MATCHES "isolatePart" OR NOT app_html MATCHES "hidden_part_ids" OR NOT app_html MATCHES "Show all")
  message(FATAL_ERROR "Relocated MCP App omitted assembly visibility controls")
endif()
if(NOT app_html MATCHES "motion_preview" OR NOT app_html MATCHES "motion_save" OR NOT app_html MATCHES "Save pose")
  message(FATAL_ERROR "Relocated MCP App omitted motion preview/save controls")
endif()
file(READ "${bundle}/share/agent-3d-cad/provenance.json" provenance)
string(SHA256 actual_app_hash "${app_html}")
string(JSON expected_app_hash GET "${provenance}" viewer_app_sha256)
if(NOT actual_app_hash STREQUAL expected_app_hash)
  message(FATAL_ERROR "Embedded MCP App differs from bundle provenance")
endif()
string(JSON count LENGTH "${provenance}" files)
if(count LESS 5)
  message(FATAL_ERROR "Incomplete bundle provenance")
endif()
message(STATUS "Relocated bundle passed create/edit/reopen/query/STEP/STL/drawings/BOM/balloons/MCP and embedded app-resource smoke with empty PATH")
