if(NOT DEFINED BUILD_DIR OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "BUILD_DIR and TEST_DIR are required")
endif()
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config Release --prefix "${TEST_DIR}/staging"
  RESULT_VARIABLE status OUTPUT_VARIABLE installed ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Bundle install failed: ${installed}\n${diagnostics}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUNDLE_DIR=${TEST_DIR}/staging"
  "-DINSTALL_DIR=${TEST_DIR}/relocated bundles" "-DRESULT_FILE=${TEST_DIR}/install-result.json"
  -P "${CMAKE_CURRENT_LIST_DIR}/../packaging/install-local.cmake"
  RESULT_VARIABLE status OUTPUT_VARIABLE installed ERROR_VARIABLE diagnostics)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Verified local installation failed: ${installed}\n${diagnostics}")
endif()
file(READ "${TEST_DIR}/install-result.json" installation)
string(JSON bundle GET "${installation}" install_dir)
if(WIN32)
  set(suffix .exe)
endif()
set(CAD_EXE "${bundle}/bin/agent-3d-cad${suffix}")
set(SOURCE_DIR "${bundle}/share/agent-3d-cad")
if(NOT EXISTS "${SOURCE_DIR}/skills/native-cad/SKILL.md")
  message(FATAL_ERROR "Bundle is missing its native CAD workflow skill")
endif()
set(TEST_DIR "${TEST_DIR}/workflow")
# Absolute service paths and direct worker spawn must work without SDK tooling
# on PATH or loader environment overrides. Windows retains SystemRoot for APIs.
set(ENV{PATH} "")
foreach(variable LD_LIBRARY_PATH DYLD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH CASROOT CSF_SHMessage CSF_XSMessage CSF_STEPDefaults CSF_IGESDefaults CSF_StandardDefaults CSF_PluginDefaults CSF_XCAFDefaults)
  unset(ENV{${variable}})
endforeach()
execute_process(COMMAND "${CAD_EXE}" --version RESULT_VARIABLE status OUTPUT_VARIABLE version ERROR_VARIABLE logs)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Relocated bundle cannot start: ${logs}")
endif()
string(JSON kernel GET "${version}" kernel_version)
if(NOT kernel STREQUAL "8.0.1")
  message(FATAL_ERROR "Unexpected bundled kernel: ${kernel}")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/cli_smoke.cmake")
call_tool(cad_drawing "${SOURCE_DIR}/examples/plate.drawing.json")
string(JSON drawing_manifest GET "${reply}" path)
string(JSON drawing_count LENGTH "${reply}" artifacts)
if(NOT EXISTS "${drawing_manifest}" OR NOT drawing_count EQUAL 6)
  message(FATAL_ERROR "Relocated native drawing did not publish PDF, SVG and four DXFs")
endif()
foreach(index RANGE 0 5)
  string(JSON drawing_file GET "${reply}" artifacts ${index} path)
  if(NOT EXISTS "${drawing_file}")
    message(FATAL_ERROR "Relocated drawing artifact missing: ${drawing_file}")
  endif()
endforeach()
set(app_requests "${TEST_DIR}/app-resource.jsonl")
file(WRITE "${app_requests}" [=[{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{"extensions":{"io.modelcontextprotocol/ui":{"mimeTypes":["text/html;profile=mcp-app"]}}},"clientInfo":{"name":"bundle-app-smoke","version":"1"}}}
{"jsonrpc":"2.0","method":"notifications/initialized"}
{"jsonrpc":"2.0","id":2,"method":"resources/read","params":{"uri":"ui://agent-3d-cad/viewer.html"}}
]=])
execute_process(COMMAND "${CAD_EXE}" serve --workspace "${TEST_DIR}/workspace"
  INPUT_FILE "${app_requests}" OUTPUT_VARIABLE app_responses ERROR_VARIABLE app_logs RESULT_VARIABLE app_status)
if(NOT app_status EQUAL 0)
  message(FATAL_ERROR "Relocated app resource request failed: ${app_logs}")
endif()
string(FIND "${app_responses}" "\n" app_first_newline)
math(EXPR app_offset "${app_first_newline}+1")
string(SUBSTRING "${app_responses}" ${app_offset} -1 app_reply)
string(JSON app_mime GET "${app_reply}" result contents 0 mimeType)
string(JSON app_html GET "${app_reply}" result contents 0 text)
if(NOT app_mime STREQUAL "text/html;profile=mcp-app" OR NOT app_html MATCHES "CadBridge" OR NOT app_html MATCHES "<canvas")
  message(FATAL_ERROR "Relocated bundle did not serve its embedded MCP App")
endif()
file(READ "${bundle}/share/agent-3d-cad/provenance.json" provenance)
string(SHA256 actual_app_hash "${app_html}")
string(JSON expected_app_hash GET "${provenance}" viewer_app_sha256)
if(NOT actual_app_hash STREQUAL expected_app_hash)
  message(FATAL_ERROR "Embedded MCP App differs from bundle provenance")
endif()
string(JSON count LENGTH "${provenance}" files)
if(count LESS 5)
  message(FATAL_ERROR "Incomplete bundle provenance")
endif()
message(STATUS "Relocated bundle passed create/edit/reopen/query/STEP/STL/drawings/MCP and embedded app-resource smoke with empty PATH")
