file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
function(call_tool tool input)
  execute_process(COMMAND "${CAD_EXE}" call "${tool}" --workspace "${TEST_DIR}/workspace" --input "${input}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE logs TIMEOUT 30)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${tool} failed: ${logs}")
  endif()
  string(JSON kind TYPE "${output}")
  if(NOT kind STREQUAL "OBJECT")
    message(FATAL_ERROR "Non-JSON stdout: ${output}")
  endif()
  set(reply "${output}" PARENT_SCOPE)
endfunction()
call_tool(cad_create "${SOURCE_DIR}/examples/plate.create.json")
call_tool(cad_apply "${SOURCE_DIR}/examples/plate.edit.json")
call_tool(cad_query "${SOURCE_DIR}/examples/plate.query.json")
string(JSON height GET "${reply}" summary bounds_mm max 2)
if(height LESS 7.9999 OR height GREATER 8.0001)
  message(FATAL_ERROR "Parameter edit did not rebuild plate height: ${height}")
endif()
call_tool(cad_export "${SOURCE_DIR}/examples/plate.export.json")
string(JSON artifact GET "${reply}" path)
if(NOT EXISTS "${artifact}")
  message(FATAL_ERROR "Export missing")
endif()
file(WRITE "${TEST_DIR}/mcp.jsonl" [=[
{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"smoke","version":"1"}}}
{"jsonrpc":"2.0","method":"notifications/initialized"}
{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"cad_export","arguments":{"document_id":"plate","revision":2,"format":"step"}}}
{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"cad_export","arguments":{"document_id":"plate","revision":1,"format":"stl"}}}
]=])
execute_process(COMMAND "${CAD_EXE}" serve --workspace "${TEST_DIR}/workspace"
  INPUT_FILE "${TEST_DIR}/mcp.jsonl" OUTPUT_VARIABLE replies ERROR_VARIABLE logs RESULT_VARIABLE status TIMEOUT 30)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "MCP process failed: ${logs}")
endif()
string(STRIP "${replies}" replies)
string(REPLACE ";" "\\;" replies "${replies}")
string(REPLACE "\n" ";" lines "${replies}")
list(LENGTH lines length)
if(NOT length EQUAL 3)
  message(FATAL_ERROR "Expected exactly 3 protocol messages on stdout: ${replies}")
endif()
foreach(line IN LISTS lines)
  string(JSON id GET "${line}" id)
  string(JSON result_type TYPE "${line}" result)
  if(id GREATER 1)
    string(JSON failed GET "${line}" result isError)
    if(failed)
      message(FATAL_ERROR "MCP export failed: ${line}")
    endif()
  endif()
endforeach()
# An existing folder uses the same transport through Claude's optional setting.
execute_process(COMMAND "${CAD_EXE}" serve --default-workspace --workspace-setting "${TEST_DIR}/workspace"
  INPUT_FILE "${TEST_DIR}/mcp.jsonl" OUTPUT_VARIABLE setting_replies ERROR_VARIABLE logs RESULT_VARIABLE status TIMEOUT 30)
# Replies contain asynchronous timestamps; validate correlation and errors.
string(STRIP "${setting_replies}" setting_replies)
string(REPLACE ";" "\\;" setting_replies "${setting_replies}")
string(REPLACE "\n" ";" setting_lines "${setting_replies}")
list(LENGTH setting_lines setting_count)
if(NOT status EQUAL 0 OR NOT setting_count EQUAL 3)
  message(FATAL_ERROR "Optional existing project setting failed: ${logs}")
endif()
foreach(line IN LISTS setting_lines)
  string(JSON id GET "${line}" id)
  if(id GREATER 1)
    string(JSON failed GET "${line}" result isError)
    if(failed)
      message(FATAL_ERROR "Optional project setting export failed: ${line}")
    endif()
  endif()
endforeach()
# A host that fails to expand its setting must never create a relative folder.
execute_process(COMMAND "${CAD_EXE}" serve --default-workspace --workspace "\${DOCUMENTS}/Agent CAD"
  WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE unexpected ERROR_VARIABLE logs TIMEOUT 10)
if(status EQUAL 0 OR NOT unexpected STREQUAL "" OR EXISTS "${TEST_DIR}/\${DOCUMENTS}")
  message(FATAL_ERROR "Unexpanded plugin folder must fail without creating storage")
endif()
execute_process(COMMAND "${CAD_EXE}" serve --default-workspace --workspace "" --workspace "${TEST_DIR}/workspace"
  RESULT_VARIABLE status OUTPUT_VARIABLE unexpected ERROR_VARIABLE logs TIMEOUT 10)
if(status EQUAL 0 OR NOT unexpected STREQUAL "")
  message(FATAL_ERROR "Repeated empty workspace must fail without opening storage")
endif()

# The plugin startup flag accepts an explicit isolated/older workspace. The
# test never changes HOME or writes to the real user's default project folder.
execute_process(COMMAND "${CAD_EXE}" serve --default-workspace --workspace "${TEST_DIR}/workspace"
  INPUT_FILE "${TEST_DIR}/mcp.jsonl" OUTPUT_VARIABLE plugin_replies ERROR_VARIABLE logs RESULT_VARIABLE status TIMEOUT 30)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Plugin startup failed: ${logs}")
endif()
string(STRIP "${plugin_replies}" plugin_replies)
string(REPLACE ";" "\\;" plugin_replies "${plugin_replies}")
string(REPLACE "\n" ";" plugin_lines "${plugin_replies}")
list(LENGTH plugin_lines plugin_count)
if(NOT plugin_count EQUAL 3)
  message(FATAL_ERROR "Plugin startup did not return three JSON messages")
endif()
foreach(line IN LISTS plugin_lines)
  string(JSON id GET "${line}" id)
  if(id GREATER 1)
    string(JSON failed GET "${line}" result isError)
    if(failed)
      message(FATAL_ERROR "Plugin startup export failed: ${line}")
    endif()
  endif()
endforeach()
foreach(args IN ITEMS "call;cad_list;--default-workspace" "serve;--default-workspace;--default-workspace" "serve;--workspace-setting;\${user_config.workspace}")
  execute_process(COMMAND "${CAD_EXE}" ${args} RESULT_VARIABLE status OUTPUT_VARIABLE unexpected ERROR_VARIABLE logs TIMEOUT 10)
  if(status EQUAL 0 OR NOT unexpected STREQUAL "")
    message(FATAL_ERROR "Invalid plugin startup flags must fail without stdout: ${args}")
  endif()
endforeach()
