file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
function(call_tool tool input)
  execute_process(COMMAND "${CAD_EXE}" call "${tool}" --workspace "${TEST_DIR}/workspace" --input "${input}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE logs TIMEOUT 30)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${tool} failed: ${logs}")
  endif()
  string(JSON kind TYPE "${output}")
  if(NOT kind STREQUAL "OBJECT")
    message(FATAL_ERROR "Non-JSON stdout: ${output}")
  endif()
  set(reply "${output}" PARENT_SCOPE)
endfunction()
call_tool(cad_create "${SOURCE_DIR}/examples/plate.create.json")
call_tool(cad_apply "${SOURCE_DIR}/examples/plate.edit.json")
call_tool(cad_query "${SOURCE_DIR}/examples/plate.query.json")
string(JSON height GET "${reply}" summary bounds_mm max 2)
if(height LESS 7.9999 OR height GREATER 8.0001)
  message(FATAL_ERROR "Parameter edit did not rebuild plate height: ${height}")
endif()
call_tool(cad_export "${SOURCE_DIR}/examples/plate.export.json")
string(JSON artifact GET "${reply}" path)
if(NOT EXISTS "${artifact}")
  message(FATAL_ERROR "Export missing")
endif()
file(WRITE "${TEST_DIR}/mcp.jsonl" [=[
{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"smoke","version":"1"}}}
{"jsonrpc":"2.0","method":"notifications/initialized"}
{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"cad_export","arguments":{"document_id":"plate","revision":2,"format":"step"}}}
{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"cad_export","arguments":{"document_id":"plate","revision":1,"format":"stl"}}}
]=])
execute_process(COMMAND "${CAD_EXE}" serve --workspace "${TEST_DIR}/workspace"
  INPUT_FILE "${TEST_DIR}/mcp.jsonl" OUTPUT_VARIABLE replies ERROR_VARIABLE logs RESULT_VARIABLE status TIMEOUT 30)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "MCP process failed: ${logs}")
endif()
string(STRIP "${replies}" replies)
string(REPLACE ";" "\\;" replies "${replies}")
string(REPLACE "\n" ";" lines "${replies}")
list(LENGTH lines length)
if(NOT length EQUAL 3)
  message(FATAL_ERROR "Expected exactly 3 protocol messages on stdout: ${replies}")
endif()
foreach(line IN LISTS lines)
  string(JSON id GET "${line}" id)
  string(JSON result_type TYPE "${line}" result)
  if(id GREATER 1)
    string(JSON failed GET "${line}" result isError)
    if(failed)
      message(FATAL_ERROR "MCP export failed: ${line}")
    endif()
  endif()
endforeach()
