if(NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "SOURCE_DIR and TEST_DIR are required")
endif()
file(REMOVE_RECURSE "${TEST_DIR}")
foreach(style IN ITEMS lf crlf)
  set(fixture "${TEST_DIR}/${style}")
  file(MAKE_DIRECTORY "${fixture}/source/web")
  foreach(asset IN ITEMS viewer.html styles.css bridge.js renderer.js state.js app.js)
    file(READ "${SOURCE_DIR}/web/${asset}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    if(style STREQUAL "crlf")
      set(newlines CRLF)
    else()
      set(newlines LF)
    endif()
    string(LENGTH "${content}" length)
    math(EXPR write_length "${length}-1")
    string(SUBSTRING "${content}" ${write_length} 1 last_byte)
    if(NOT last_byte STREQUAL "\n")
      message(FATAL_ERROR "Reviewed asset must end with LF: ${asset}")
    endif()
    string(SUBSTRING "${content}" 0 ${write_length} write_content)
    file(CONFIGURE OUTPUT "${fixture}/source/web/${asset}"
      CONTENT "@write_content@" @ONLY NEWLINE_STYLE "${newlines}")
    file(READ "${fixture}/source/web/${asset}" raw HEX)
    string(FIND "${raw}" "0d0a" crlf_position)
    if(style STREQUAL "crlf" AND crlf_position LESS 0)
      message(FATAL_ERROR "CRLF fixture has no physical CRLF bytes: ${asset}")
    elseif(style STREQUAL "lf" AND NOT crlf_position EQUAL -1)
      message(FATAL_ERROR "LF fixture contains physical CRLF bytes: ${asset}")
    endif()
  endforeach()
  file(WRITE "${fixture}/source/CMakeLists.txt"
    "cmake_minimum_required(VERSION 3.24)\nproject(viewer_embed_fixture LANGUAGES NONE)\ninclude([==[${SOURCE_DIR}/cmake/EmbedViewerApp.cmake]==])\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${fixture}/source" -B "${fixture}/build"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${style} asset fixture failed: ${output}\n${errors}")
  endif()
  # Text-mode file(READ) normalizes newlines and can mask a bad generated file.
  file(READ "${fixture}/build/generated/viewer.html" raw HEX)
  string(FIND "${raw}" "0d0a" crlf_position)
  if(NOT crlf_position EQUAL -1)
    message(FATAL_ERROR "Embedded ${style} assets still contain CRLF bytes")
  endif()
  file(READ "${fixture}/source/web/viewer.html" expected)
  foreach(asset IN ITEMS styles bridge renderer state app)
    if(asset STREQUAL "styles")
      set(extension css)
    else()
      set(extension js)
    endif()
    file(READ "${fixture}/source/web/${asset}.${extension}" content)
    string(TOUPPER "${asset}" token)
    string(REPLACE "@VIEWER_${token}@" "${content}" expected "${expected}")
  endforeach()
  string(REPLACE "\r\n" "\n" expected "${expected}")
  string(HEX "${expected}" expected_hex)
  if(NOT raw STREQUAL expected_hex)
    message(FATAL_ERROR "Generated HTML differs from reviewed ${style} assets, including final newline bytes")
  endif()
  file(SHA256 "${fixture}/build/generated/viewer.html" ${style}_html_hash)
  file(SHA256 "${fixture}/build/generated/viewer_app.cpp" ${style}_cpp_hash)
endforeach()
if(NOT lf_html_hash STREQUAL crlf_html_hash OR NOT lf_cpp_hash STREQUAL crlf_cpp_hash)
  message(FATAL_ERROR "LF and CRLF checkouts do not produce identical embedded UTF-8 assets")
endif()
message(STATUS "LF/CRLF assets produce identical canonical HTML and C++ byte initializers")
