cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED TEST_DIR OR NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "TEST_DIR and SOURCE_DIR required")
endif()
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
set(installer "${SOURCE_DIR}/packaging/install-local.cmake")
set(bundle "${TEST_DIR}/bundle with spaces")
set(destination "${TEST_DIR}/installed versions")
set(manifest_path "share/agent-3d-cad/provenance.json")
set(result_path "${TEST_DIR}/result.json")
if(WIN32)
  set(executable "bin/agent-3d-cad.exe")
  set(system Windows)
else()
  set(executable "bin/agent-3d-cad")
  set(system "${CMAKE_HOST_SYSTEM_NAME}")
endif()
file(MAKE_DIRECTORY "${bundle}/bin" "${bundle}/lib" "${bundle}/share/agent-3d-cad")
file(WRITE "${bundle}/${executable}" "#!/bin/sh\nexit 0\n")
file(CHMOD "${bundle}/${executable}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
file(WRITE "${bundle}/lib/runtime.bin" "native library fixture\n")
file(WRITE "${bundle}/share/agent-3d-cad/guide.txt" "Documentation included in full inventory.\n")
if(NOT WIN32)
  file(CREATE_LINK runtime.bin "${bundle}/lib/runtime-link.bin" SYMBOLIC)
endif()
file(GLOB_RECURSE files RELATIVE "${bundle}" "${bundle}/bin/*" "${bundle}/lib/*" "${bundle}/share/*")
set(manifest "{\"format_version\":1,\"project_version\":\"0.1.0\",\"system\":\"${system}\",\"architecture\":\"fixture\",\"files\":[]}")
set(index 0)
foreach(path IN LISTS files)
  file(SHA256 "${bundle}/${path}" hash)
  string(JSON manifest SET "${manifest}" files ${index} "{\"path\":\"${path}\",\"sha256\":\"${hash}\"}")
  math(EXPR index "${index}+1")
endforeach()
file(WRITE "${bundle}/${manifest_path}" "${manifest}")
file(SHA256 "${bundle}/${manifest_path}" manifest_hash)
set(checks 0)
function(run_install expected label)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUNDLE_DIR=${bundle}" "-DINSTALL_DIR=${destination}"
    "-DRESULT_FILE=${result_path}" ${ARGN} -P "${installer}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected STREQUAL "success" AND NOT status EQUAL 0)
    message(FATAL_ERROR "${label} failed: ${output}\n${error}")
  elseif(NOT expected STREQUAL "success")
    if(status EQUAL 0 OR NOT error MATCHES "${expected}")
      message(FATAL_ERROR "${label} should fail with '${expected}': ${output}\n${error}")
    endif()
  endif()
  math(EXPR next "${checks}+1")
  set(checks ${next} PARENT_SCOPE)
endfunction()

run_install(success "initial install" "-DEXPECTED_PROVENANCE_SHA256=${manifest_hash}")
file(READ "${result_path}" result)
string(JSON first_install GET "${result}" install_dir)
string(JSON copied_executable GET "${result}" executable)
if(NOT WIN32)
  execute_process(COMMAND "${copied_executable}" RESULT_VARIABLE status)
  if(NOT status EQUAL 0 OR NOT IS_SYMLINK "${first_install}/lib/runtime-link.bin")
    message(FATAL_ERROR "Install lost executable permissions or native library symlink")
  endif()
  math(EXPR checks "${checks}+1")
endif()
run_install(success "second install preserves prior version")
file(READ "${result_path}" result)
string(JSON second_install GET "${result}" install_dir)
if(first_install STREQUAL second_install OR NOT EXISTS "${first_install}/${executable}")
  message(FATAL_ERROR "Installer overwrote an existing version")
endif()
math(EXPR checks "${checks}+1")
run_install("provenance SHA256 differs" "caller manifest pin" "-DEXPECTED_PROVENANCE_SHA256=wrong")
file(APPEND "${bundle}/share/agent-3d-cad/guide.txt" "tampered")
run_install("SHA256 mismatch" "tampered docs")
file(WRITE "${bundle}/share/agent-3d-cad/guide.txt" "Documentation included in full inventory.\n")
file(WRITE "${bundle}/share/agent-3d-cad/unlisted.txt" "unexpected")
run_install("inventory differs" "unlisted file")
file(REMOVE "${bundle}/share/agent-3d-cad/unlisted.txt")
file(RENAME "${bundle}/share/agent-3d-cad/guide.txt" "${TEST_DIR}/guide.txt")
run_install("inventory differs" "missing file")
file(RENAME "${TEST_DIR}/guide.txt" "${bundle}/share/agent-3d-cad/guide.txt")
string(JSON unsafe SET "${manifest}" files 0 path "\"bin/../../outside\"")
file(WRITE "${bundle}/${manifest_path}" "${unsafe}")
run_install("Unsafe bundle path" "manifest traversal")
string(JSON unsafe SET "${manifest}" files 0 path "\"/tmp/outside\"")
file(WRITE "${bundle}/${manifest_path}" "${unsafe}")
run_install("Unsafe bundle path" "manifest absolute path")
string(JSON first GET "${manifest}" files 0)
string(JSON unsafe SET "${manifest}" files ${index} "${first}")
file(WRITE "${bundle}/${manifest_path}" "${unsafe}")
run_install("Duplicate or self-referential" "duplicate manifest file")
file(WRITE "${bundle}/${manifest_path}" "${manifest}")
run_install("must be outside BUNDLE_DIR" "recursive installation" "-DINSTALL_DIR=${bundle}/nested")
if(NOT WIN32)
  file(REMOVE "${bundle}/lib/runtime-link.bin")
  file(CREATE_LINK "../lib/runtime.bin" "${bundle}/lib/runtime-link.bin" SYMBOLIC)
  run_install(success "internal relative parent link")
  file(REMOVE "${bundle}/lib/runtime-link.bin")
  file(WRITE "${TEST_DIR}/outside.bin" "native library fixture\n")
  file(CREATE_LINK "../../outside.bin" "${bundle}/lib/runtime-link.bin" SYMBOLIC)
  run_install("escapes its directory" "external relative symlink")
  file(REMOVE "${bundle}/lib/runtime-link.bin")
  file(CREATE_LINK "${bundle}/lib/runtime.bin" "${bundle}/lib/runtime-link.bin" SYMBOLIC)
  run_install("must be relative file links" "absolute symlink")
  file(REMOVE "${bundle}/lib/runtime-link.bin")
  file(CREATE_LINK runtime.bin "${bundle}/lib/runtime-link.bin" SYMBOLIC)
  file(CREATE_LINK ../share "${bundle}/lib/linked-dir" SYMBOLIC)
  run_install("must be relative file links" "directory symlink")
  file(REMOVE "${bundle}/lib/linked-dir")
  file(CREATE_LINK missing "${bundle}/lib/broken" SYMBOLIC)
  run_install("Missing or broken bundle entry" "broken symlink")
  file(REMOVE "${bundle}/lib/broken")
endif()
message(STATUS "Local installer smoke passed ${checks} checks")
