#include "agentcad/kernel.hpp"
#include "agentcad/mesh_reconstruction.hpp"
#include "agentcad/service.hpp"
#include "agentcad/jobs.hpp"
#include "agentcad/hash.hpp"
#include <STEPControl_Reader.hxx>
#include <BRepCheck_Analyzer.hxx>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <array>
#include <cmath>
#include <numbers>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <thread>
using namespace agentcad;
namespace {
int checks=0;void require(bool ok,const std::string& message){++checks;if(!ok)throw std::runtime_error(message);}void near(double a,double b,double e=1e-7){require(std::abs(a-b)<=e,"Expected "+std::to_string(b)+", got "+std::to_string(a));}
template<class F>void fails(F f,const std::string& code=""){++checks;try{f();}catch(const Error& e){if(code.empty()||e.code==code)return;throw std::runtime_error("Unexpected "+e.code+": "+e.what());}throw std::runtime_error("Expected failure");}
struct Temp{fs::path root=temporary_directory(fs::canonical(fs::temp_directory_path()));~Temp(){std::error_code ec;fs::remove_all(root,ec);}};
using P=std::array<double,3>;P add(P a,P b){for(int k=0;k<3;++k)a[k]+=b[k];return a;}P sub(P a,P b){for(int k=0;k<3;++k)a[k]-=b[k];return a;}double dot(P a,P b){double r=0;for(int k=0;k<3;++k)r+=a[k]*b[k];return r;}double norm(P p){return std::sqrt(dot(p,p));}P cross(P a,P b){return {a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]};}
Json mesh(){return {{"positions",Json::array()},{"triangles",Json::array()}};}void tri(Json& m,P a,P b,P c){auto i=m["positions"].size();for(const auto& p:{a,b,c})m["positions"].push_back(p);m["triangles"].push_back({i,i+1,i+2});}
void plane(Json& m){for(int x=0;x<2;++x)for(int y=0;y<2;++y){P a={double(x*5),double(y*5),30},b={double(x*5+5),double(y*5),30},c={double(x*5+5),double(y*5+5),30},d={double(x*5),double(y*5+5),30};tri(m,a,b,c);tri(m,a,c,d);}}
void cylinder(Json& m,int count=64,double angle=2*std::numbers::pi){for(int i=0;i<count;++i){double a=angle*i/count,b=angle*(i+1)/count;P p={0,5*std::cos(a),5*std::sin(a)},q={0,5*std::cos(b),5*std::sin(b)},r=q,s=p;r[0]=12;s[0]=12;tri(m,p,q,r);tri(m,p,r,s);}}
void sphere(Json& m,int lon=32,int lat=16){auto p=[&](int u,int v){double a=2*std::numbers::pi*(u%lon)/lon,b=std::numbers::pi*v/lat;return P{40+4*std::sin(b)*std::cos(a),4*std::sin(b)*std::sin(a),4*std::cos(b)};};for(int v=0;v<lat;++v)for(int u=0;u<lon;++u){if(v>0)tri(m,p(u,v),p(u+1,v),p(u+1,v+1));if(v<lat-1)tri(m,p(u,v),p(u+1,v+1),p(u,v+1));}}
Json opts(double distance=.08){return {{"distance_tolerance_mm",distance},{"normal_tolerance_deg",12},{"weld_tolerance_mm",1e-7},{"min_triangles",8},{"max_patches",16},{"max_candidates",256}};}
Json recognize(const Json& m,const Json& o=opts(),const Json& guides=Json::array()){return BuiltModel::recognize_mesh(m,o,guides,sha256(m.dump()),sha256("review"+m.dump()));}
const Json& patch(const Json& result,const std::string& kind){for(const auto& p:result.at("patches"))if(p.at("analytic").at("kind")==kind)return p;throw std::runtime_error("Missing "+kind+" patch: "+result.dump());}
void independent(const Json& m,const Json& result){std::vector<bool> seen(m.at("triangles").size());for(const auto& patch:result.at("patches")){const auto& a=patch.at("analytic");const P origin=a.at("origin_mm"),axis=a.at("axis");double measured=0,normal_max=0;for(const auto& id:patch.at("triangle_indices")){const auto n=id.get<std::size_t>();require(!seen[n],"Patch memberships do not overlap");seen[n]=true;const auto t=m.at("triangles")[n];const P p=m.at("positions")[t[0].get<std::size_t>()],q=m.at("positions")[t[1].get<std::size_t>()],r=m.at("positions")[t[2].get<std::size_t>()];for(int u=0;u<=8;++u)for(int v=0;v<=8-u;++v){P point;for(int k=0;k<3;++k)point[k]=(u*p[k]+v*q[k]+(8-u-v)*r[k])/8.;auto d=sub(point,origin);double error;if(a.at("kind")=="plane")error=std::abs(dot(d,axis));else{if(a.at("kind")=="cylinder"){const auto axial=dot(d,axis);for(int k=0;k<3;++k)d[k]-=axis[k]*axial;}error=std::abs(norm(d)-a.at("radius_mm").get<double>());}measured=std::max(measured,error);const auto n=cross(sub(q,p),sub(r,p));const auto ray=a.at("kind")=="plane"?axis:d;const auto denominator=norm(n)*norm(ray);const double cosine=denominator>1e-20?std::clamp(std::abs(dot(n,ray))/denominator,0.,1.):0.;normal_max=std::max(normal_max,std::acos(cosine)*180/std::numbers::pi);}}
  require(normal_max<=patch.at("residual").at("max_normal_deviation_deg").get<double>()+1e-6,"Normal bound covers independent barycentric samples");require(measured<=patch.at("residual").at("max_distance_mm").get<double>()+1e-10,"Full-triangle residual bounds independent dense barycentric samples");require(patch.at("residual").at("max_distance_mm")<=result.at("options").at("distance_tolerance_mm"),"Every patch satisfies explicit distance tolerance");}
 for(const auto& id:result.at("leftover_triangle_indices")){auto n=id.get<std::size_t>();require(!seen[n],"Leftover membership is disjoint");seen[n]=true;}require(std::all_of(seen.begin(),seen.end(),[](bool b){return b;}),"Every source triangle is recognized or leftover");}
void geometry(){auto m=mesh();plane(m);cylinder(m);sphere(m);tri(m,{90,0,0},{91,0,1},{90,1,2});const auto r=recognize(m);require(r.at("patches").size()==3,"Mixed fixture yields three analytic patches");require(r.at("leftover_triangle_indices").size()==1,"Unsupported isolated facet remains explicit");near(patch(r,"cylinder").at("analytic").at("radius_mm"),5);near(patch(r,"sphere").at("analytic").at("radius_mm"),4);near(patch(r,"plane").at("analytic").at("origin_mm")[2],30);independent(m,r);require(recognize(m)==r,"Deterministic source-qualified recognition");
 auto closed=mesh();cylinder(closed);for(int i=0;i<64;++i){const double a=2*std::numbers::pi*i/64,b=2*std::numbers::pi*(i+1)/64;for(double z:{0.,12.})tri(closed,{z,0,0},{z,5*std::cos(a),5*std::sin(a)},{z,5*std::cos(b),5*std::sin(b)});}const auto capped=recognize(closed);require(capped.at("patches").size()==3&&capped.at("leftover_triangle_indices").empty(),"Connected capped cylinder separates cylindrical wall and two planar caps");independent(closed,capped);
 auto partial=mesh();cylinder(partial,32,std::numbers::pi);const auto half=recognize(partial);require(half.at("patches").size()==1&&half.at("leftover_triangle_indices").empty(),"Partial cylinder fits without claiming a closed solid");near(patch(half,"cylinder").at("analytic").at("radius_mm"),5);independent(partial,half);
 auto coarse=mesh();cylinder(coarse,12);auto strict=opts(.001);strict["normal_tolerance_deg"]=20;const auto rejected=recognize(coarse,strict);require(rejected.at("patches").empty(),"Vertices on cylinder do not excuse out-of-tolerance facet sagitta");require(rejected.at("leftover_triangle_indices").size()==24,"Out-of-tolerance coarse mesh is wholly leftover");
 auto noisy=partial;for(std::size_t i=0;i<noisy["positions"].size();++i){auto& p=noisy["positions"][i];const double scale=1+.0001*std::sin(p[0].get<double>()+p[1].get<double>());p[1]=p[1].get<double>()*scale;p[2]=p[2].get<double>()*scale;}const auto noise=recognize(noisy);require(!noise.at("patches").empty(),"Small deterministic scan noise admits bounded analytic fit");independent(noisy,noise);
 auto small=opts();small["max_patches"]=1;auto bounded=recognize(m,small);require(bounded.at("search_budget_exhausted")==true&&!bounded.at("leftover_triangle_indices").empty(),"Patch budget returns qualified leftovers");auto wrong=opts();wrong["distance_tolerance_mm"]=0;fails([&]{recognize(m,wrong);},"invalid_argument");wrong=opts();wrong["weld_tolerance_mm"]=1;fails([&]{recognize(m,wrong);},"invalid_argument");
 Json guides=Json::array();for(const auto& p:r.at("patches")){const auto k=p.at("analytic").at("kind").get<std::string>();Json g={{"patch_id",p.at("id")},{"feature_id",k+"Solid"},{"extent",k=="plane"?"rectangle":k}};if(k=="plane"){g["bounds_uv_mm"]=p.at("observed_bounds_uv_mm");g["thickness_mm"]=2;}if(k=="cylinder")g["axis_range_mm"]=p.at("axis_range_mm");guides.push_back(g);}const auto proposals=recognize(m,opts(),guides);Temp temp;Service service(temp.root);
 for(const auto& p:proposals.at("proposals")){const auto model=p.at("model");const auto id=model.at("output").get<std::string>();const auto made=service.call("cad_create",{{"document_id",id},{"model",model}});const double expected=id=="planeSolid"?200:id=="cylinderSolid"?300*std::numbers::pi:256*std::numbers::pi/3;near(made.at("summary").at("volume_mm3"),expected,1e-6);const auto exported=service.call("cad_export",{{"document_id",id},{"revision",1},{"format","step"}});STEPControl_Reader reader;require(reader.ReadFile(exported.at("path").get<std::string>().c_str())==IFSelect_RetDone&&reader.TransferRoots()>0,"Adopted proposal exports independent STEP");require(BRepCheck_Analyzer(reader.OneShape()).IsValid(),"Proposed exact solid survives STEP readback");GProp_GProps volume;BRepGProp::VolumeProperties(reader.OneShape(),volume);near(volume.Mass(),expected,1e-5);
  auto before=service.call("cad_read",{{"document_id",id}});const auto parameter=id+(id=="planeSolid"?"Width":"Radius");fails([&]{service.call("cad_apply",{{"document_id",id},{"expected_revision",1},{"operations",Json::array({{{"op","set_parameter"},{"name",parameter},{"value",0}}})}});});require(service.call("cad_read",{{"document_id",id}})==before,"Failed adopted-proposal edit preserves HEAD");
  const Json seed={{"schema_version",1},{"units","mm"},{"parameters",Json::object()},{"features",Json::array({{{"id","seed"},{"type","box"},{"size",{1,1,1}}}})},{"output","seed"}};service.call("cad_create",{{"document_id",id+"Apply"},{"model",seed}});near(service.call("cad_apply",{{"document_id",id+"Apply"},{"expected_revision",1},{"operations",p.at("operations")}}).at("summary").at("volume_mm3"),expected,1e-6);
 }
 auto stale=guides;stale[0]["patch_id"]="wrong";fails([&]{recognize(m,opts(),stale);},"stale_selection");
}
std::string stl(const Json& m){std::ostringstream s;s<<std::setprecision(17)<<"solid fixture\n";for(const auto& t:m.at("triangles")){s<<"facet normal 0 0 0\nouter loop\n";for(const auto& i:t){const P p=m.at("positions")[i.get<std::size_t>()];s<<"vertex "<<p[0]<<' '<<p[1]<<' '<<p[2]<<'\n';}s<<"endloop\nendfacet\n";}s<<"endsolid fixture\n";return s.str();}
Json wait(Service& service,const std::string& id){for(int i=0;i<1000;++i){try{const auto r=service.call("cad_job",{{"action","get"},{"job_id",id}});if(r.at("state")=="succeeded"||r.at("state")=="failed")return r;}catch(const Error& e){if(e.code!="workspace_busy")throw;}std::this_thread::sleep_for(std::chrono::milliseconds(10));}throw std::runtime_error("Job timeout");}
void captured(){Temp temp;Service service(temp.root);auto m=mesh();cylinder(m);const auto bytes=stl(m);const auto path=temp.root/"cylinder.stl";atomic_text(path,bytes);const auto review=service.call("cad_artifact",{{"action","review"},{"path",path_to_utf8(path)},{"format","stl"},{"units","mm"},{"expected_sha256",sha256(bytes)}});Json args={{"action","recognize"},{"review_path",review.at("path")},{"expected_sha256",review.at("sha256")},{"options",opts()}};const auto r=service.call("cad_artifact",args);near(patch(r,"cylinder").at("analytic").at("radius_mm"),5);fs::remove(path);require(service.call("cad_artifact",args)==r,"Captured source permits original deletion without stale references");service.call("cad_job",{{"action","submit"},{"request_id","recognizeJob"},{"tool","cad_artifact"},{"arguments",args}});const auto job=wait(service,"recognizeJob");require(job.at("state")=="succeeded"&&job.at("result")==r,"Durable bounded native job reproduces recognition");auto bad=args;bad["reconstruct"]=Json::array({{{"patch_id","stale"},{"feature_id","Solid"},{"extent","cylinder"},{"axis_range_mm",{0,12}}}});service.call("cad_job",{{"action","submit"},{"request_id","staleJob"},{"tool","cad_artifact"},{"arguments",bad}});require(wait(service,"staleJob").at("state")=="failed","Stale guide fails inside bounded job");
 service.call("cad_job",{{"action","submit"},{"request_id","boundedJob"},{"tool","cad_artifact"},{"arguments",args},{"budget",{{"timeout_ms",1},{"memory_mb",2048}}}});const auto timed=wait(service,"boundedJob");require(timed.at("state")=="failed"&&timed.at("error").at("code")=="job_timeout","Recognition obeys native worker deadline");require(service.call("cad_artifact",args)==r,"Timed-out recognition leaves captured source unchanged");
 const auto captured=path_from_utf8(review.at("directory"))/path_from_utf8(review.at("source").at("path"));atomic_text(captured,bytes+"changed");fails([&]{service.call("cad_artifact",args);},"artifact_invalid");
}
}
int main(){try{set_worker_executable(path_from_utf8(CAD_SERVICE_EXE));geometry();captured();std::cout<<checks<<" mesh reconstruction checks passed\n";return 0;}catch(const Error& e){std::cerr<<"After "<<checks<<": "<<e.code<<": "<<e.what()<<" "<<e.details.dump()<<'\n';return 1;}catch(const std::exception& e){std::cerr<<"After "<<checks<<": "<<e.what()<<'\n';return 1;}}
