cmake_minimum_required(VERSION 3.24)
# Legal notices must agree with what the installer actually records. A stale
# modification identifier or archive hash in a shipped notice is a distribution
# defect, so fail the build instead of relying on a reviewer to notice.
if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR required")
endif()
function(read_text path out)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing required file: ${path}")
  endif()
  file(READ "${path}" text)
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

read_text("${SOURCE_DIR}/cmake/InstallBundle.cmake.in" installer)
string(REGEX MATCH "agentcad-hlr-midpoint-v[0-9]+" expected "${installer}")
if(NOT expected)
  message(FATAL_ERROR "Installer does not name an HLR modification identifier")
endif()
read_text("${SOURCE_DIR}/cmake/dependencies/CMakeLists.txt" recipe)

set(checks 0)
foreach(file IN ITEMS packaging/THIRD_PARTY.md cmake/dependencies/OCCT-HLR-PATCH.md)
  read_text("${SOURCE_DIR}/${file}" text)
  string(REGEX MATCHALL "agentcad-hlr-midpoint-v[0-9]+" ids "${text}")
  list(REMOVE_DUPLICATES ids)
  if(NOT ids STREQUAL expected)
    message(FATAL_ERROR "${file} names modification '${ids}', installer records '${expected}'")
  endif()
  math(EXPR checks "${checks}+1")
endforeach()

read_text("${SOURCE_DIR}/packaging/THIRD_PARTY.md" notices)
string(REGEX MATCH "0d6913eae4bcc09a3653ceced6dda1aec11c35a1513d4c06762c9b002092c68a" shown "${notices}")
if(NOT shown OR NOT recipe MATCHES "${shown}")
  message(FATAL_ERROR "THIRD_PARTY.md must state the pinned OCCT archive SHA-256 used by the dependency recipe")
endif()
math(EXPR checks "${checks}+1")
foreach(phrase IN ITEMS "LGPL 2.1" "PatchOcctHlr.cmake" "occt/modified/" "relink")
  string(FIND "${notices}" "${phrase}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "THIRD_PARTY.md no longer mentions '${phrase}'")
  endif()
  math(EXPR checks "${checks}+1")
endforeach()
foreach(file IN ITEMS NOTICE SECURITY.md CONTRIBUTING.md)
  read_text("${SOURCE_DIR}/${file}" text)
  math(EXPR checks "${checks}+1")
endforeach()
read_text("${SOURCE_DIR}/NOTICE" project_notice)
string(FIND "${project_notice}" "has not been selected" at)
if(at EQUAL -1)
  message(FATAL_ERROR "NOTICE must keep stating that the original-code license is undecided")
endif()
if(EXISTS "${SOURCE_DIR}/LICENSE" OR EXISTS "${SOURCE_DIR}/LICENSE.md" OR EXISTS "${SOURCE_DIR}/LICENSE.txt")
  message(FATAL_ERROR "A LICENSE file exists: update NOTICE, which says no license has been selected")
endif()
math(EXPR checks "${checks}+2")
message(STATUS "notice consistency checks passed: ${checks}")
