#include "agentcad/kernel.hpp"
#include "agentcad/model.hpp"
#include "agentcad/service.hpp"
#include "agentcad/jobs.hpp"
#include "agentcad/cache.hpp"
#include <BRepAdaptor_Surface.hxx>
#include <BRepCheck_Analyzer.hxx>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <STEPControl_Reader.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <cmath>
#include <functional>
#include <iostream>
#include <numbers>
#include <set>
#include <thread>
using namespace agentcad;
namespace {
int checks=0;
void require(bool ok,const std::string& message){++checks;if(!ok)throw std::runtime_error(message);}
void near(double a,double b,double tolerance=1e-5){require(std::abs(a-b)<tolerance,"Expected "+std::to_string(b)+", got "+std::to_string(a));}
void fails(const std::function<void()>& f){try{f();}catch(const Error&){++checks;return;}throw std::runtime_error("Expected rejection");}
struct Temp{fs::path root=temporary_directory(fs::canonical(fs::temp_directory_path()));~Temp(){std::error_code ignored;fs::remove_all(root,ignored);}};
Json edge(Json center,Json axis={1,0,0}){return {{"type","geometric"},{"feature_id","profile"},{"curve_kind","line"},{"expected_count",1},{"center",{{"point",center},{"tolerance",1e-6}}},{"direction",{{"vector",axis},{"tolerance",1e-6}}}};}
Json bend(const std::string& id,const std::string& parent,double angle=90,double length=10){return {{"id",id},{"parent",parent},{"inside_radius",2},{"angle_deg",angle},{"length",length}};}
Json root_bend(){auto result=bend("wall","",90,20);result.erase("parent");result["edge"]=edge({40,60,0});return result;}
Json model(Json flanges,bool flat=true){Json m={{"schema_version",1},{"units","mm"},{"parameters",{{"t",1.5},{"k",.5},{"lip",8}}},{"features",Json::array({{{"id","profile"},{"type","sketch"},{"workplane",{{"origin",{0,0,0}},{"normal",{0,0,1}},{"x_direction",{1,0,0}}}},{"profile",{{"type","rectangle"},{"width",80},{"height",60}}}},{{"id","formed"},{"type","sheet_metal"},{"input","profile"},{"thickness",{{"parameter","t"}}},{"k_factor",{{"parameter","k"}}},{"flanges",flanges}}})},{"output",flat?"flat":"formed"}};if(flat)m["features"].push_back({{"id","flat"},{"type","sheet_unfold"},{"input","formed"}});return m;}
Json enclosure(){auto wall=root_bend();wall["start_gap"]=3;wall["end_gap"]=3;wall["relief"]={{"width",1},{"depth",2}};auto lip=bend("lip","wall",90,8);lip["length"]={{"parameter","lip"}};auto hem=bend("safe","lip",180,3);hem["hem"]=true;hem["inside_radius"]=1;hem["angle_deg"]=-180;auto other=root_bend();other["id"]="opposite";other["edge"]=edge({40,0,0});other["start_gap"]=3;other["end_gap"]=3;other["relief"]={{"width",1},{"depth",2}};auto left=other;left["id"]="left";left["edge"]=edge({0,30,0},{0,1,0});auto right=other;right["id"]="right";right["edge"]=edge({80,30,0},{0,1,0});return model(Json::array({wall,lip,hem,other,left,right}));}
void geometry(){
  const double allowance=2.75*std::numbers::pi/2;
  auto chain=model(Json::array({root_bend(),bend("return","wall",90,10),bend("third","return",-90,5)}));BuiltModel built(chain);near(built.summary().at("volume_mm3"),(4800+80*(35+3*allowance))*1.5);near(built.summary("formed").at("volume_mm3"),built.summary().at("volume_mm3"));
  const auto report=built.summary().at("sheet_metal");require(report.at("bends").size()==3,"Named three-bend intent retained");near(report.at("bends")[1].at("bend_start_line_mm")[0][1],60+20+allowance);near(report.at("bends")[2].at("bend_start_line_mm")[0][1],60+30+2*allowance);
  auto jog=model(Json::array({root_bend(),bend("jog","wall",-90,10)}));near(BuiltModel(jog).summary("formed").at("bounds_mm").at("max")[2],25.5);near(BuiltModel(jog).summary().at("volume_mm3"),(4800+80*(30+2*allowance))*1.5);
  auto hem=root_bend();hem["angle_deg"]=180;hem["hem"]=true;hem["length"]=10;auto hem_model=model(Json::array({hem}));BuiltModel h(hem_model);require(h.summary().at("sheet_metal").at("bends")[0].at("bend_deduction_mm").is_null(),"Parallel hem deduction is undefined instead of a spurious huge number");near(h.summary("formed").at("volume_mm3"),(4800+80*(10+2.75*std::numbers::pi))*1.5);
  auto side=bend("side","wall",90,5);side["attachment"]="start";auto side_model=model(Json::array({root_bend(),side}));near(BuiltModel(side_model).summary().at("volume_mm3"),(4800+80*(20+allowance)+20*(5+allowance))*1.5);
  auto miter=root_bend();miter["miter"]={{"start_deg",45},{"end_deg",30}};auto miter_model=model(Json::array({miter}));near(BuiltModel(miter_model).summary().at("volume_mm3"),(4800+80*(20+allowance)-200*(1+std::tan(std::numbers::pi/6)))*1.5);
  auto cut=root_bend();cut["cuts"]=Json::array({{{"offset",10},{"width",5},{"from",1},{"to",allowance+7}}});auto cut_model=model(Json::array({cut}));BuiltModel c(cut_model);near(c.summary().at("volume_mm3"),(4800+80*(20+allowance)-5*(allowance+6))*1.5);near(c.summary("formed").at("volume_mm3"),c.summary().at("volume_mm3"));
  cut_model["parameters"]["k"]=.3;BuiltModel different(cut_model);const auto neutral_allowance=2.45*std::numbers::pi/2;near(different.summary("formed").at("volume_mm3"),(4800+80*(20+allowance)-5*((neutral_allowance-1)*allowance/neutral_allowance+(allowance+7-neutral_allowance)))*1.5);require(std::abs(different.summary().at("volume_mm3").get<double>()-different.summary("formed").at("volume_mm3").get<double>())>1,"K-factor explicitly affects cut arclength mapping and flat volume");
  auto fold=bend("fold","",90,20-allowance);fold.erase("parent");fold["fold_line"]={{80,40,0},{0,40,0}};auto folded=model(Json::array({fold}));BuiltModel f(folded);near(f.summary().at("volume_mm3"),7200);near(f.summary().at("bounds_mm").at("max")[1],60);near(f.summary("formed").at("volume_mm3"),7200);near(f.summary("formed").at("bounds_mm").at("max")[1],43.5);
  auto relief=root_bend();relief["relief"]={{"width",2},{"depth",3}};near(BuiltModel(model(Json::array({relief}))).summary().at("volume_mm3"),(4800-12+76*(20+allowance))*1.5);
  BuiltModel real(enclosure());Temp t;const auto path=t.root/"enclosure.step";real.export_file(path,"step","formed");STEPControl_Reader reader;require(reader.ReadFile(path_to_utf8(path).c_str())==IFSelect_RetDone&&reader.TransferRoots()>0,"Independent STEP reader reads multi-bend enclosure");require(BRepCheck_Analyzer(reader.OneShape()).IsValid(),"Independent STEP shell is valid");GProp_GProps volume;BRepGProp::VolumeProperties(reader.OneShape(),volume,1e-9);near(volume.Mass(),real.summary("formed").at("volume_mm3"),1e-8*real.summary("formed").at("volume_mm3").get<double>());std::set<double> radii;for(TopExp_Explorer it(reader.OneShape(),TopAbs_FACE);it.More();it.Next()){BRepAdaptor_Surface surface(TopoDS::Face(it.Current()));if(surface.GetType()==GeomAbs_Cylinder)radii.insert(surface.Cylinder().Radius());}require(radii.size()==4,"STEP preserves physical exact bend-cylinder radii");for(double radius:{1.0,2.0,2.5,3.5})require(radii.contains(radius),"Expected exact inner/outer radius");
  auto rotated=chain;rotated["features"][0]["workplane"]={{"origin",{7,11,13}},{"normal",{1,0,0}},{"x_direction",{0,1,0}}};rotated["features"][1]["flanges"][0]["edge"]=edge({7,51,73},{0,1,0});near(BuiltModel(rotated).summary().at("volume_mm3"),built.summary().at("volume_mm3"));
  auto collision=chain;collision["features"][1]["flanges"][2]["angle_deg"]=90;collision["features"][1]["flanges"][2]["length"]=40;fails([&]{BuiltModel rejected(collision);});
  auto invalid=chain;invalid["features"][1]["flanges"][1]["parent"]="missing";fails([&]{BuiltModel rejected(invalid);});invalid=chain;invalid["features"][1]["flanges"][1]["edge"]=edge({40,60,0});fails([&]{BuiltModel rejected(invalid);});invalid=cut_model;invalid["features"][1]["flanges"][0]["cuts"].push_back(invalid["features"][1]["flanges"][0]["cuts"][0]);fails([&]{BuiltModel rejected(invalid);});invalid=cut_model;invalid["features"][1]["flanges"][0]["cuts"][0]["to"]=1.000000001;fails([&]{BuiltModel rejected(invalid);});invalid=folded;invalid["features"][1]["flanges"][0]["length"]=30;fails([&]{BuiltModel rejected(invalid);});
}
Json wait_job(Service& service,const std::string& id){const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(30);while(std::chrono::steady_clock::now()<deadline){try{const auto state=service.call("cad_job",{{"action","get"},{"job_id",id}});if(state.at("state")=="succeeded"||state.at("state")=="failed")return state;}catch(const Error& e){if(e.code!="workspace_busy")throw;}std::this_thread::sleep_for(std::chrono::milliseconds(20));}throw std::runtime_error("Sheet job exceeded its deadline");}
void lifecycle(){Temp temp;Service service(temp.root);auto created=service.call("cad_create",{{"document_id","enclosure"},{"model",enclosure()}});created["model"]=service.call("cad_read",{{"document_id","enclosure"},{"revision",created.at("revision")}}).at("model");const double original=created.at("summary").at("volume_mm3");Json diagnostics;const auto evaluated=evaluate_model(temp.root,created.at("model"),{{"kind","view"}},&diagnostics);fs::remove(temp.root/".cache"/(geometry_cache_key(created.at("model"))+".json"));const auto cached=evaluate_model(temp.root,created.at("model"),{{"kind","view"}},&diagnostics);require(cached.at("summary")==evaluated.at("summary")&&diagnostics.at("feature_hits").at("formed")==true&&diagnostics.at("feature_hits").at("flat")==true,"Exact cache retains complete complex bend recipe");fs::remove_all(temp.root/".cache");Service reopened(temp.root);near(reopened.call("cad_query",{{"document_id","enclosure"},{"revision",1}}).at("summary").at("volume_mm3"),original);auto changed=reopened.call("cad_apply",{{"document_id","enclosure"},{"expected_revision",1},{"operations",Json::array({{{"op","set_parameter"},{"name","lip"},{"value",9}}})}});near(changed.at("summary").at("volume_mm3"),original+72*1.5);auto before=reopened.call("cad_read",{{"document_id","enclosure"}});fails([&]{reopened.call("cad_apply",{{"document_id","enclosure"},{"expected_revision",2},{"operations",Json::array({{{"op","set_parameter"},{"name","lip"},{"value",-1}}})}});});require(before==reopened.call("cad_read",{{"document_id","enclosure"}}),"Invalid nested lip dimension preserves HEAD");
  for(const auto* mode:{"formed","flat"})for(const auto* format:{"step","stl","3mf"}){const auto exported=reopened.call("cad_export",{{"document_id","enclosure"},{"revision",2},{"feature_id",mode},{"format",format}});require(fs::exists(path_from_utf8(exported.at("path"))),"Four-wall enclosure modes export independently");}
  const auto drawing=reopened.call("cad_drawing",{{"document_id","enclosure"},{"revision",2},{"drawing",{{"formats",{"dxf"}},{"views",Json::array({{{"id","top"},{"orientation","top"}}})}}}});bool dxf=false;for(const auto& artifact:drawing.at("artifacts"))if(artifact.at("format")=="dxf"){require(read_text(path_from_utf8(artifact.at("path")),16*1024*1024).find("EOF")!=std::string::npos,"Multi-bend developed outline exports an independent DXF");dxf=true;}require(dxf,"Developed enclosure has cutting DXF");
  Json seed={{"schema_version",1},{"units","mm"},{"parameters",Json::object()},{"features",Json::array({{{"id","seed"},{"type","box"},{"size",{1,1,1}}}})},{"output","seed"}};reopened.call("cad_create",{{"document_id","consumer"},{"model",seed}});auto captured=reopened.call("cad_apply",{{"document_id","consumer"},{"expected_revision",1},{"operations",Json::array({{{"op","set_component"},{"id","blank"},{"source_document_id","enclosure"},{"source_revision",2}},{{"op","set_output"},{"feature_id","blank"}}})}});captured["model"]=reopened.call("cad_read",{{"document_id","consumer"},{"revision",captured.at("revision")}}).at("model");for(const auto& feature:captured.at("model").at("features"))if(feature.at("type")=="sheet_metal"){require(feature.at("flanges")[0].at("edge").at("feature_id")==feature.at("input"),"Base feature reference is remapped");require(feature.at("flanges")[1].at("parent")=="wall","Local flange intent IDs remain scoped and unchanged");}Temp portable;fs::remove_all(temp.root/"documents/enclosure");Service independent(portable.root);near(independent.call("cad_create",{{"document_id","portable"},{"model",captured.at("model")}}).at("summary").at("volume_mm3"),changed.at("summary").at("volume_mm3"));
  independent.call("cad_job",{{"action","submit"},{"request_id","enclosureJob"},{"tool","cad_create"},{"arguments",{{"document_id","jobEnclosure"},{"model",enclosure()}}}});const auto job=wait_job(independent,"enclosureJob");require(job.at("state")=="succeeded",job.dump());near(job.at("result").at("summary").at("volume_mm3"),original);
  independent.call("cad_job",{{"action","submit"},{"request_id","badEnclosureJob"},{"tool","cad_apply"},{"arguments",{{"document_id","jobEnclosure"},{"expected_revision",1},{"operations",Json::array({{{"op","set_parameter"},{"name","lip"},{"value",-1}}})}}}});require(wait_job(independent,"badEnclosureJob").at("state")=="failed","Invalid chained edit job fails");require(independent.call("cad_read",{{"document_id","jobEnclosure"}}).at("revision")==1,"Failed chained job preserves saved revision");
}
}
int main(){try{set_worker_executable(path_from_utf8(CAD_SERVICE_EXE));geometry();lifecycle();std::cout<<checks<<" parity sheet checks passed\n";return 0;}catch(const Error& e){std::cerr<<"After "<<checks<<" checks: "<<e.code<<": "<<e.what()<<" "<<e.details.dump()<<'\n';return 1;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
