cmake_minimum_required(VERSION 3.24)

# Install an already-extracted, trusted preview bundle. This verifies integrity;
# it does not authenticate the publisher or extract archives. No host/MCP config
# is changed, and existing version directories are never replaced.
foreach(argument BUNDLE_DIR INSTALL_DIR)
  if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
    message(FATAL_ERROR "${argument} is required")
  endif()
endforeach()
foreach(argument BUNDLE_DIR INSTALL_DIR RESULT_FILE)
  if(DEFINED ${argument} AND "${${argument}}" MATCHES "[;\n\r\t]")
    message(FATAL_ERROR "${argument} contains unsupported control characters or a semicolon")
  endif()
endforeach()
get_filename_component(bundle_input "${BUNDLE_DIR}" ABSOLUTE)
if(NOT IS_DIRECTORY "${bundle_input}" OR IS_SYMLINK "${bundle_input}")
  message(FATAL_ERROR "BUNDLE_DIR must be a real directory")
endif()
file(REAL_PATH "${bundle_input}" bundle)
get_filename_component(install_input "${INSTALL_DIR}" ABSOLUTE)
# Resolve existing ancestors too, so a symlink cannot hide destination recursion.
set(ancestor "${install_input}")
set(missing_parts)
while(NOT EXISTS "${ancestor}")
  if(IS_SYMLINK "${ancestor}")
    message(FATAL_ERROR "INSTALL_DIR has a broken symlink ancestor")
  endif()
  cmake_path(GET ancestor FILENAME part)
  list(PREPEND missing_parts "${part}")
  cmake_path(GET ancestor PARENT_PATH parent)
  if(parent STREQUAL ancestor OR parent STREQUAL "")
    message(FATAL_ERROR "INSTALL_DIR has no existing filesystem ancestor")
  endif()
  set(ancestor "${parent}")
endwhile()
file(REAL_PATH "${ancestor}" install_root)
foreach(part IN LISTS missing_parts)
  cmake_path(APPEND install_root "${part}")
endforeach()
cmake_path(IS_PREFIX bundle "${install_root}" NORMALIZE destination_in_source)
if(destination_in_source)
  message(FATAL_ERROR "INSTALL_DIR must be outside BUNDLE_DIR")
endif()

set(manifest_path "share/agent-3d-cad/provenance.json")
function(check_relative_path path)
  if(IS_ABSOLUTE "${path}" OR NOT path MATCHES "^(bin|lib|share)/[^/].*"
      OR path MATCHES "(^|/)\\.\\.?(/|$)" OR path MATCHES "//|[\\\\;:\n\r\t]" OR path MATCHES "/$")
    message(FATAL_ERROR "Unsafe bundle path: ${path}")
  endif()
endfunction()

function(check_entry base relative)
  check_relative_path("${relative}")
  set(path "${base}/${relative}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing or broken bundle entry: ${relative}")
  endif()
  if(IS_SYMLINK "${path}")
    file(READ_SYMLINK "${path}" target)
    if(IS_ABSOLUTE "${target}" OR IS_DIRECTORY "${path}")
      message(FATAL_ERROR "Bundle links must be relative file links: ${relative}")
    endif()
  endif()
  file(REAL_PATH "${path}" resolved)
  cmake_path(IS_PREFIX base "${resolved}" NORMALIZE inside)
  if(NOT inside)
    message(FATAL_ERROR "Bundle entry escapes its directory: ${relative}")
  endif()
endfunction()

function(verify_bundle base)
  if(NOT EXISTS "${base}/${manifest_path}" OR IS_SYMLINK "${base}/${manifest_path}")
    message(FATAL_ERROR "Bundle provenance must be a regular file")
  endif()
  file(SHA256 "${base}/${manifest_path}" actual_manifest_hash)
  if(NOT actual_manifest_hash STREQUAL manifest_hash)
    message(FATAL_ERROR "Bundle provenance changed during installation")
  endif()
  file(GLOB roots LIST_DIRECTORIES true RELATIVE "${base}" "${base}/*")
  foreach(top IN LISTS roots)
    if(NOT top MATCHES "^(bin|lib|share)$" OR NOT IS_DIRECTORY "${base}/${top}" OR IS_SYMLINK "${base}/${top}")
      message(FATAL_ERROR "Unexpected bundle root entry: ${top}")
    endif()
  endforeach()
  foreach(required bin share)
    if(NOT IS_DIRECTORY "${base}/${required}")
      message(FATAL_ERROR "Bundle is missing ${required}")
    endif()
  endforeach()
  # CMP0009 is NEW: do not traverse directory symlinks. check_entry rejects them.
  file(GLOB_RECURSE entries LIST_DIRECTORIES true RELATIVE "${base}"
    "${base}/bin/*" "${base}/lib/*" "${base}/share/*")
  set(actual_files)
  foreach(entry IN LISTS entries)
    check_entry("${base}" "${entry}")
    if(NOT IS_DIRECTORY "${base}/${entry}" AND NOT entry STREQUAL manifest_path)
      list(APPEND actual_files "${entry}")
    endif()
  endforeach()
  list(SORT actual_files)
  if(NOT actual_files STREQUAL expected_files)
    message(FATAL_ERROR "Bundle inventory differs from provenance (missing or unlisted files)")
  endif()
  math(EXPR last "${file_count}-1")
  foreach(index RANGE ${last})
    string(JSON relative GET "${manifest}" files ${index} path)
    string(JSON expected_hash GET "${manifest}" files ${index} sha256)
    file(SHA256 "${base}/${relative}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
      message(FATAL_ERROR "Bundle SHA256 mismatch: ${relative}")
    endif()
  endforeach()
endfunction()

if(NOT EXISTS "${bundle}/${manifest_path}" OR IS_SYMLINK "${bundle}/${manifest_path}")
  message(FATAL_ERROR "Bundle provenance must be a regular file")
endif()
check_entry("${bundle}" "${manifest_path}")
file(READ "${bundle}/${manifest_path}" manifest)
file(SHA256 "${bundle}/${manifest_path}" manifest_hash)
if(DEFINED EXPECTED_PROVENANCE_SHA256 AND NOT EXPECTED_PROVENANCE_SHA256 STREQUAL manifest_hash)
  message(FATAL_ERROR "Bundle provenance SHA256 differs from EXPECTED_PROVENANCE_SHA256")
endif()
string(JSON format GET "${manifest}" format_version)
if(NOT format STREQUAL "1")
  message(FATAL_ERROR "Unsupported provenance format: ${format}")
endif()
foreach(field project_version system architecture)
  string(JSON ${field} GET "${manifest}" ${field})
  if(NOT ${field} MATCHES "^[A-Za-z0-9_.+-]+$")
    message(FATAL_ERROR "Invalid provenance ${field}")
  endif()
endforeach()
string(JSON file_count LENGTH "${manifest}" files)
if(file_count LESS 1)
  message(FATAL_ERROR "Bundle provenance is empty")
endif()
math(EXPR last "${file_count}-1")
set(expected_files)
foreach(index RANGE ${last})
  string(JSON relative GET "${manifest}" files ${index} path)
  string(JSON hash GET "${manifest}" files ${index} sha256)
  check_relative_path("${relative}")
  if(relative STREQUAL manifest_path OR relative IN_LIST expected_files)
    message(FATAL_ERROR "Duplicate or self-referential provenance path: ${relative}")
  endif()
  string(LENGTH "${hash}" hash_length)
  if(NOT hash_length EQUAL 64 OR NOT hash MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Invalid SHA256 for ${relative}")
  endif()
  list(APPEND expected_files "${relative}")
endforeach()
list(SORT expected_files)
if(system STREQUAL "Windows")
  set(executable "bin/agent-3d-cad.exe")
else()
  set(executable "bin/agent-3d-cad")
endif()
if(NOT executable IN_LIST expected_files)
  message(FATAL_ERROR "Bundle provenance is missing its executable")
endif()
verify_bundle("${bundle}")

file(MAKE_DIRECTORY "${install_root}")
file(REAL_PATH "${install_root}" install_root)
cmake_path(IS_PREFIX bundle "${install_root}" NORMALIZE destination_in_source)
if(destination_in_source)
  message(FATAL_ERROR "INSTALL_DIR resolves inside BUNDLE_DIR")
endif()
set(lock_path "${install_root}/.agent-3d-cad-install.lock")
if(IS_SYMLINK "${lock_path}")
  message(FATAL_ERROR "Installation lock must not be a symlink")
endif()
file(LOCK "${lock_path}" GUARD PROCESS TIMEOUT 30 RESULT_VARIABLE lock_result)
if(NOT lock_result STREQUAL "0")
  message(FATAL_ERROR "Unable to lock installation directory: ${lock_result}")
endif()
string(SUBSTRING "${manifest_hash}" 0 12 short_hash)
string(TIMESTAMP timestamp "%Y%m%dT%H%M%SZ" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(name "agent-3d-cad-${project_version}-${system}-${architecture}-${short_hash}-${timestamp}-${nonce}")
set(staging "${install_root}/.install-${nonce}")
set(installed "${install_root}/${name}")
if(EXISTS "${staging}" OR IS_SYMLINK "${staging}" OR EXISTS "${installed}" OR IS_SYMLINK "${installed}")
  message(FATAL_ERROR "Fresh installation path already exists; retry installation")
endif()
file(MAKE_DIRECTORY "${staging}")
foreach(top bin lib share)
  if(IS_DIRECTORY "${bundle}/${top}")
    file(COPY "${bundle}/${top}" DESTINATION "${staging}" USE_SOURCE_PERMISSIONS)
  endif()
endforeach()
verify_bundle("${staging}")
# The installation-directory lock serializes cooperating installers; the fresh
# random name and existence check retain prior versions. Plain rename also works
# under macOS sandboxes that disallow renamex_np(RENAME_EXCL).
file(RENAME "${staging}" "${installed}" RESULT rename_result)
if(NOT rename_result STREQUAL "0")
  message(FATAL_ERROR "Unable to publish fresh installation: ${rename_result}")
endif()
if(DEFINED RESULT_FILE)
  # CMake JSON SET expects JSON-encoded string values.
  string(REPLACE "\\" "\\\\" json_installed "${installed}")
  string(REPLACE "\"" "\\\"" json_installed "${json_installed}")
  file(WRITE "${RESULT_FILE}" "{\"install_dir\":\"${json_installed}\",\"executable\":\"${json_installed}/${executable}\",\"provenance_sha256\":\"${manifest_hash}\",\"verified_files\":${file_count}}\n")
endif()
message(STATUS "Verified ${file_count} files; installed ${installed}")
message(STATUS "MCP command: ${installed}/${executable} serve --workspace <workspace>")
