cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED SOURCE_DIR)
  get_filename_component(SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED STAGE_DIR)
  set(STAGE_DIR "${SOURCE_DIR}/build-linux-container/context")
endif()
file(MAKE_DIRECTORY "${STAGE_DIR}/source" "${STAGE_DIR}/archives")
# Keep the native build, its notices, and developer tests self-contained.
# Do not copy host build trees, credentials, caches, or the host-native SDK.
foreach(item CMakeLists.txt VERSION README.md LICENSE NOTICE install.sh install.ps1
    src include third_party cmake docs examples tests packaging web skills .github)
  file(COPY "${SOURCE_DIR}/${item}" DESTINATION "${STAGE_DIR}/source")
endforeach()
foreach(archive OCCT-V8_0_1.tar.gz freetype-2.14.3.tar.xz json-3.12.0.tar.gz)
  if(NOT EXISTS "${SOURCE_DIR}/.deps/${archive}")
    message(FATAL_ERROR "Missing pinned archive .deps/${archive}; obtain it from docs/DEPENDENCIES.md before staging")
  endif()
  file(COPY "${SOURCE_DIR}/.deps/${archive}" DESTINATION "${STAGE_DIR}/archives")
endforeach()
file(COPY_FILE "${SOURCE_DIR}/packaging/Dockerfile.linux-validation" "${STAGE_DIR}/Dockerfile")
message(STATUS "Staged project source and pinned archives only in ${STAGE_DIR}")
