#include "artifact_internal.hpp"
#include <cmath>
#include <algorithm>

namespace agentcad::artifact_detail {
namespace {
using Element=const tinyxml2::XMLElement*;
Element child(Element e,const char*name,bool mandatory=false){auto result=e->FirstChildElement(name);require(!result||!result->NextSiblingElement(name),"Duplicate robot singleton element");require(result||!mandatory,"Missing robot element: "+std::string(name));return result;}
std::string content(Element e){require(e&&e->GetText(),"Missing robot element text");return e->GetText();}
void plain(Element e){require(std::string(e->Name()).find(':')==std::string::npos&&!e->Attribute("xmlns"),"Robot XML namespaces/macros are unsupported");for(auto a=e->FirstAttribute();a;a=a->Next())if(std::string(a->Name()).find(':')!=std::string::npos)unsupported("Robot namespaced attributes are unsupported");for(auto c=e->FirstChildElement();c;c=c->NextSiblingElement())plain(c);}
Mat urdf_origin(Element e){if(!e)return identity();if(e->Attribute("quat_xyzw"))unsupported("URDF quaternion origins require a newer supported subset");const auto xyz=numbers(attribute(e,"xyz","0 0 0"),3),rpy=numbers(attribute(e,"rpy","0 0 0"),3);return pose({xyz[0],xyz[1],xyz[2],rpy[0],rpy[1],rpy[2]},1000);}
Mat sdf_pose(Element e){if(!e)return identity();if(!attribute(e,"relative_to").empty()||attribute(e,"rotation_format","euler_rpy")!="euler_rpy"||attribute(e,"degrees","false")!="false")unsupported("SDF named pose frames, quaternion poses and degree poses are unsupported");return pose(numbers(content(e),6),1000);}
void primitive(Geometry&geometry,Element e,const Mat&m,const std::string&ref,bool sdf,const References&references,Json meta){
  const auto name=tag(e);std::vector<Vec> v;std::vector<std::array<std::size_t,3>> t;
  if(sdf){if(name=="box")children(e,{"size"});else if(name=="cylinder")children(e,{"radius","length"});else if(name=="sphere")children(e,{"radius"});else if(name=="mesh")children(e,{"uri","scale","submesh"});}
  else children(e,{});
  if(name=="box"){const auto dimensions=numbers(sdf?content(child(e,"size",true)):attribute(e,"size"),3);for(auto d:dimensions)require(d>0,"Robot box dimensions must be positive");
    for(unsigned n=0;n<8;++n)v.push_back({(n&1?1:-1)*dimensions[0]*500,(n&2?1:-1)*dimensions[1]*500,(n&4?1:-1)*dimensions[2]*500});t={{0,2,3},{0,3,1},{4,5,7},{4,7,6},{0,1,5},{0,5,4},{2,6,7},{2,7,3},{0,4,6},{0,6,2},{1,3,7},{1,7,5}};meta["primitive"]={{"type","box"},{"size_m",dimensions}};
  }else if(name=="cylinder"){const double r=real(sdf?content(child(e,"radius",true)):attribute(e,"radius"))*1000,length=real(sdf?content(child(e,"length",true)):attribute(e,"length"))*1000;require(r>0&&length>0,"Robot cylinder dimensions must be positive");constexpr unsigned segments=48;
    for(unsigned z=0;z<2;++z)for(unsigned n=0;n<segments;++n){const auto a=2*std::acos(-1)*n/segments;v.push_back({r*std::cos(a),r*std::sin(a),(z?1:-1)*length/2});}v.push_back({0,0,-length/2});v.push_back({0,0,length/2});
    for(unsigned n=0;n<segments;++n){const unsigned next=(n+1)%segments;t.push_back({n,next,n+segments});t.push_back({next,next+segments,n+segments});t.push_back({segments*2,next,n});t.push_back({segments*2+1,n+segments,next+segments});}meta["primitive"]={{"type","cylinder"},{"radius_mm",r},{"length_mm",length}};
  }else if(name=="sphere"){const double r=real(sdf?content(child(e,"radius",true)):attribute(e,"radius"))*1000;require(r>0,"Robot sphere radius must be positive");constexpr unsigned longitude=48,latitude=24;v.push_back({0,0,r});
    for(unsigned y=1;y<latitude;++y)for(unsigned x=0;x<longitude;++x){const double p=std::acos(-1)*y/latitude,a=2*std::acos(-1)*x/longitude;v.push_back({r*std::sin(p)*std::cos(a),r*std::sin(p)*std::sin(a),r*std::cos(p)});}const auto south=v.size();v.push_back({0,0,-r});
    for(unsigned x=0;x<longitude;++x){const auto next=(x+1)%longitude;t.push_back({0,1+x,1+next});for(unsigned y=0;y<latitude-2;++y){const auto a=1+y*longitude+x,b=1+y*longitude+next,c=a+longitude,d=b+longitude;t.push_back({a,c,b});t.push_back({b,c,d});}t.push_back({south,1+(latitude-2)*longitude+next,1+(latitude-2)*longitude+x});}meta["primitive"]={{"type","sphere"},{"radius_mm",r}};
  }else if(name=="mesh"){const auto uri=relative_uri(sdf?content(child(e,"uri",true)):attribute(e,"filename"));require(references.contains(uri),"Robot mesh requires an explicit contained SHA-256 reference: "+uri);const auto&reference=references.at(uri);auto extension=path_to_utf8(reference.path.extension());for(auto&c:extension)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));if(extension!=".stl")unsupported("Robot mesh references currently support STL only");
    if(sdf&&child(e,"submesh"))unsupported("SDF submesh selectors are unsupported");auto parsed=stl(reference.bytes,unit_scale(reference.units));const auto scale=numbers(sdf?(child(e,"scale")?content(child(e,"scale")):"1 1 1"):attribute(e,"scale","1 1 1"),3);auto sm=identity();for(int n=0;n<3;++n)sm[n*4+n]=scale[n];affine(sm);
    for(const auto&p:parsed.geometry.positions)v.push_back({p[0],p[1],p[2]});for(const auto&p:parsed.geometry.triangles)t.push_back({p[0],p[1],p[2]});meta["mesh_uri"]=uri;meta["mesh_sha256"]=reference.hash;geometry.mesh(v,t,product(m,sm),ref,meta);return;
  }else unsupported("Unsupported robot geometry: "+name);
  geometry.mesh(v,t,m,ref,meta);
}
struct Link {std::string name;Element element;Mat pose;};
struct Joint {std::string name,type,parent,child;Mat origin;Json data;};
Json graph(const std::map<std::string,Link>&links,const std::map<std::string,Joint>&joints,std::map<std::string,Mat>&placements,bool urdf){
  require(!links.empty()&&links.size()<=1024&&joints.size()<=1024,"Robot link/joint budget exceeded");std::map<std::string,std::string> parent;std::map<std::string,std::vector<const Joint*>> children;Json jj=Json::array(),ll=Json::array();
  for(const auto&[name,j]:joints){require(links.contains(j.parent)&&links.contains(j.child)&&j.parent!=j.child&&parent.emplace(j.child,j.parent).second,"Robot joint names missing links or repeats a child");children[j.parent].push_back(&j);jj.push_back(j.data);}
  std::vector<std::string> roots;for(const auto&[name,l]:links)if(!parent.contains(name))roots.push_back(name);require(roots.size()==1&&joints.size()+1==links.size(),"Robot review requires one connected tree");std::set<std::string> visited;
  std::function<void(const std::string&,const Mat&,unsigned)> walk=[&](const auto&name,const Mat&m,unsigned depth){require(depth<=64&&visited.insert(name).second,"Robot graph cycle or depth limit");placements[name]=urdf?m:links.at(name).pose;ll.push_back({{"name",name},{"rest_transform_mm",placements[name]}});for(auto j:children[name])walk(j->child,product(m,j->origin),depth+1);};walk(roots.front(),links.at(roots.front()).pose,0);require(visited.size()==links.size(),"Disconnected robot links");
  return {{"root",roots.front()},{"links",ll},{"joints",jj},{"configuration","zero_joint_coordinates"},{"simulation_validated",false}};
}
Parsed urdf(const tinyxml2::XMLDocument&xml,const References&references){
  const auto root=xml.RootElement();require(tag(root)=="robot"&&!attribute(root,"name").empty(),"URDF requires a named robot");if(attribute(root,"version","1.0")!="1.0")unsupported("This review subset accepts URDF 1.0 only");children(root,{"link","joint","material"});std::map<std::string,Link> links;std::map<std::string,Joint> joints;
  for(auto e=root->FirstChildElement();e;e=e->NextSiblingElement()){const auto name=attribute(e,"name");if(tag(e)=="material")continue;require(!name.empty(),"Robot link/joint name missing");
    if(tag(e)=="link"){children(e,{"visual","collision","inertial"});require(links.emplace(name,Link{name,e,identity()}).second,"Duplicate URDF link");}
    else{children(e,{"parent","child","origin","axis","limit","dynamics","mimic","safety_controller","calibration"});if(child(e,"mimic"))unsupported("URDF mimic coordinates need another configuration backend");const auto type=attribute(e,"type");if(type!="fixed"&&type!="revolute"&&type!="continuous"&&type!="prismatic")unsupported("Unsupported URDF joint type: "+type);
      Joint joint{name,type,attribute(child(e,"parent",true),"link"),attribute(child(e,"child",true),"link"),urdf_origin(child(e,"origin")),{{"name",name},{"type",type}}};joint.data["parent"]=joint.parent;joint.data["child"]=joint.child;
      const auto axis=numbers(child(e,"axis")?attribute(child(e,"axis"),"xyz"):"1 0 0",3);double norm=0;for(auto a:axis)norm+=a*a;require(norm>0,"URDF joint axis is zero");joint.data["axis"]=axis;
      if(auto limit=child(e,"limit")){Json data=Json::object();for(const auto*key:{"lower","upper","effort","velocity"})if(limit->Attribute(key))data[key]=real(attribute(limit,key));joint.data["limits"]=data;}require(joints.emplace(name,joint).second,"Duplicate URDF joint");}}
  Parsed parsed;parsed.representation="robot_description";std::map<std::string,Mat> placements;parsed.metadata={{"format","urdf"},{"name",attribute(root,"name")},{"graph",graph(links,joints,placements,true)}};
  for(const auto&[name,link]:links)for(const auto*role:{"visual","collision"}){unsigned ordinal=0;for(auto e=link.element->FirstChildElement(role);e;e=e->NextSiblingElement(role)){children(e,{"origin","geometry","material"});const auto geo=child(e,"geometry",true);require(geo->FirstChildElement()&&!geo->FirstChildElement()->NextSiblingElement(),"URDF geometry needs exactly one primitive");primitive(parsed.geometry,geo->FirstChildElement(),product(placements.at(name),urdf_origin(child(e,"origin"))),"links/"+name+"/"+role+"/"+std::to_string(ordinal++),false,references,{{"link",name},{"role",role}});}}
  parsed.limitations.push_back("URDF 1.0 visual and collision geometry is shown together at zero joint coordinates. Dynamics, collisions, joint-limit adequacy, controllers and simulation behavior are not validated; mesh references require explicit contained STL snapshots.");return parsed;
}
Parsed sdf(const tinyxml2::XMLDocument&xml,const References&references){
  const auto root=xml.RootElement();require(tag(root)=="sdf","SDF requires an sdf root");const auto version=attribute(root,"version");if(version!="1.6"&&version!="1.7"&&version!="1.8"&&version!="1.9"&&version!="1.10"&&version!="1.11"&&version!="1.12")unsupported("Unsupported SDF specification version");children(root,{"model"});const auto model=child(root,"model",true);children(model,{"pose","link","joint","static","self_collide","allow_auto_disable"});const auto model_pose=sdf_pose(child(model,"pose"));std::map<std::string,Link> links;std::map<std::string,Joint> joints;
  for(auto e=model->FirstChildElement();e;e=e->NextSiblingElement()){const auto type=tag(e);if(type!="link"&&type!="joint")continue;const auto name=attribute(e,"name");require(!name.empty(),"Missing SDF link/joint name");
    if(type=="link"){children(e,{"pose","visual","collision","inertial","gravity","self_collide","kinematic","enable_wind"});require(links.emplace(name,Link{name,e,product(model_pose,sdf_pose(child(e,"pose")))}).second,"Duplicate SDF link");}
    else{children(e,{"parent","child","pose","axis","axis2","physics"});const auto jt=attribute(e,"type");if(jt!="fixed"&&jt!="revolute"&&jt!="prismatic")unsupported("Unsupported SDF joint type: "+jt);if(child(e,"axis2"))unsupported("SDF second axes are unsupported");sdf_pose(child(e,"pose"));Joint j{name,jt,content(child(e,"parent",true)),content(child(e,"child",true)),identity(),{{"name",name},{"type",jt}}};j.data["parent"]=j.parent;j.data["child"]=j.child;require(joints.emplace(name,j).second,"Duplicate SDF joint");}}
  Parsed parsed;parsed.representation="robot_description";std::map<std::string,Mat> placements;auto g=graph(links,joints,placements,false);g["configuration"]="declared_link_poses";parsed.metadata={{"format","sdf"},{"name",attribute(model,"name")},{"version",version},{"graph",g}};
  for(const auto&[name,link]:links)for(const auto*role:{"visual","collision"}){unsigned ordinal=0;for(auto e=link.element->FirstChildElement(role);e;e=e->NextSiblingElement(role)){children(e,{"pose","geometry","material","cast_shadows","transparency","surface","laser_retro","max_contacts"});const auto geo=child(e,"geometry",true);require(geo->FirstChildElement()&&!geo->FirstChildElement()->NextSiblingElement(),"SDF geometry needs exactly one primitive");primitive(parsed.geometry,geo->FirstChildElement(),product(placements.at(name),sdf_pose(child(e,"pose"))),"links/"+name+"/"+role+"/"+std::to_string(ordinal++),true,references,{{"link",name},{"role",role}});}}
  parsed.limitations.push_back("One SDF model uses declared link poses with primitive or explicit contained STL geometry. Worlds, nested models, includes, plugins and named pose frames are unsupported; simulation, contacts and physical readiness are not validated.");return parsed;
}
Parsed srdf(const tinyxml2::XMLDocument&xml){
  const auto root=xml.RootElement();require(tag(root)=="robot"&&!attribute(root,"name").empty(),"SRDF requires a named robot");children(root,{"group","group_state","end_effector","virtual_joint","disable_collisions","passive_joint"});Json groups=Json::array(),states=Json::array(),collisions=Json::array(),other=Json::array();std::set<std::string> names;
  for(auto e=root->FirstChildElement();e;e=e->NextSiblingElement()){const auto kind=tag(e);Json item={{"element",kind}};for(auto a=e->FirstAttribute();a;a=a->Next())item[a->Name()]=a->Value();
    if(kind=="group"){const auto name=attribute(e,"name");require(!name.empty()&&names.insert(name).second&&names.size()<=1024,"Duplicate or missing SRDF group name");children(e,{"link","joint","chain","group"});item["members"]=Json::array();for(auto c=e->FirstChildElement();c;c=c->NextSiblingElement()){Json member={{"element",tag(c)}};for(auto a=c->FirstAttribute();a;a=a->Next())member[a->Name()]=a->Value();item["members"].push_back(member);}groups.push_back(item);}
    else if(kind=="group_state"){children(e,{"joint"});item["joints"]=Json::array();for(auto c=e->FirstChildElement();c;c=c->NextSiblingElement()){const auto v=attribute(c,"value");std::istringstream stream(v);std::string token;Json values=Json::array();while(stream>>token){require(values.size()<6,"SRDF state joint value budget exceeded");values.push_back(real(token));}require(!values.empty(),"SRDF joint state value missing");item["joints"].push_back({{"name",attribute(c,"name")},{"values",values}});}states.push_back(item);}
    else if(kind=="disable_collisions")collisions.push_back(item);else other.push_back(item);}
  std::map<std::string,Json> by_name;for(const auto&g:groups)by_name[g.at("name")]=g;std::set<std::string> active,done;std::function<void(const std::string&,unsigned)> visit=[&](const auto&name,unsigned depth){require(depth<=64&&by_name.contains(name),"Missing SRDF subgroup or depth budget");if(done.contains(name))return;require(active.insert(name).second,"Cyclic SRDF subgroups");for(const auto&m:by_name[name].at("members"))if(m.at("element")=="group"){require(m.contains("name"),"Missing SRDF subgroup name");visit(m.at("name"),depth+1);}active.erase(name);done.insert(name);};for(const auto&name:names)visit(name,0);
  for(const auto&s:states)require(s.contains("group")&&names.contains(s.at("group")),"SRDF state references missing group");Parsed parsed;parsed.representation="robot_semantics";parsed.metadata={{"format","srdf"},{"name",attribute(root,"name")},{"groups",groups},{"states",states},{"disabled_collisions",collisions},{"other_declarations",other},{"robot_names_qualified",false}};
  parsed.limitations.push_back("SRDF is semantic data and has no standalone shape. Link/joint names are unqualified until paired with the intended URDF; planning, collision exemptions and saved-state feasibility are not validated.");return parsed;
}
}
Parsed robot(const std::string&bytes,const std::string&format,const References&references){tinyxml2::XMLDocument xml;safe_xml(xml,bytes);plain(xml.RootElement());if(format=="urdf")return urdf(xml,references);if(format=="sdf")return sdf(xml,references);return srdf(xml);}
}
