#include "agentcad/mesh_reconstruction.hpp"
#include "agentcad/artifact_review.hpp"
#include "agentcad/kernel.hpp"
#include "agentcad/jobs.hpp"
#include "agentcad/model.hpp"
#include "agentcad/hash.hpp"
#include <set>
namespace agentcad {
namespace {
Json obj(Json properties,Json required){return {{"type","object"},{"properties",properties},{"required",required},{"additionalProperties",false}};}
void bound(const Json& j,const char* key,double low,double high){const auto n=number(j.at(key));if(n<low||n>high)throw Error("invalid_argument",std::string(key)+" is outside recognition limits");}
void integer(const Json& j,const char* key,int low,int high){bound(j,key,low,high);if(!j.at(key).is_number_integer())throw Error("invalid_argument",std::string(key)+" must be an integer");}
}
Json mesh_reconstruction_definitions(){
  const Json real={{"type","number"}},text={{"type","string"}},positive={{"type","number"},{"minimum",0}},hash={{"type","string"},{"pattern","^[a-f0-9]{64}$"}};
  const auto list=[](Json item,int maximum){return Json{{"type","array"},{"items",item},{"maxItems",maximum}};};
  const auto tuple=[&](int size){auto v=list(real,size);v["minItems"]=size;return v;};const auto xyz=tuple(3),pair=tuple(2);auto rectangle=list(pair,2);rectangle["minItems"]=2;
  const auto options=obj({{"distance_tolerance_mm",{{"type","number"},{"minimum",1e-6},{"maximum",10}}},{"normal_tolerance_deg",{{"type","number"},{"minimum",.01},{"maximum",45}}},{"weld_tolerance_mm",{{"type","number"},{"minimum",0},{"maximum",1}}},{"min_triangles",{{"type","integer"},{"minimum",2},{"maximum",10000}}},{"max_patches",{{"type","integer"},{"minimum",1},{"maximum",64}}},{"max_candidates",{{"type","integer"},{"minimum",8},{"maximum",512}}}}, {"distance_tolerance_mm","normal_tolerance_deg","weld_tolerance_mm","min_triangles","max_patches","max_candidates"});
  auto guide=obj({{"patch_id",text},{"feature_id",{{"type","string"},{"pattern","^[A-Za-z][A-Za-z0-9_-]{0,39}$"}}},{"extent",{{"enum",{"rectangle","cylinder","sphere"}}}},{"bounds_uv_mm",rectangle},{"thickness_mm",{{"type","number"},{"minimum",1e-5},{"maximum",1e6}}},{"axis_range_mm",pair}}, {"patch_id","feature_id","extent"});
  guide["oneOf"]=Json::array({Json{{"properties",{{"extent",{{"const","rectangle"}}}}},{"required",{"bounds_uv_mm","thickness_mm"}},{"not",{{"required",{"axis_range_mm"}}}}},Json{{"properties",{{"extent",{{"const","cylinder"}}}}},{"required",{"axis_range_mm"}},{"not",{{"anyOf",Json::array({Json{{"required",{"bounds_uv_mm"}}},Json{{"required",{"thickness_mm"}}}})}}}},Json{{"properties",{{"extent",{{"const","sphere"}}}}},{"not",{{"anyOf",Json::array({Json{{"required",{"bounds_uv_mm"}}},Json{{"required",{"thickness_mm"}}},Json{{"required",{"axis_range_mm"}}}})}}}}});
  const auto arguments=obj({{"action",{{"const","recognize"}}},{"review_path",text},{"expected_sha256",hash},{"options",options},{"reconstruct",list(guide,16)}},{"action","review_path","expected_sha256","options"});
  const Json index={{"type","integer"},{"minimum",0},{"maximum",199999}};const auto indices=list(index,200000);
  const auto analytic=obj({{"kind",{{"enum",{"plane","cylinder","sphere"}}}},{"origin_mm",xyz},{"axis",xyz},{"x_direction",xyz},{"radius_mm",positive}}, {"kind","origin_mm","axis","x_direction","radius_mm"});
  const auto residual=obj({{"max_distance_mm",positive},{"vertex_rms_distance_mm",positive},{"max_normal_deviation_deg",positive},{"worst_triangle",index},{"method",{{"const","full_triangle_distance_extrema_and_normal_cone"}}}}, {"max_distance_mm","vertex_rms_distance_mm","max_normal_deviation_deg","worst_triangle","method"});
  const auto patch=obj({{"id",text},{"analytic",analytic},{"triangle_indices",indices},{"triangle_count",{{"type","integer"},{"minimum",2},{"maximum",200000}}},{"area_mm2",positive},{"area_fraction",{{"type","number"},{"minimum",0},{"maximum",1}}},{"residual",residual},{"observed_bounds_uv_mm",rectangle},{"axis_range_mm",pair}}, {"id","analytic","triangle_indices","triangle_count","area_mm2","area_fraction","residual","observed_bounds_uv_mm","axis_range_mm"});
  const auto proposal=obj({{"patch_id",text},{"model",{{"$ref","#/$defs/model"}}},{"operations",{{"type","array"},{"items",{{"$ref","#/$defs/operation"}}},{"maxItems",16}}},{"summary",{{"$ref","#/$defs/reconstruction_summary"}}},{"extrapolation",text},{"exact_geometry_validated",{{"const",true}}}}, {"patch_id","model","operations","summary","extrapolation","exact_geometry_validated"});
  const auto result=obj({{"action",{{"const","recognize"}}},{"source_sha256",hash},{"review_sha256",hash},{"kernel_version",{{"const","8.0.1"}}},{"units",{{"const","mm"}}},{"read_only",{{"const",true}}},{"editable_history_recovered",{{"const",false}}},{"options",options},{"patches",list(patch,64)},{"proposals",list(proposal,16)},{"leftover_triangle_indices",indices},{"leftover_area_mm2",positive},{"total_area_mm2",positive},{"recognized_area_fraction",{{"type","number"},{"minimum",0},{"maximum",1}}},{"candidates_examined",{{"type","integer"},{"minimum",0},{"maximum",512}}},{"search_budget_exhausted",{{"type","boolean"}}},{"limitations",list(text,8)}}, {"action","source_sha256","review_sha256","kernel_version","units","read_only","editable_history_recovered","options","patches","proposals","leftover_triangle_indices","leftover_area_mm2","total_area_mm2","recognized_area_fraction","candidates_examined","search_budget_exhausted","limitations"});
  return {{"mesh_recognition_arguments",arguments},{"mesh_recognition_result",result}};
}
void validate_mesh_recognition(const Json& args){
  fields(args,{"action","review_path","expected_sha256","options"},{"reconstruct"});const auto path=path_from_utf8(text_field(args,"review_path"));const auto hash=text_field(args,"expected_sha256");if(args.at("action")!="recognize"||!path.is_absolute()||path.filename()!="review.json"||hash.size()!=64||hash.find_first_not_of("0123456789abcdef")!=std::string::npos)throw Error("invalid_argument","Recognition requires absolute review.json and its SHA-256");
  const auto& o=args.at("options");fields(o,{"distance_tolerance_mm","normal_tolerance_deg","weld_tolerance_mm","min_triangles","max_patches","max_candidates"});bound(o,"distance_tolerance_mm",1e-6,10);bound(o,"normal_tolerance_deg",.01,45);bound(o,"weld_tolerance_mm",0,std::min(1.,number(o.at("distance_tolerance_mm"))));integer(o,"min_triangles",2,10000);integer(o,"max_patches",1,64);integer(o,"max_candidates",8,512);
  if(args.contains("reconstruct")){const auto& guides=args.at("reconstruct");if(!guides.is_array()||guides.size()>16)throw Error("invalid_argument","At most 16 reconstruction guides are permitted");std::set<std::string> ids,patches;for(const auto& g:guides){fields(g,{"patch_id","feature_id","extent"},{"bounds_uv_mm","thickness_mm","axis_range_mm"});const auto id=text_field(g,"feature_id"),patch=text_field(g,"patch_id"),extent=text_field(g,"extent");model_identifier(id);if(id.size()>40||!ids.insert(id).second||!patches.insert(patch).second||patch.size()>160)throw Error("invalid_argument","Duplicate or invalid reconstruction guide identity");
    if(extent=="rectangle"){fields(g,{"patch_id","feature_id","extent","bounds_uv_mm","thickness_mm"});bound(g,"thickness_mm",1e-5,1e6);const auto& b=g.at("bounds_uv_mm");if(!b.is_array()||b.size()!=2)throw Error("invalid_argument","Rectangle requires two UV corners");for(const auto& p:b){if(!p.is_array()||p.size()!=2)throw Error("invalid_argument","UV points require two numbers");for(const auto& n:p)number(n);}if(number(b[1][0])-number(b[0][0])<1e-5||number(b[1][1])-number(b[0][1])<1e-5)throw Error("invalid_argument","Rectangle bounds must increase");}
    else if(extent=="cylinder"){fields(g,{"patch_id","feature_id","extent","axis_range_mm"});const auto& r=g.at("axis_range_mm");if(!r.is_array()||r.size()!=2||number(r[1])-number(r[0])<1e-5)throw Error("invalid_argument","Cylinder requires increasing axial bounds");}
    else if(extent=="sphere")fields(g,{"patch_id","feature_id","extent"});else throw Error("invalid_argument","Unsupported reconstruction extent");}}
}
Json recognize_mesh_artifact(const fs::path& workspace,const Json& args){
  validate_mesh_recognition(args);const auto path=path_from_utf8(text_field(args,"review_path"));const auto expected=text_field(args,"expected_sha256");const auto verified=verify_external_artifact(path.parent_path(),expected);if(verified.at("summary").at("representation")!="triangle_mesh")throw Error("invalid_argument","Analytic recognition requires a captured STL, GLB or 3MF mesh");
  const auto raw=read_text(path,64*1024*1024);if(sha256(raw)!=expected)throw Error("artifact_mismatch","Review changed before recognition");const auto review=parse_json(raw,64*1024*1024);
  const Json model={{"schema_version",1},{"units","mm"},{"parameters",Json::object()},{"features",Json::array({{{"id","workerContext"},{"type","box"},{"size",{1,1,1}}}})},{"output","workerContext"}};
  auto result=evaluate_model(workspace,model,{{"kind","recognize_mesh"},{"mesh",review.at("geometry")},{"options",args.at("options")},{"guides",args.value("reconstruct",Json::array())},{"source_sha256",review.at("source").at("sha256")},{"review_sha256",expected}});
  // Publication stays outside the worker and rechecks every captured source byte.
  verify_external_artifact(path.parent_path(),expected);return result;
}
}
