#include "agentcad/viewer.hpp"

namespace agentcad {
std::string viewer_html(const Json& evaluation) {
  auto data = evaluation.dump();
  std::size_t position = 0;
  while ((position = data.find('<', position)) != std::string::npos) {
    data.replace(position, 1, "\\u003c"); position += 6;
  }
  return R"HTML(<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'">
<title>CAD review</title>
<style>
:root{color-scheme:dark;font:14px system-ui,sans-serif;color:#e2e9ef;background:#101820}*{box-sizing:border-box}body{margin:0}header{height:80px;border-bottom:1px solid #34414c;display:flex;align-items:center;padding:18px 28px;gap:24px}h1{font-size:20px;margin:0;letter-spacing:-.4px}.brand{color:#5be0b7;font-weight:700;font-size:12px;letter-spacing:1.2px}#identity{font-size:12px;color:#a5b5c4;margin-top:5px}main{display:grid;grid-template-columns:minmax(0,1fr) 340px;height:calc(100vh - 80px)}.viewport{position:relative;min-height:300px;background:radial-gradient(ellipse at 45% 40%,#263744,#101820)}canvas{display:block;width:100%;height:100%;touch-action:none;outline-offset:-4px}aside{padding:24px;border-left:1px solid #34414c;overflow:auto;background:#16212b}h2{font-size:15px;margin:24px 0 12px}h2:first-child{margin-top:0}p{color:#a5b5c4;line-height:1.6}button,.file{background:#263744;border:1px solid #4a6070;border-radius:6px;color:#eef7ff;padding:9px 12px;font:inherit;cursor:pointer;display:inline-block}button:hover,.file:hover{background:#364d5e}button[aria-pressed=true]{border-color:#5be0b7;color:#5be0b7}button:disabled{opacity:.4;cursor:default}.tools{display:flex;gap:8px;flex-wrap:wrap}.help{position:absolute;left:22px;bottom:16px;color:#b9c8d2;font-size:12px;pointer-events:none}.badge{position:absolute;top:20px;left:22px;padding:6px 10px;background:#132c29;color:#75efc8;border:1px solid #2c6859;border-radius:5px}.draft{color:#ffd088;background:#392c14;border-color:#8f7135}pre{white-space:pre-wrap;word-break:break-word;font:11px/1.5 ui-monospace,monospace;background:#101820;border:1px solid #34414c;padding:12px;border-radius:5px;max-height:320px;overflow:auto}dl{display:grid;grid-template-columns:1fr auto;gap:9px;font-size:13px}dt{color:#a5b5c4}dd{margin:0}#notice{min-height:24px;color:#ffd088;font-size:12px}input[type=file]{display:none}@media(max-width:750px){main{grid-template-columns:1fr;height:auto}.viewport{height:60vh}aside{border-left:0;border-top:1px solid #34414c}header{padding:15px}.help{font-size:10px}}
</style>
<header><span class="brand">AGENT / CAD</span><div><h1 id="title"></h1><div id="identity"></div></div></header>
<main><div class="viewport"><canvas id="canvas" tabindex="0" aria-label="Interactive CAD model. Drag to orbit, scroll to zoom, click to select. Use arrow keys to orbit."></canvas><div class="badge" id="badge"></div><div class="help">Drag to orbit · Scroll to zoom · Click to select · Arrow keys to orbit</div></div>
<aside><h2>Inspect geometry</h2><div class="tools"><button id="faces" aria-pressed="true">Faces</button><button id="edges" aria-pressed="false">Edges</button><button id="reset">Reset view</button></div><dl id="facts"></dl><h2>Selection</h2><p id="hint">Pick a face or edge to inspect its measurements and share its reference with an agent.</p><pre id="selection" hidden></pre><div class="tools"><button id="copy" disabled>Copy reference</button><button id="save" disabled>Save reference</button></div><p id="notice" role="status" aria-live="polite"></p><h2>Open another revision</h2><p>Load a saved .view.json to review an updated model here. Each pick belongs to its displayed revision and evaluation.</p><label class="file">Load view file<input id="load" type="file" accept=".json"></label><p>This artifact works offline. Dimensions use millimeters.</p></aside></main>
<script id="cad-data" type="application/json">)HTML" + data + R"HTML(</script>
<script>
'use strict';
let data=JSON.parse(document.getElementById('cad-data').textContent), mode='faces', yaw=-.65, pitch=.55, zoom=1, chosen=null, projected=[], edgeLines=[], drag=null;
const $=id=>document.getElementById(id), canvas=$('canvas'), ctx=canvas.getContext('2d');
function text(id,value){$(id).textContent=value;}
function load(d){valid(d);data=d;chosen=null;yaw=-.65;pitch=.55;zoom=1;text('title',String(data.document_id));text('identity','Revision '+data.revision+' · '+data.feature_id+' · '+data.evaluation_id);text('badge',data.draft?'DRAFT PREVIEW':'COMMITTED REVISION '+data.revision);$('badge').className='badge'+(data.draft?' draft':'');const s=data.summary;$('facts').replaceChildren();for(const [label,value] of [['Volume',Number(s.volume_mm3).toFixed(2)+' mm³'],['Area',Number(s.area_mm2).toFixed(2)+' mm²'],['Faces',s.face_count],['Edges',s.edge_count]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('facts').append(dt,dd);}selection(null);draw();}
function project(p){const b=data.summary.bounds_mm,c=b.min.map((v,i)=>(v+b.max[i])/2),span=Math.max(...b.min.map((v,i)=>b.max[i]-v),1e-6);let [x,y,z]=p.map((v,i)=>v-c[i]);const a=x*Math.cos(yaw)-y*Math.sin(yaw),v=x*Math.sin(yaw)+y*Math.cos(yaw),h=v*Math.sin(pitch)+z*Math.cos(pitch),depth=v*Math.cos(pitch)-z*Math.sin(pitch),scale=Math.min(canvas.clientWidth,canvas.clientHeight)*.64*zoom/span;return [canvas.clientWidth/2+a*scale,canvas.clientHeight/2-h*scale,depth];}
// BEGIN PURE RENDERER
function valid(d){
 if(!d||d.schema_version!==1||!d.mesh||!d.topology||!d.summary)throw Error('Unsupported view file');
 const m=d.mesh,t=d.topology,point=p=>Array.isArray(p)&&p.length===3&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<=1e12),b=d.summary.bounds_mm;
 if(!b||!point(b.min)||!point(b.max)||b.min.some((v,i)=>v>b.max[i]))throw Error('Invalid bounds');
 const span=Math.max(...b.min.map((v,i)=>b.max[i]-v));if(!Number.isFinite(span)||span<=0)throw Error('Invalid bounds');
 const inside=p=>point(p)&&p.every((v,i)=>v>=b.min[i]-1e-5&&v<=b.max[i]+1e-5);
 if(!Array.isArray(m.positions)||m.positions.length>200000||!m.positions.every(inside)||!Array.isArray(m.triangles)||m.triangles.length>200000||!m.triangles.every(v=>Array.isArray(v)&&v.length===3&&v.every(i=>Number.isInteger(i)&&i>=0&&i<m.positions.length))||!Array.isArray(t.faces)||!Array.isArray(t.edges)||t.faces.length+t.edges.length>10000)throw Error('Invalid or oversized mesh');
 const faces=new Set(),edges=new Set();for(const f of t.faces){if(!f||typeof f.id!=='string'||!/^face-[1-9][0-9]*$/.test(f.id)||faces.has(f.id))throw Error('Invalid face identity');faces.add(f.id);}for(const e of t.edges){if(!e||typeof e.id!=='string'||!/^edge-[1-9][0-9]*$/.test(e.id)||edges.has(e.id))throw Error('Invalid edge identity');edges.add(e.id);}
 if(!Array.isArray(m.triangle_faces)||m.triangle_faces.length!==m.triangles.length||!m.triangle_faces.every(id=>faces.has(id))||!Array.isArray(m.edges)||m.edges.length>10000)throw Error('Invalid topology mapping');
 let points=0;const seen=new Set();for(const e of m.edges){if(!e||!edges.has(e.id)||seen.has(e.id)||!Array.isArray(e.points)||!e.points.every(inside))throw Error('Invalid edge mapping');seen.add(e.id);points+=e.points.length;if(points>200000)throw Error('Edge payload exceeds its limit');}
 return d;
}
function depthAt(frame,x,y){const px=Math.floor(x),py=Math.floor(y);if(px<0||py<0||px>=frame.width||py>=frame.height)return Infinity;const index=py*frame.width+px,triangle=frame.triangles[index];if(triangle<0)return frame.depth[index];const [a,b,c,den]=frame.planes[triangle],wa=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/den,wb=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/den;return wa*a[2]+wb*b[2]+(1-wa-wb)*c[2];}
function rasterize(mesh,points,width,height,selected){
 if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width*height>4000000)throw Error('Viewport exceeds the rendering limit');
 let samples=0;const size=width*height,depth=new Float64Array(size),triangles=new Int32Array(size),pixels=new Uint8ClampedArray(size*4),planes=[];depth.fill(Infinity);triangles.fill(-1);
 for(let i=0;i<mesh.triangles.length;i++){
  const t=mesh.triangles[i],[a,b,c]=t.map(j=>points[j]),den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);
  planes[i]=[a,b,c,den];if(Math.abs(den)<1e-10)continue;
  const minX=Math.max(0,Math.floor(Math.min(a[0],b[0],c[0]))),maxX=Math.min(width-1,Math.ceil(Math.max(a[0],b[0],c[0]))),minY=Math.max(0,Math.floor(Math.min(a[1],b[1],c[1]))),maxY=Math.min(height-1,Math.ceil(Math.max(a[1],b[1],c[1])));
  samples+=Math.max(0,maxX-minX+1)*Math.max(0,maxY-minY+1);if(samples>50000000)throw Error('Model exceeds the rendering limit; inspect a specific feature');
  const u=mesh.positions[t[0]],v=mesh.positions[t[1]],q=mesh.positions[t[2]],e=v.map((x,j)=>x-u[j]),f=q.map((x,j)=>x-u[j]),n=[e[1]*f[2]-e[2]*f[1],e[2]*f[0]-e[0]*f[2],e[0]*f[1]-e[1]*f[0]],l=Math.hypot(...n)||1,shade=.4+.6*Math.abs((n[0]*.3+n[1]*-.5+n[2]*.8)/l),color=selected&&selected.kind==='face'&&selected.id===mesh.triangle_faces[i]?[79,224,176]:[82*shade,159*shade,189*shade];
  for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){
   const px=x+.5,py=y+.5,wa=((b[1]-c[1])*(px-c[0])+(c[0]-b[0])*(py-c[1]))/den,wb=((c[1]-a[1])*(px-c[0])+(a[0]-c[0])*(py-c[1]))/den,wc=1-wa-wb;
   if(wa< -1e-10||wb< -1e-10||wc< -1e-10)continue;
   const z=wa*a[2]+wb*b[2]+wc*c[2],index=y*width+x,tolerance=1e-10*Math.max(1,Math.abs(z));
   if(Math.abs(z-depth[index])<=tolerance){const prior=triangles[index];if(prior>=0&&mesh.triangle_faces[prior]!==mesh.triangle_faces[i])triangles[index]=-2;continue;}
   if(z>=depth[index])continue;
   depth[index]=z;triangles[index]=i;const offset=index*4;pixels[offset]=color[0];pixels[offset+1]=color[1];pixels[offset+2]=color[2];pixels[offset+3]=255;
  }
 }
 return {width,height,depth,triangles,pixels,planes};
}
function nearestSegment(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1)));return {x:a[0]+t*dx,y:a[1]+t*dy,z:a[2]+t*(b[2]-a[2]),distance:Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy)};}
function edgePick(p,edges,frame,tolerance,allowance=0){let best=9,depth=Infinity,id=null,ambiguous=false;for(const edge of edges)for(let i=1;i<edge.points.length;i++){const q=nearestSegment(p,edge.points[i-1],edge.points[i]);if(q.distance>=9||q.z>depthAt(frame,q.x,q.y)+tolerance+allowance)continue;if(q.distance<best-1e-6||(Math.abs(q.distance-best)<=1e-6&&q.z<depth-tolerance)){best=q.distance;depth=q.z;id=edge.id;ambiguous=false;}else if(id!==edge.id&&Math.abs(q.distance-best)<=1e-6&&Math.abs(q.z-depth)<=tolerance)ambiguous=true;}return {id,ambiguous};}
function clipSegment(a,b,width,height){
 if(!a.every(Number.isFinite)||!b.every(Number.isFinite))return null;
 const dx=b[0]-a[0],dy=b[1]-a[1];if(!Number.isFinite(dx)||!Number.isFinite(dy))return null;
 let lo=0,hi=1;for(const [p,q] of [[-dx,a[0]],[dx,width-1-a[0]],[-dy,a[1]],[dy,height-1-a[1]]]){if(p===0){if(q<0)return null;continue;}const r=q/p;if(p<0)lo=Math.max(lo,r);else hi=Math.min(hi,r);if(lo>hi)return null;}
 const at=t=>a.map((v,i)=>v+t*(b[i]-v));return [at(lo),at(hi)];
}
function renderEdges(edges,frame,selected,edgeMode,tolerance,allowance=0){let samples=0;for(const edge of edges){const active=selected&&selected.kind==='edge'&&selected.id===edge.id,color=active?[255,208,136]:edgeMode?[190,212,223]:[49,73,87],radius=active?2:0;for(let i=1;i<edge.points.length;i++){const clipped=clipSegment(edge.points[i-1],edge.points[i],frame.width,frame.height);if(!clipped)continue;const [a,b]=clipped,steps=Math.max(1,Math.ceil(Math.max(Math.abs(a[0]-b[0]),Math.abs(a[1]-b[1]))));samples+=steps+1;if(samples>4000000)throw Error('Edges exceed the rendering limit; inspect a specific feature');for(let j=0;j<=steps;j++){const t=j/steps,sx=a[0]+t*(b[0]-a[0]),sy=a[1]+t*(b[1]-a[1]),x=Math.floor(sx),y=Math.floor(sy),z=a[2]+t*(b[2]-a[2]);if(z>depthAt(frame,sx,sy)+tolerance+allowance)continue;for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){const px=x+dx,py=y+dy;if(px<0||py<0||px>=frame.width||py>=frame.height)continue;const offset=(py*frame.width+px)*4;frame.pixels[offset]=color[0];frame.pixels[offset+1]=color[1];frame.pixels[offset+2]=color[2];frame.pixels[offset+3]=255;}}}}}
function pickDepthTolerance(bounds){const span=Math.max(...bounds.min.map((v,i)=>bounds.max[i]-v),1);return Math.min(1e-4,Math.max(1e-7,span*Number.EPSILON*16));}
function pickDepthAllowance(deflection){return typeof deflection==='number'&&Number.isFinite(deflection)&&deflection>0&&deflection<=1e6?2*deflection:0;}
// END PURE RENDERER
let frame=null,depthTolerance=1e-7,depthAllowance=0,renderScale=1;
function draw(){if(!data.mesh)return;try{renderScale=Math.min(1,1900/canvas.clientWidth,1900/canvas.clientHeight);const w=Math.max(1,Math.round(canvas.clientWidth*renderScale)),h=Math.max(1,Math.round(canvas.clientHeight*renderScale)),screen=p=>project(p).map((v,i)=>i<2?v*renderScale:v);canvas.width=w;canvas.height=h;projected=data.mesh.positions.map(screen);frame=rasterize(data.mesh,projected,w,h,chosen);edgeLines=data.mesh.edges.map(e=>({id:e.id,points:e.points.map(screen)}));const bounds=data.summary.bounds_mm;depthTolerance=pickDepthTolerance(bounds);depthAllowance=pickDepthAllowance(data.mesh.linear_deflection_mm);renderEdges(edgeLines,frame,chosen,mode==='edges',depthTolerance,depthAllowance);ctx.putImageData(new ImageData(frame.pixels,w,h),0,0);}catch(error){frame=null;selection(null);ctx.clearRect(0,0,canvas.width,canvas.height);text('notice',error.message);}}

function pick(x,y){if(!frame)return;x*=renderScale;y*=renderScale;let id,ambiguous=false;if(mode==='faces'){const px=Math.floor(x),py=Math.floor(y),index=px>=0&&py>=0&&px<frame.width&&py<frame.height?frame.triangles[py*frame.width+px]:-1;ambiguous=index===-2;if(index>=0)id=data.mesh.triangle_faces[index];}else{const picked=edgePick([x,y],edgeLines,frame,depthTolerance,depthAllowance);id=picked.id;ambiguous=picked.ambiguous;}selection(id&&!ambiguous?{kind:mode==='faces'?'face':'edge',id}:null);if(ambiguous)text('notice','Geometry overlaps at this point. Rotate the view or inspect a specific feature.');draw();}
function selection(s){chosen=s;$('selection').hidden=!s;$('copy').disabled=$('save').disabled=!s;text('notice','');if(!s){text('hint','Pick a face or edge to inspect its measurements and share its reference with an agent.');return;}const entity=data.topology[s.kind==='face'?'faces':'edges'].find(e=>e.id===s.id);const reference={document_id:data.document_id,revision:data.revision,evaluation_id:data.evaluation_id,feature_id:data.feature_id,kind:s.kind,entity_id:s.id};chosen.reference=reference;text('hint',data.draft?'Draft selections are for inspection. Build a committed revision before resolving a design reference.':'Send this reference to cad_resolve_selection to obtain measurements and available design intent.');text('selection',JSON.stringify({reference,geometry:entity},null,2));}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.offsetX,y:e.offsetY,lastX:e.offsetX,lastY:e.offsetY,moved:false};});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.offsetX-drag.lastX,dy=e.offsetY-drag.lastY;if(Math.hypot(e.offsetX-drag.x,e.offsetY-drag.y)>4)drag.moved=true;if(drag.moved){yaw+=dx*.008;pitch=Math.max(-1.5,Math.min(1.5,pitch+dy*.008));draw();}drag.lastX=e.offsetX;drag.lastY=e.offsetY;});canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved)pick(e.offsetX,e.offsetY);drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.1,Math.min(20,zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});canvas.addEventListener('keydown',e=>{if(e.key.startsWith('Arrow')){e.preventDefault();yaw+=e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0;pitch+=e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0;draw();}});
for(const m of ['faces','edges'])$(m).onclick=()=>{mode=m;$('faces').setAttribute('aria-pressed',m==='faces');$('edges').setAttribute('aria-pressed',m==='edges');selection(null);draw();};$('reset').onclick=()=>{yaw=-.65;pitch=.55;zoom=1;draw();};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(chosen.reference,null,2));text('notice','Reference copied.');}catch{text('notice','Clipboard unavailable. Save the reference instead.');}};$('save').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(chosen.reference,null,2)],{type:'application/json'}));a.href=u;a.download=data.document_id+'-selection.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$('load').onchange=async e=>{try{const f=e.target.files[0];if(f.size>64*1024*1024)throw Error('View file exceeds 64 MiB');load(JSON.parse(await f.text()));}catch(err){text('notice',err.message);}};new ResizeObserver(draw).observe(canvas);load(data);
</script></html>)HTML";
}
}
