# Portable production-input identity. No Git metadata, timestamps or host paths.
function(agentcad_source_manifest source_root output)
  get_filename_component(source_root "${source_root}" ABSOLUTE)
  set(patterns)
  foreach(directory src include web third_party cmake)
    list(APPEND patterns "${source_root}/${directory}/*")
  endforeach()
  if(CMAKE_SCRIPT_MODE_FILE)
    file(GLOB_RECURSE sources LIST_DIRECTORIES FALSE ${patterns})
  else()
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE ${patterns})
  endif()
  list(APPEND sources "${source_root}/CMakeLists.txt" "${source_root}/VERSION")
  list(REMOVE_DUPLICATES sources)
  list(SORT sources)
  set(manifest "")
  foreach(source IN LISTS sources)
    if(NOT EXISTS "${source}" OR IS_SYMLINK "${source}")
      message(FATAL_ERROR "Source identity requires regular production inputs: ${source}")
    endif()
    file(RELATIVE_PATH relative "${source_root}" "${source}")
    if(relative MATCHES "[\r\n]" OR relative MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "Unsafe source identity path")
    endif()
    file(SHA256 "${source}" digest)
    string(APPEND manifest "${digest}  ${relative}\n")
    if(NOT CMAKE_SCRIPT_MODE_FILE)
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
    endif()
  endforeach()
  set(${output} "${manifest}" PARENT_SCOPE)
endfunction()

# Shared install-time verification; deliberately independent of Git state.
function(agentcad_verify_source_stamp source_root input_manifest expected_source stamp_file executable output)
  agentcad_source_manifest("${source_root}" current_source)
  file(READ "${input_manifest}" configured_source)
  if(NOT current_source STREQUAL configured_source)
    message(FATAL_ERROR "Production source changed after configure/build; rebuild before packaging")
  endif()
  string(SHA256 source_hash "${configured_source}")
  if(NOT source_hash STREQUAL expected_source)
    message(FATAL_ERROR "Source manifest differs from configured identity")
  endif()
  file(READ "${stamp_file}" build_identity)
  string(JSON built_source GET "${build_identity}" source_sha256)
  string(JSON built_executable GET "${build_identity}" executable_sha256)
  file(SHA256 "${executable}" actual_executable)
  if(NOT built_source STREQUAL source_hash OR NOT built_executable STREQUAL actual_executable)
    message(FATAL_ERROR "Native executable differs from its successful build/source stamp; rebuild before packaging")
  endif()
  set(${output} "${build_identity}" PARENT_SCOPE)
endfunction()

# Developer/CI inspection entrypoint; the exact same function stamps the build.
if(CMAKE_SCRIPT_MODE_FILE AND DEFINED OUTPUT_MANIFEST)
  if(NOT DEFINED SOURCE_ROOT OR NOT IS_DIRECTORY "${SOURCE_ROOT}")
    message(FATAL_ERROR "SOURCE_ROOT must name the production checkout")
  endif()
  agentcad_source_manifest("${SOURCE_ROOT}" source_manifest)
  file(WRITE "${OUTPUT_MANIFEST}" "${source_manifest}")
endif()
