# Called only after the native target links successfully.
include("${SOURCE_ROOT}/cmake/SourceIdentity.cmake")
agentcad_source_manifest("${SOURCE_ROOT}" current)
file(READ "${INPUT_MANIFEST}" configured)
if(NOT current STREQUAL configured)
  message(FATAL_ERROR "Production source changed during build; reconfigure and rebuild")
endif()
string(SHA256 source_hash "${configured}")
file(READ "${SETTINGS_FILE}" stamp)
string(JSON expected_source GET "${stamp}" source_sha256)
if(NOT expected_source STREQUAL source_hash)
  message(FATAL_ERROR "Configured source manifest does not match build settings")
endif()
file(SHA256 "${EXECUTABLE}" executable_hash)
string(JSON stamp SET "${stamp}" executable_sha256 "\"${executable_hash}\"")
file(WRITE "${OUTPUT_FILE}.pending" "${stamp}\n")
file(RENAME "${OUTPUT_FILE}.pending" "${OUTPUT_FILE}")
